var searchData=
[
  ['changed_0',['changed',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CHANGELOG.html#autotoc_md34',1,'Changed'],['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CHANGELOG.html#autotoc_md26',1,'Changed'],['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CHANGELOG.html#autotoc_md18',1,'Changed']]],
  ['changelog_1',['Changelog',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CHANGELOG.html',1,'']]],
  ['changelog_2emd_2',['CHANGELOG.md',['../CHANGELOG_8md.html',1,'']]],
  ['clean_20and_20re_20compile_3',['Clean and re-compile',['../index.html#autotoc_md11',1,'']]],
  ['client_4',['Client',['../classClient.html',1,'']]],
  ['code_5',['Source Code',['../index.html#autotoc_md8',1,'']]],
  ['code_20documentation_6',['code documentation',['../index.html#autotoc_md13',1,'Generating Source Code Documentation'],['../index.html#autotoc_md9',1,'Source Code Documentation']]],
  ['code_20of_20conduct_7',['Contributor Covenant Code of Conduct',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CODE__OF__CONDUCT.html',1,'']]],
  ['code_5fof_5fconduct_2emd_8',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['compile_9',['Clean and re-compile',['../index.html#autotoc_md11',1,'']]],
  ['conclusion_10',['Conclusion',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CONTRIBUTING.html#autotoc_md49',1,'']]],
  ['conduct_11',['Contributor Covenant Code of Conduct',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CODE__OF__CONDUCT.html',1,'']]],
  ['configuration_12',['Configuration',['../index.html#autotoc_md2',1,'']]],
  ['connectconfig_13',['ConnectConfig',['../ssh2_8d_8ts.html#a0b6cfa99430ba3e65ebbd110bc30d9c2',1,'ssh2.d.ts']]],
  ['connections_14',['Working with SSH connections',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CONTRIBUTING.html#autotoc_md46',1,'']]],
  ['constructor_15',['constructor',['../classSidebarViewProvider.html#a093499da7eddfe81b07d81750ac60ea3',1,'SidebarViewProvider::constructor()'],['../classLogSession.html#a61ef78d4d91ff8936a528899795808bd',1,'LogSession::constructor()'],['../classLogPanel.html#aa1db5b9f66c2765588aa1f9d050134c8',1,'LogPanel::constructor()'],['../classDeviceItem.html#af6e5dc5302e9a62804e860ae463f0d96',1,'DeviceItem::constructor()'],['../classDeviceTreeDataProvider.html#a6f116f5ee766acbc3d0d348c8d17d656',1,'DeviceTreeDataProvider::constructor()']]],
  ['contact_16',['Contact',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2SECURITY.html#autotoc_md64',1,'']]],
  ['contributing_20guidelines_20for_20vscode‑logger_17',['Contributing Guidelines for VSCode‑Logger',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_18',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['contribution_20guidelines_19',['Contribution guidelines',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CONTRIBUTING.html#autotoc_md43',1,'']]],
  ['contributor_20covenant_20code_20of_20conduct_20',['Contributor Covenant Code of Conduct',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CODE__OF__CONDUCT.html',1,'']]],
  ['correction_21',['1. Correction',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CODE__OF__CONDUCT.html#autotoc_md57',1,'']]],
  ['covenant_20code_20of_20conduct_22',['Contributor Covenant Code of Conduct',['../md__2home_2runner_2work_2VSCode-Logger_2VSCode-Logger_2CODE__OF__CONDUCT.html',1,'']]]
];
