/* eslint-disable spellcheck/spell-checker */
import type { en } from './en';

export const cs: typeof en = {
  languageId: 'cs',
  htmlLang: 'cs',
  languageNames: {
    vscode: 'Výchozí VSCode',
    en: 'Angličtina',
    es: 'Španělština',
    it: 'Italština',
    'zh-cn': 'Zjednodušená čínština',
    'zh-tw': 'Tradiční čínština',
    fr: 'Francouzština',
    de: 'Němčina',
    ja: 'Japonština',
    ko: 'Korejština',
    ru: 'Ruština',
    'pt-br': 'Portugalština (Brazílie)',
    tr: 'Turečtina',
    pl: 'Polština',
    cs: 'Čeština',
    hu: 'Maďarština',
  },
  common: {
    add: 'Přidat',
    cancel: 'Zrušit',
    close: 'Zavřít',
    command: 'Příkaz',
    copy: 'Kopírovat',
    default: 'Výchozí',
    disabled: 'Zakázáno',
    enabled: 'Povoleno',
    exportSettings: 'Exportovat nastavení',
    importSettings: 'Importovat nastavení',
    name: 'Název',
    none: 'Žádné',
    remove: 'Odebrat',
    save: 'Uložit',
    select: 'Vybrat',
  },
  deviceManager: {
    title: 'Vložený záznamník zařízení v{version}',
    panelTitle: 'Správce embedded zařízení',
    intro: 'Spravujte zařízení a výchozí konfiguraci.',
    removeStoredPasswords: 'Odstranit uložená hesla',
    editJson: 'Upravit v JSON',
    viewConfigurationExample: 'Zobrazit příklad konfigurace',
    saveChanges: 'Uložit změny',
    defaults: 'Výchozí',
    defaultsDescription:
      'Výchozí hodnoty pro všechna zařízení. Každé zařízení jej může v případě potřeby změnit v tabulce zařízení.',
    enableSshTerminal: 'Povolit terminál SSH',
    enableSftpExplorer: 'Povolit průzkumníka SFTP',
    enableExternalWebBrowser: 'Povolit externí webový prohlížeč',
    enableEmbeddedWebBrowser: 'Povolit vložený webový prohlížeč',
    enableDevicePing: 'Povolit ping zařízení',
    showBastionOptions: 'Zobrazit moznosti bastionu',
    language: 'Jazyk rozšíření',
    port: 'Přístav',
    logCommand: 'Příkaz záznamu',
    maxLinesPerTab: 'Maximální řádky na kartě',
    pingIntervalSeconds: 'Ping interval (sekundy)',
    pingIntervalPlaceholder: 'Zanechat prázdné pouze pro ruční ping',
    sshCommands: 'Příkazy SSH',
    groups: 'Skupiny',
    groupsDescription:
      'Definujte volitelné skupiny pro organizaci zařízení v zobrazení vestavěných zařízení.',
    addGroup: 'Přidat skupinu',
    devices: 'Zařízení',
    devicesDescription: 'Přidat nebo odstranit řádky, pak upravit pole inline.',
    addDevice: 'Přidat zařízení',
    moveSelectedDevicesUp: 'Přesunout vybraná zařízení nahoru v seznamu',
    moveSelectedDevicesDown: 'Přesunout vybraná zařízení do seznamu',
    resetPassword: 'Obnovit heslo',
    removeStoredPasswordsForSelectedDevices: 'Odstranit uložená hesla a hesla pro vybraná zařízení',
    columnId: 'ID',
    columnGroup: 'Skupina',
    columnColor: 'Barva',
    columnHost: 'Hostitel',
    columnUser: 'Uživatel',
    columnHostFingerprint: 'Otisk prstu hostitele',
    columnSecondaryHost: 'Sekundární hostitel',
    columnSecondaryFingerprint: 'Sekundární otisk prstu',
    columnSshTerminal: 'Terminál SSH',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'SFTP předvolby (vzdálené)',
    columnSftpPresetsLocal: 'SFTP presety (lokální)',
    columnExternalWebBrowser: 'Externí webový prohlížeč',
    columnEmbeddedWebBrowser: 'Name',
    columnWebUrl: 'Web URL',
    columnPrivateKeyPath: 'Soukromá klíčová cesta',
    columnPrivateKeyPassphrase: 'Privátní heslo',
    columnPasswordWriteOnly: 'Heslo (pouze pro zápis)',
    columnShowDefaultSshCommands: 'Zobrazit výchozí příkazy SSH',
    columnBastionHost: 'Bastion hostitel',
    columnBastionPort: 'Bastion port',
    columnBastionUser: 'Uživatel bašty',
    columnBastionFingerprint: 'Otisk bastionu',
    columnBastionKeyPath: 'Cesta klíče bašty',
    columnBastionKeyPassphrase: 'Passplasa klíče bastionu',
    columnBastionPasswordWriteOnly: 'Bastion heslo (pouze pro zápis)',
    groupNamePlaceholder: 'Název skupiny',
    editScript: 'Upravit skript',
    editScriptFor: 'Upravit skript pro {name}',
    sshCommandFallback: 'Příkaz SSH',
    scriptDescription: 'Napište skript, který bude zkopírován do /tmp a proveden.',
    sshCommandScriptEditor: 'Name',
    commandNamesEmojiHelp: 'Příkazová jména podporují smajlíky z https://emojidb.org/',
    openSshPanel: 'Otevřít SSH Panel',
    rerunOnReconnection: 'Znovu spustit při opětovném připojení',
    copyAndRunScript: 'Kopírovat a spustit skript',
    addCommand: 'Přidat příkaz',
    openCommandInSshPanel: 'Otevřít tento příkaz v panelu SSH',
    openNamedCommandInSshPanel: 'Otevřít {name} v panelu SSH',
    rerunCommandAfterReconnect: 'Znovu spusťte tento příkaz poté, co se panel SSH znovu spojí',
    rerunNamedCommandOnReconnect: 'Respun {name} při opětovném připojení',
    copyScriptToTmp: 'Kopírovat skript do /tmp a spustit ho po příkazu',
    copyAndRunScriptFor: 'Kopírovat a spustit skript pro {name}',
    removeCommand: 'Odstranit příkaz',
    dragToResize: 'Přetáhněte do přestavby',
    selectDeviceRow: 'Vybrat řádek zařízení',
    removedSelectedDevice: 'Odstraněno vybrané zařízení.',
    removedSelectedDevices: 'Odstraněna vybraná zařízení {count}.',
    saving: 'Zachraňuji...',
    openingSettingsJson: 'Otevírám settings.json...',
    removingStoredPasswords: 'Odstranění uložených hesel...',
    exportingSettings: 'Vyvážející nastavení...',
    importingSettings: 'Importování nastavení...',
    setSelectedDeviceIdBeforeReset:
      'Před opětovným nastavením uloženého hesla nastavte alespoň jedno zvolené zařízení ID.',
    removingStoredPasswordForDevice: 'Odstranění uloženého hesla pro {id}...',
    removingStoredPasswordsForDevices: 'Odstranění uložených hesel pro vybraná zařízení {count}...',
    configurationExample: 'Příklad konfigurace',
    configurationExampleDescription: 'Zkopírujte a vložte tyto vady do Vašeho settings.json.',
    copiedConfigurationExample: 'Kopírovaný příklad konfigurace.',
    failedToCopyConfigurationExample: 'Chyba při kopírování příkladu konfigurace.',
    savedSettings: 'Uložené nastavení.',
    failedToSaveSettings: 'Nepodařilo se uložit nastavení.',
    importedSettingsApply:
      'Importované nastavení. Zkontrolujte je a klepněte na tlačítko Uložit změny je použít.',
    failedToImportSettings: 'Nepodařilo se importovat nastavení.',
    exportSettingsSaveLabel: 'Nastavení exportu',
    exportCanceled: 'Export zrušen.',
    exportedSettingsTo: 'Exportované nastavení do {path}.',
    failedToExportSettings: 'Nastavení exportu selhalo: {message}',
    importSettingsOpenLabel: 'Nastavení importu',
    importCanceled: 'Import zrušen.',
    importedSettingsFrom:
      'Importované nastavení {path}. Recenze a klepněte na tlačítko Uložit změny je použít.',
    failedToImportSettingsWithMessage: 'Nastavení importu selhalo: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      'Uložené nastavení. Obnovit okno nebo rozšíření hostitele, pak uložit znovu pokračovat v nastavení vestavěný webový prohlížeč.',
    reloadToPersistNewDefaultSettings:
      'Nastavení uloženo. Znovu načtěte okno nebo hostitele rozšíření a poté uložte znovu, aby se nově přidaná výchozí nastavení zachovala.',
  },
  sidebar: {
    title: 'Zabudovaná záznamová zařízení',
    copyUrl: 'Kopírovat URL',
    copyName: 'Kopírovat',
    pingInProgress: 'Probíhá ping',
    pingReachable: 'Ping dosažitelný',
    pingUnreachable: 'Ping nedostupný',
    openLogs: 'Otevřít záznamy',
    openLogsFor: 'Otevřené protokoly pro {name}',
    openSshTerminal: 'Otevřít SSH Terminál',
    openSshTerminalFor: 'Otevřít terminál SSH pro {name}',
    openSftpExplorer: 'Otevřít SFTP Explorer',
    browseAndTransferFilesFor: 'Procházení a přenos souborů pro {name}',
    openExternalWebBrowser: 'Otevřít externí webový prohlížeč',
    openExternalWebBrowserFor: 'Otevřít nakonfigurovaný web URL pro {name} v externím prohlížeči',
    openEmbeddedWebBrowser: 'Otevřít vestavěný webový prohlížeč',
    openEmbeddedWebBrowserFor: 'Otevřít konfigurovaný web URL pro {name} v VS Code',
    copyScriptCommandTitle: 'Kopírovat skript na /tmp, chmod 777, a spustit ho',
    noDevicesConfigured: 'Žádná zařízení. Aktualizovat "embeddedLogger.devices" v nastavení.',
    deviceNameLabel: 'Název zařízení',
    deviceUrlLabel: 'Zařízení URL',
    copiedToClipboard: '{label} zkopíroval do schránky.',
  },
  deviceTree: {
    noDevicesConfigured: 'Žádná zařízení. Aktualizovat "embeddedLogger.devices" v nastavení.',
    openSettingsToConfigure: 'Otevřít nastavení pro konfiguraci vložených zařízení.',
    openSettings: 'Otevřít nastavení',
    openDeviceLogs: 'Otevřít záznamy zařízení',
    groupTooltip: '{name} skupina',
  },
  logPanel: {
    logsTitle: '{name} Záznamy',
    minLevel: 'Min level',
    textFilter: 'Textový filtr',
    filterSubstring: 'Filtrační podřetězec',
    filteringPresets: 'Filtrační predy',
    filterPresets: 'Filtrační předvolby',
    savePreset: 'Uložit preset',
    deletePreset: 'Smazat přednastavený',
    exportLogs: 'Záznamy o vývozu',
    editLogFile: 'Upravit soubor záznamu',
    refreshLogFile: 'Obnovit soubor záznamu',
    startAutoSave: 'Spustit automatické ukládání',
    stopAutoSave: 'Stop auto- save',
    clearLogs: 'Smazat protokoly',
    highlight: 'Zvýraznění',
    wordWrap: 'Slovní obal',
    autoScroll: 'Auto- svitek',
    autoReconnect: 'Automatické připojení',
    toggleState: '{label} ({state})',
    toggleOn: 'n',
    toggleOff: 'vypnuto',
    find: 'Najít',
    findInLogs: 'Najít v protokolech (Ctrl/Cmd+F)',
    clearSearch: 'Vymazat vyhledávání',
    previousMatch: 'Předchozí zápas',
    nextMatch: 'Další zápas',
    prev: 'Předcházející',
    next: 'Další',
    reconnect: 'Rozpuštění',
    disconnect: 'Odpojení',
    highlights: 'Zvýraznění',
    addHighlight: 'přidat',
    removeAllHighlights: 'odstranit všechny',
    highlightKeywords: 'Zvýraznit klíčová slova',
    lineLimitLive: 'Dosáhla nastavená čára displeje. Starší řádky se nahrazují novějšími vstupy.',
    lineLimitOffline:
      'Dosáhla nastavená čára displeje. Starší importované linky byly skryty z tohoto pohledu.',
    upToTenHighlights: 'Můžete zvýraznit až 10 klíčů.',
    keyToHighlight: 'Klíč k zvýraznění',
    removeHighlight: 'Odstranit zvýraznění',
    noPreset: '(bez předvolání)',
    filterPresetNamed: 'Přednastavený filtr: {name}',
    connectedStreaming: 'Připojeno. Vysílání záznamů...',
    bookmarkLabel: 'Štítek záložky',
    enterBookmarkLabel: 'Zadejte štítek záložky',
    addBookmark: 'Přidat záložku',
    editBookmarkLabel: 'Upravit štítek záložky',
    removeBookmark: 'Odstranit záložku',
    removeAllBookmarks: 'Odstranit všechny záložky',
    goToNextBookmark: 'Přejít na další záložku',
    goToPreviousBookmark: 'Přejít na předchozí záložku',
    clearStatusMessage: 'Vymazat zprávu o stavu',
    connectionClosed: 'Spojení ukončeno.',
    retryingInSeconds: '{message} Znovu v {seconds} sekundách...',
    reconnecting: 'Obnovuji...',
    disconnecting: 'Odpojení...',
    hostKeyFailedDetails:
      'Ověření klíče pro hosty selhalo. Očekáván {expected}, ale obdržel {received}. Aktualizujte otisk prstu, aby se znovu spojil.',
    hostKeyFailed:
      'Ověření klíče pro hosty selhalo. Před opětovným připojením aktualizujte uložené otisky prstů.',
    sessionClosed: 'Sezení bylo ukončeno.',
    sshSessionClosedOn: '--- SSH relace ukončena na {timestamp}',
    dateAtTime: '{date} na {time}',
    autoSavingTo: 'Automatické ukládání do',
    autoSaveEnabled: 'Automatické uložení povoleno.',
    autoSaveFailed: 'Automatické šetření selhalo.',
    waitingForPassword: 'Čekání, až uživatel zadá heslo..',
  },
  extension: {
    missingHost: 'Zařízení "{name}" chybí hostitel.',
    missingUsername: 'Zařízení "{name}" chybí uživatelské jméno.',
    invalidPort: 'Zařízení "{name}" má neplatný port.',
    credentialsMigrationWarning:
      'Kredity byly přesunuty do Secret Storage, ale nelze odstranit "heslo" nebo "privateKeyPasspase". Prosím vymažte je ze embeddedLogger.devices ve vašem nastavení.',
    sftpPresetsMigrationFailed:
      'Nepodařilo se migrovat presety SFTP do presetů embeddedLogger.devices. Existující zůstávají v prodlouženém úložišti.',
    noHostFound: 'Pro vybrané zařízení není nalezen žádný hostitel.',
    webUrlMustStart: 'Webový prohlížeč URLs musí začít s http: / / nebo https://.',
    invalidWebUrl: 'Neplatný web URL pro {name}: {message}',
    deviceNotFound: 'Zařízení nenalezeno. embeddedLogger.devices.',
    workspaceTrustDeviceResources:
      'Před otevřením zdrojů zařízení je vyžadována důvěra v pracovní prostor.',
    workspaceTrustConnect: 'Před připojením k zařízení je vyžadována důvěra v pracovní prostor.',
    embeddedBrowserUnavailable: 'Podpora zabudovaného prohlížeče VS Code není k dispozici.',
    failedToOpenUri: 'Nepodařilo se otevřít {uri}: {message}',
    sshCommandNoControlCharacters: 'Příkaz SSH nesmí obsahovat kontrolní znaky nebo nové řádky.',
    runningCommandOnDevice: 'Běžící "{command}" na {device}',
    commandFinishedOnDevice: 'Příkaz "{command}" dokončen na {device}.',
    noDevicesConfigured: 'Žádná zařízení. embeddedLogger.devices.',
    selectDeviceForSftp: 'Vyberte zařízení pro otevření průzkumníka SFTP',
    selectDeviceForExternalBrowser: 'Vyberte zařízení k otevření ve vnějším webovém prohlížeči',
    selectDeviceForEmbeddedBrowser: 'Vyberte zařízení k otevření v vloženém webovém prohlížeči',
    storedPasswordsRemovedFor: 'Pro {device} byla odstraněna uložená hesla a hesla.',
    noDevicesToClearPasswords: 'Žádná zařízení nenakonfigurovaná pro vyčištění hesel.',
    storedPasswordsRemoved: 'Pro nakonfigurovaná zařízení byla odstraněna uložená hesla a hesla.',
    openLogFile: 'Otevřít soubor záznamu',
    failedToReadLogFile: 'Chyba při čtení souboru záznamu: {message}',
    localPanelSuffix: 'Místní',
    noDeviceInfo: 'Žádné informace o zařízení.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Nelze vytvořit relaci záznamu bez zařízení.',
    loadedLines: 'Nabité linky {count}.',
    presetSaved: 'Preset "{name}" uložen pro {target}.',
    presetRemoved: 'Preset "{name}" odstraněn pro {target}.',
    exportLogsSaveLabel: 'Záznamy o vývozu',
    exportedLines: 'Exported {count} lines from {target}.',
    failedToExportLogs: 'Nepodařilo se exportovat protokoly: {message}',
    failedToExportLogsFallback: 'Nepodařilo se exportovat protokoly.',
    editOnlyImported: 'Edit je k dispozici pouze pro importované logové soubory.',
    failedToOpenLogFile: 'Nepodařilo se otevřít soubor záznamu: {message}',
    failedToOpenLogFileFallback: 'Nepodařilo se otevřít soubor záznamu.',
    refreshOnlyImported: 'Refresh je k dispozici pouze pro importované logové soubory.',
    failedToReadLogFile: 'Chyba při čtení souboru záznamu: {message}',
    failedToReadLogFileFallback: 'Nepodařilo se přečíst soubor záznamu.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: 'Sezení bylo ukončeno.',
    disconnected: 'Odpojeno.',
    reconnecting: 'Obnovuji...',
    failedToReconnect: 'Selhalo spojení.',
    autoSaveDialogTitle: 'Vyberte logový soubor k automatickému uložení výstupu SSH',
    allFiles: 'Všechny soubory',
    autoSaveCancelled: 'Automatické uložení zrušeno.',
    autoSaveFailed: 'Automatické uložení selhalo: {message}',
    autoSaveFailedFallback: 'Automatické šetření selhalo.',
    hostKeyVerificationFailed:
      'Ověření klíče pro hosty selhalo pro {target}. Očekáván {expected}, ale obdržel {received}. Aktualizovat otisk prstu v nastavení pro opětovné připojení.',
    sshSessionClosedOn: '--- SSH relace ukončena na {timestamp}',
  },
};
