/* eslint-disable spellcheck/spell-checker */
import type { en } from './en';

export const de: typeof en = {
  languageId: 'de',
  htmlLang: 'de',
  languageNames: {
    vscode: 'VSCode-Standard',
    en: 'Englisch',
    es: 'Spanisch',
    it: 'Italienisch',
    'zh-cn': 'Vereinfachtes Chinesisch',
    'zh-tw': 'Traditionelles Chinesisch',
    fr: 'Französisch',
    de: 'Deutsch',
    ja: 'Japanisch',
    ko: 'Koreanisch',
    ru: 'Russisch',
    'pt-br': 'Portugiesisch (Brasilien)',
    tr: 'Türkisch',
    pl: 'Polnisch',
    cs: 'Tschechisch',
    hu: 'Ungarisch',
  },
  common: {
    add: 'Hinzufügen',
    cancel: 'Abbrechen',
    close: 'Schließen',
    command: 'Befehl',
    copy: 'Kopieren',
    default: 'Standard',
    disabled: 'Deaktiviert',
    enabled: 'Aktiviert',
    exportSettings: 'Einstellungen exportieren',
    importSettings: 'Einstellungen importieren',
    name: 'Name',
    none: 'Keine',
    remove: 'Entfernen',
    save: 'Speichern',
    select: 'Auswählen',
  },
  deviceManager: {
    title: 'Embedded Device Logger v{version}',
    panelTitle: 'Manager für eingebettete Geräte',
    intro: 'Geräte und Standardkonfiguration verwalten.',
    removeStoredPasswords: 'Gespeicherte Passwörter entfernen',
    editJson: 'Bearbeiten in JSON',
    viewConfigurationExample: 'Konfigurationsbeispiel anzeigen',
    saveChanges: 'Änderungen speichern',
    defaults: 'Fehler',
    defaultsDescription:
      'Standardwerte für alle Geräte. Jedes Gerät kann es auf Wunsch in Gerätetabelle ändern.',
    enableSshTerminal: 'SSH Terminal aktivieren',
    enableSftpExplorer: 'SFTP Explorer aktivieren',
    enableExternalWebBrowser: 'Externer Webbrowser aktivieren',
    enableEmbeddedWebBrowser: 'Ein eingebetteter Webbrowser aktivieren',
    enableDevicePing: 'Gerätepistole aktivieren',
    showBastionOptions: 'Bastion-Optionen anzeigen',
    language: 'Erweiterungssprache',
    port: 'Hafen',
    logCommand: 'Log-Befehl',
    maxLinesPerTab: 'Max Linien pro Tab',
    pingIntervalSeconds: 'Ping-Intervall (Sekunden)',
    pingIntervalPlaceholder: 'Nur für manuelles Ping leeren',
    sshCommands: 'SSH Befehle',
    groups: 'Gruppen',
    groupsDescription:
      'Definieren Sie optionale Gruppen, um Geräte in der Ansicht Embedded Devices zu organisieren.',
    addGroup: 'Gruppe hinzufügen',
    devices: 'Geräte',
    devicesDescription: 'Zeilen hinzufügen oder entfernen, dann Felder inline bearbeiten.',
    addDevice: 'Gerät hinzufügen',
    moveSelectedDevicesUp: 'Ausgewählte Geräte in der Liste verschieben',
    moveSelectedDevicesDown: 'Ausgewählte Geräte in der Liste nach unten verschieben',
    resetPassword: 'Passwort vergessen',
    removeStoredPasswordsForSelectedDevices:
      'Entfernen Sie gespeicherte Passwörter und Passphrasen für ausgewählte Geräte',
    columnId: 'ID',
    columnGroup: 'Gruppe',
    columnColor: 'Farbe',
    columnHost: 'Gastgeber',
    columnUser: 'Benutzer',
    columnHostFingerprint: 'Host Fingerabdruck',
    columnSecondaryHost: 'Sekundäre Gastgeber',
    columnSecondaryFingerprint: 'Sekundärer Fingerabdruck',
    columnSshTerminal: 'SSH Terminal',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'SFTP Presets (Remote)',
    columnSftpPresetsLocal: 'SFTP Presets (lokal)',
    columnExternalWebBrowser: 'Externer Browser',
    columnEmbeddedWebBrowser: 'Embedded Web Browser',
    columnWebUrl: 'Web URL',
    columnPrivateKeyPath: 'Privater Schlüsselweg',
    columnPrivateKeyPassphrase: 'Private Schlüssel passphrase',
    columnPasswordWriteOnly: 'Passwort (nur schreiben)',
    columnShowDefaultSshCommands: 'Standard-SSH-Befehle anzeigen',
    columnBastionHost: 'Bastion Gastgeber',
    columnBastionPort: 'Bastion Hafen',
    columnBastionUser: 'Bastion Benutzer',
    columnBastionFingerprint: 'Bastion Fingerabdruck',
    columnBastionKeyPath: 'Bastion Schlüsselweg',
    columnBastionKeyPassphrase: 'Bastion Schlüssel passphras',
    columnBastionPasswordWriteOnly: 'Bastion Passwort (nur schreiben)',
    groupNamePlaceholder: 'Bezeichnung',
    editScript: 'Skript bearbeiten',
    editScriptFor: 'Skript bearbeiten für {name}',
    sshCommandFallback: 'SSH Befehl',
    scriptDescription: 'Schreiben Sie das Skript, das auf /tmp kopiert und ausgeführt wird.',
    sshCommandScriptEditor: 'SSH Befehlsskript Editor',
    commandNamesEmojiHelp: 'Befehlsnamen unterstützen Emojis von https://emojidb.org/',
    openSshPanel: 'SSH öffnen Panel',
    rerunOnReconnection: 'Wiederaufschaltung',
    copyAndRunScript: 'Kopieren und Ausführen von Skript',
    addCommand: 'Befehl hinzufügen',
    openCommandInSshPanel: 'Öffnen Sie diesen Befehl in einem SSH-Panel',
    openNamedCommandInSshPanel: '{name} öffnen in SSH Panel',
    rerunCommandAfterReconnect:
      'Führen Sie diesen Befehl erneut aus, nachdem das SSH-Panel wieder angeschlossen ist',
    rerunNamedCommandOnReconnect: 'Re-run {name} auf Wiederverbindung',
    copyScriptToTmp: 'Kopieren Sie ein Skript in /tmp und führen Sie es nach dem Befehl aus',
    copyAndRunScriptFor: 'Skript kopieren und ausführen für {name}',
    removeCommand: 'Befehl löschen',
    dragToResize: 'Drag to reize',
    selectDeviceRow: 'Wählen Sie die Gerätezeile',
    removedSelectedDevice: 'Entfernte ausgewählte Vorrichtung.',
    removedSelectedDevices: 'Entfernen von {count} ausgewählten Geräten.',
    saving: 'Sparen...',
    openingSettingsJson: 'settings.json öffnen...',
    removingStoredPasswords: 'Abgespeicherte Passwörter entfernen...',
    exportingSettings: 'Exportieren von Einstellungen...',
    importingSettings: 'Importieren von Einstellungen...',
    setSelectedDeviceIdBeforeReset:
      'Setzen Sie mindestens ein ausgewähltes Gerät ID vor dem Zurücksetzen des gespeicherten Passworts.',
    removingStoredPasswordForDevice: 'Entfernen des gespeicherten Passworts für {id}...',
    removingStoredPasswordsForDevices:
      'Entfernen von gespeicherten Passwörtern für {count} ausgewählte Geräte...',
    configurationExample: 'Konfigurationsbeispiel',
    configurationExampleDescription:
      'Kopieren und fügen Sie diese Standardeinstellungen in Ihr settings.json ein.',
    copiedConfigurationExample: 'Copied Konfiguration Beispiel.',
    failedToCopyConfigurationExample: 'Nicht kopieren Konfiguration Beispiel.',
    savedSettings: 'Gespeicherte Einstellungen.',
    failedToSaveSettings: 'Versäumt, Einstellungen zu speichern.',
    importedSettingsApply:
      'Importierte Einstellungen. Überprüfen Sie sie und klicken Sie auf Änderungen speichern, um sie anzuwenden.',
    failedToImportSettings: 'Nicht importiert Einstellungen.',
    exportSettingsSaveLabel: 'Exporteinstellungen',
    exportCanceled: 'Export storniert.',
    exportedSettingsTo: 'Exportierte Einstellungen in {path}.',
    failedToExportSettings: 'Nicht exportiert: {message}',
    importSettingsOpenLabel: 'Importeinstellungen',
    importCanceled: 'Import storniert.',
    importedSettingsFrom:
      'Importierte Einstellungen von {path}. Überprüfen und klicken Sie auf Änderungen speichern, um sie anzuwenden.',
    failedToImportSettingsWithMessage: 'Nicht importiert: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      'Gespeicherte Einstellungen. Laden Sie den Fenster- oder Erweiterungs-Host neu, speichern Sie dann erneut, um den Embedded Web Browser-Standard zu bestehen.',
    reloadToPersistNewDefaultSettings:
      'Einstellungen gespeichert. Laden Sie das Fenster oder den Erweiterungshost neu und speichern Sie dann erneut, um neu hinzugefügte Standardeinstellungen beizubehalten.',
  },
  sidebar: {
    title: 'Embedded Logger Geräte',
    copyUrl: 'Kopieren von URL',
    copyName: 'Kopie des Namens',
    pingInProgress: 'Fortschritte',
    pingReachable: 'Zu erreichende',
    pingUnreachable: 'Nicht erreichbar',
    openLogs: 'Logs öffnen',
    openLogsFor: 'Protokolle für {name} öffnen',
    openSshTerminal: 'SSH öffnen Terminal',
    openSshTerminalFor: 'Öffne eine SSH-Terminalsitzung für {name}',
    openSftpExplorer: 'SFTP öffnen Explorer',
    browseAndTransferFilesFor: 'Durchsuchen und übertragen von Dateien für {name}',
    openExternalWebBrowser: 'Externer Browser öffnen',
    openExternalWebBrowserFor:
      'Öffne das konfigurierte Web URL für {name} in einem externen Browser',
    openEmbeddedWebBrowser: 'Open Embedded Web Browser',
    openEmbeddedWebBrowserFor: 'Öffne das konfigurierte Web URL für {name} in VS Code',
    copyScriptCommandTitle: 'Kopieren Sie Skript in /tmp, chmod 777 und führen Sie es aus',
    noDevicesConfigured:
      'Keine Geräte konfiguriert. Aktualisieren Sie "embeddedLogger.devices" in Einstellungen.',
    deviceNameLabel: 'Bezeichnung des Geräts',
    deviceUrlLabel: 'Gerät URL',
    copiedToClipboard: '{label} kopiert auf Zwischenablage.',
  },
  deviceTree: {
    noDevicesConfigured:
      'Keine Geräte konfiguriert. Aktualisieren Sie "embeddedLogger.devices" in Einstellungen.',
    openSettingsToConfigure: 'Öffnen Sie Einstellungen, um eingebettete Geräte zu konfigurieren.',
    openSettings: 'Offene Einstellungen',
    openDeviceLogs: 'Gerätelogos öffnen',
    groupTooltip: '{name} Gruppe',
  },
  logPanel: {
    logsTitle: '{name} Logs',
    minLevel: 'Mindestens',
    textFilter: 'Text filtern',
    filterSubstring: 'Filter Substring',
    filteringPresets: 'Filtervoreinstellungen',
    filterPresets: 'Filtervoreinstellungen',
    savePreset: 'Voreinstellung speichern',
    deletePreset: 'Voreinstellung löschen',
    exportLogs: 'Exportprotokolle',
    editLogFile: 'Protokolldatei bearbeiten',
    refreshLogFile: 'Aktualisieren der Datei',
    startAutoSave: 'Auto-Save starten',
    stopAutoSave: 'Autospeicher stoppen',
    clearLogs: 'Logs löschen',
    highlight: 'Höhepunkt',
    wordWrap: 'Wortpackung',
    autoScroll: 'Auto-Scroll',
    autoReconnect: 'Auto-Reconnect',
    toggleState: '{label} ({state})',
    toggleOn: 'auf',
    toggleOff: 'ab',
    find: 'Finden',
    findInLogs: 'Finden Sie in Protokollen (Ctrl/Cmd+F)',
    clearSearch: 'Suche löschen',
    previousMatch: 'Zurück zur Übersicht',
    nextMatch: 'Nächstes Spiel',
    prev: 'Vor',
    next: 'Nächste',
    reconnect: 'Reconnect',
    disconnect: 'Trennen',
    highlights: 'Highlights',
    addHighlight: 'hinzufügen',
    removeAllHighlights: 'alle entfernen',
    highlightKeywords: 'Schlüsselwörter markieren',
    lineLimitLive:
      'Konfigurierte Anzeigezeilengrenze erreicht. Ältere Linien werden durch neuere Einträge ersetzt.',
    lineLimitOffline:
      'Konfigurierte Anzeigezeilengrenze erreicht. Ältere importierte Linien wurden von dieser Ansicht versteckt.',
    upToTenHighlights: 'Sie können bis zu 10 Tasten markieren.',
    keyToHighlight: 'Schlüssel zum Highlight',
    removeHighlight: 'Entfernen Sie das Highlight',
    noPreset: '(keine voreinstellung)',
    filterPresetNamed: 'Filtervoreinstellung: {name}',
    connectedStreaming: 'Vernetzt. Logs zu streamen...',
    bookmarkLabel: 'Lesezeichen',
    enterBookmarkLabel: 'Beschriftungszeichen',
    addBookmark: 'Lesezeichen hinzufügen',
    editBookmarkLabel: 'Bookmark Label bearbeiten',
    removeBookmark: 'Lesezeichen entfernen',
    removeAllBookmarks: 'Alle Lesezeichen entfernen',
    goToNextBookmark: 'Zum nächsten Bookmark',
    goToPreviousBookmark: 'Zum vorherigen Lesezeichen',
    clearStatusMessage: 'Statusmeldung löschen',
    connectionClosed: 'Verbindung geschlossen.',
    retryingInSeconds: '{message} Wiederholen in {seconds} Sekunden...',
    reconnecting: 'Wiederanschließen...',
    disconnecting: 'Die Verbindung...',
    hostKeyFailedDetails:
      'Host-Schlüsselverifikation fehlgeschlagen. Erwartete {expected}, erhielt jedoch {received}. Aktualisieren Sie den Fingerabdruck, um wieder zu verbinden.',
    hostKeyFailed:
      'Host-Schlüsselverifikation fehlgeschlagen. Aktualisieren Sie den gespeicherten Fingerabdruck vor dem erneuten Verbinden.',
    sessionClosed: 'Die Sitzung ist geschlossen.',
    sshSessionClosedOn: '--- SSH Sitzung geschlossen {timestamp}',
    dateAtTime: '{date} bei {time}',
    autoSavingTo: 'Autosparend für',
    autoSaveEnabled: 'Autospeicher aktiviert.',
    autoSaveFailed: 'Auto-Save versagt.',
    waitingForPassword: 'Warten auf den Benutzer, um das Passwort einzugeben..',
  },
  extension: {
    missingHost: 'Gerät "{name}" fehlt ein Host.',
    missingUsername: 'Das Gerät "{name}" fehlt einem Benutzernamen.',
    invalidPort: 'Das Gerät "{name}" hat einen ungültigen Port.',
    credentialsMigrationWarning:
      'Credentials wurden zu Secret Storage migriert, aber die Felder "Passwort" oder "privateKeyPassphrase" konnten nicht entfernt werden. Bitte löschen Sie sie von embeddedLogger.devices in Ihren Einstellungen.',
    sftpPresetsMigrationFailed:
      'Versäumt, SFTP-Voreinstellungen in embeddedLogger.devices. zu migrieren.',
    noHostFound: 'Kein Host für das ausgewählte Gerät gefunden.',
    webUrlMustStart: 'Webbrowser URLs muss mit http:// oder https://. starten',
    invalidWebUrl: 'Invalides Web URL für {name}: {message}',
    deviceNotFound: 'Gerät nicht gefunden. Überprüfen Sie embeddedLogger.devices.',
    workspaceTrustDeviceResources:
      'Workspace Trust ist erforderlich, bevor Geräteressourcen geöffnet werden.',
    workspaceTrustConnect: 'Workspace-Vertrauen ist vor dem Anschluss an Geräte erforderlich.',
    embeddedBrowserUnavailable: 'VS Code Embedded Browser-Unterstützung ist nicht verfügbar.',
    failedToOpenUri: 'Nicht zu öffnen {uri}: {message}',
    sshCommandNoControlCharacters:
      'SSH-Befehl darf keine Steuerzeichen oder neue Zeilen enthalten.',
    runningCommandOnDevice: 'Laufen "{command}" auf {device}',
    commandFinishedOnDevice: 'Befehl "{command}" beendete {device}.',
    noDevicesConfigured: 'Keine Geräte konfiguriert. Überprüfen Sie embeddedLogger.devices.',
    selectDeviceForSftp: 'Wählen Sie ein Gerät zum Öffnen des SFTP Explorers',
    selectDeviceForExternalBrowser: 'Wählen Sie ein Gerät zum Öffnen im externen Webbrowser',
    selectDeviceForEmbeddedBrowser: 'Wählen Sie ein Gerät zum Öffnen im eingebetteten Webbrowser',
    storedPasswordsRemovedFor:
      'Gespeicherte Passwörter und Passphrasen wurden für {device} entfernt.',
    noDevicesToClearPasswords: 'Keine Geräte konfiguriert, um Passwörter zu löschen.',
    storedPasswordsRemoved:
      'Für konfigurierte Geräte wurden gespeicherte Passwörter und Passphrasen entfernt.',
    openLogFile: 'Protokolldatei öffnen',
    failedToReadLogFile: 'Fehler beim Lesen der Protokolldatei: {message}',
    localPanelSuffix: 'Ort',
    noDeviceInfo: 'Keine Geräteinformationen geliefert.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Kann keine Protokollsitzung ohne Gerät erstellen.',
    loadedLines: 'Geladene {count} Linien.',
    presetSaved: 'Preset "{name}" für {target} gespeichert.',
    presetRemoved: 'Preset "{name}" für {target} entfernt.',
    exportLogsSaveLabel: 'Exportprotokolle',
    exportedLines: 'Exportierte {count}-Zeilen von {target}.',
    failedToExportLogs: 'Nicht exportiert Protokolle: {message}',
    failedToExportLogsFallback: 'Nicht exportieren von Protokollen.',
    editOnlyImported: 'Edit ist nur für importierte Logdateien verfügbar.',
    failedToOpenLogFile: 'Fehler beim Öffnen der Protokolldatei: {message}',
    failedToOpenLogFileFallback: 'Nicht geöffnet.',
    refreshOnlyImported: 'Refresh ist nur für importierte Log-Dateien verfügbar.',
    failedToReadLogFile: 'Fehler beim Lesen der Protokolldatei: {message}',
    failedToReadLogFileFallback: 'Fehler beim Lesen der Protokolldatei.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: 'Die Sitzung ist geschlossen.',
    disconnected: 'Entkoppelt.',
    reconnecting: 'Wiederanschließen...',
    failedToReconnect: 'Versäumt, sich wieder anzuschließen.',
    autoSaveDialogTitle: 'Wählen Sie Log-Datei zum automatischen Speichern von SSH-Ausgang',
    allFiles: 'Alle Dateien',
    autoSaveCancelled: 'Autospeicher storniert.',
    autoSaveFailed: 'Auto-Save versagt: {message}',
    autoSaveFailedFallback: 'Auto-Save versagt.',
    hostKeyVerificationFailed:
      'Host-Schlüsselverifikation fehlgeschlagen für {target}. Erwartete {expected}, erhielt jedoch {received}. Aktualisieren Sie den Fingerabdruck in Einstellungen, um wieder zu verbinden.',
    sshSessionClosedOn: '--- SSH Sitzung geschlossen {timestamp}',
  },
};
