export const en = {
  languageId: 'en',
  htmlLang: 'en',
  languageNames: {
    vscode: 'VSCode default',
    en: 'English',
    es: 'Spanish',
    it: 'Italian',
    'zh-cn': 'Simplified Chinese',
    'zh-tw': 'Traditional Chinese',
    fr: 'French',
    de: 'German',
    ja: 'Japanese',
    ko: 'Korean',
    ru: 'Russian',
    'pt-br': 'Portuguese (Brazil)',
    tr: 'Turkish',
    pl: 'Polish',
    cs: 'Czech',
    hu: 'Hungarian',
  },
  common: {
    add: 'Add',
    cancel: 'Cancel',
    close: 'Close',
    command: 'Command',
    copy: 'Copy',
    default: 'Default',
    disabled: 'Disabled',
    enabled: 'Enabled',
    exportSettings: 'Export Settings',
    importSettings: 'Import Settings',
    name: 'Name',
    none: 'None',
    remove: 'Remove',
    save: 'Save',
    select: 'Select',
  },
  deviceManager: {
    title: 'Embedded Device Logger v{version}',
    panelTitle: 'Embedded Devices Manager',
    intro: 'Manage devices and default configuration.',
    removeStoredPasswords: 'Remove Stored Passwords',
    editJson: 'Edit in JSON',
    viewConfigurationExample: 'View configuration example',
    saveChanges: 'Save changes',
    defaults: 'Defaults',
    defaultsDescription:
      'Default values for all devices. Each device can change it in devices table if desired.',
    enableSshTerminal: 'Enable SSH terminal',
    enableSftpExplorer: 'Enable SFTP explorer',
    enableExternalWebBrowser: 'Enable external web browser',
    enableEmbeddedWebBrowser: 'Enable embedded web browser',
    enableDevicePing: 'Enable device ping',
    showBastionOptions: 'Show Bastion options',
    language: 'Extension language',
    port: 'Port',
    logCommand: 'Log command',
    maxLinesPerTab: 'Max lines per tab',
    pingIntervalSeconds: 'Ping interval (seconds)',
    pingIntervalPlaceholder: 'Leave blank for manual ping only',
    sshCommands: 'SSH commands',
    groups: 'Groups',
    groupsDescription: 'Define optional groups to organize devices in the Embedded Devices view.',
    addGroup: 'Add group',
    devices: 'Devices',
    devicesDescription: 'Add or remove rows, then edit fields inline.',
    addDevice: 'Add device',
    moveSelectedDevicesUp: 'Move selected devices up in the list',
    moveSelectedDevicesDown: 'Move selected devices down in the list',
    resetPassword: 'Reset password',
    removeStoredPasswordsForSelectedDevices:
      'Remove stored passwords and passphrases for selected devices',
    columnId: 'ID',
    columnGroup: 'Group',
    columnColor: 'Color',
    columnHost: 'Host',
    columnUser: 'User',
    columnHostFingerprint: 'Host fingerprint',
    columnSecondaryHost: 'Secondary host',
    columnSecondaryFingerprint: 'Secondary fingerprint',
    columnSshTerminal: 'SSH terminal',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'SFTP presets (remote)',
    columnSftpPresetsLocal: 'SFTP presets (local)',
    columnExternalWebBrowser: 'External Web Browser',
    columnEmbeddedWebBrowser: 'Embedded Web Browser',
    columnWebUrl: 'Web URL',
    columnPrivateKeyPath: 'Private key path',
    columnPrivateKeyPassphrase: 'Private key passphrase',
    columnPasswordWriteOnly: 'Password (write only)',
    columnShowDefaultSshCommands: 'Show default SSH commands',
    columnBastionHost: 'Bastion host',
    columnBastionPort: 'Bastion port',
    columnBastionUser: 'Bastion user',
    columnBastionFingerprint: 'Bastion fingerprint',
    columnBastionKeyPath: 'Bastion key path',
    columnBastionKeyPassphrase: 'Bastion key passphrase',
    columnBastionPasswordWriteOnly: 'Bastion password (write only)',
    groupNamePlaceholder: 'Group name',
    editScript: 'Edit script',
    editScriptFor: 'Edit script for {name}',
    sshCommandFallback: 'SSH command',
    scriptDescription: 'Write the script that will be copied to /tmp and executed.',
    sshCommandScriptEditor: 'SSH command script editor',
    commandNamesEmojiHelp: 'Command names support emojis from https://emojidb.org/',
    openSshPanel: 'Open SSH Panel',
    rerunOnReconnection: 'Re-run on reconnection',
    copyAndRunScript: 'Copy and Run Script',
    addCommand: 'Add command',
    openCommandInSshPanel: 'Open this command in an SSH panel',
    openNamedCommandInSshPanel: 'Open {name} in SSH panel',
    rerunCommandAfterReconnect: 'Re-run this command after the SSH panel reconnects',
    rerunNamedCommandOnReconnect: 'Re-run {name} on reconnection',
    copyScriptToTmp: 'Copy a script to /tmp and run it after the command',
    copyAndRunScriptFor: 'Copy and run script for {name}',
    removeCommand: 'Remove command',
    dragToResize: 'Drag to resize',
    selectDeviceRow: 'Select device row',
    removedSelectedDevice: 'Removed selected device.',
    removedSelectedDevices: 'Removed {count} selected devices.',
    saving: 'Saving...',
    openingSettingsJson: 'Opening settings.json...',
    removingStoredPasswords: 'Removing stored passwords...',
    exportingSettings: 'Exporting settings...',
    importingSettings: 'Importing settings...',
    setSelectedDeviceIdBeforeReset:
      'Set at least one selected device ID before resetting stored password.',
    removingStoredPasswordForDevice: 'Removing stored password for {id}...',
    removingStoredPasswordsForDevices: 'Removing stored passwords for {count} selected devices...',
    configurationExample: 'Configuration example',
    configurationExampleDescription: 'Copy and paste these defaults into your settings.json.',
    copiedConfigurationExample: 'Copied configuration example.',
    failedToCopyConfigurationExample: 'Failed to copy configuration example.',
    savedSettings: 'Saved settings.',
    failedToSaveSettings: 'Failed to save settings.',
    importedSettingsApply: 'Imported settings. Review them and click Save changes to apply them.',
    failedToImportSettings: 'Failed to import settings.',
    exportSettingsSaveLabel: 'Export settings',
    exportCanceled: 'Export canceled.',
    exportedSettingsTo: 'Exported settings to {path}.',
    failedToExportSettings: 'Failed to export settings: {message}',
    importSettingsOpenLabel: 'Import settings',
    importCanceled: 'Import canceled.',
    importedSettingsFrom:
      'Imported settings from {path}. Review and click Save changes to apply them.',
    failedToImportSettingsWithMessage: 'Failed to import settings: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      'Saved settings. Reload the window or extension host, then save again to persist the Embedded Web Browser default.',
    reloadToPersistNewDefaultSettings:
      'Saved settings. Reload the window or extension host, then save again to persist newly added default settings.',
  },
  sidebar: {
    title: 'Embedded Logger Devices',
    copyUrl: 'Copy URL',
    copyName: 'Copy Name',
    pingInProgress: 'Ping in progress',
    pingReachable: 'Ping reachable',
    pingUnreachable: 'Ping unreachable',
    openLogs: 'Open Logs',
    openLogsFor: 'Open logs for {name}',
    openSshTerminal: 'Open SSH Terminal',
    openSshTerminalFor: 'Open an SSH terminal session for {name}',
    openSftpExplorer: 'Open SFTP Explorer',
    browseAndTransferFilesFor: 'Browse and transfer files for {name}',
    openExternalWebBrowser: 'Open External Web Browser',
    openExternalWebBrowserFor: 'Open the configured web URL for {name} in an external browser',
    openEmbeddedWebBrowser: 'Open Embedded Web Browser',
    openEmbeddedWebBrowserFor: 'Open the configured web URL for {name} in VS Code',
    copyScriptCommandTitle: 'Copy script to /tmp, chmod 777, and run it',
    noDevicesConfigured: 'No devices configured. Update "embeddedLogger.devices" in settings.',
    deviceNameLabel: 'Device name',
    deviceUrlLabel: 'Device URL',
    copiedToClipboard: '{label} copied to clipboard.',
  },
  deviceTree: {
    noDevicesConfigured: 'No devices configured. Update "embeddedLogger.devices" in settings.',
    openSettingsToConfigure: 'Open settings to configure embedded devices.',
    openSettings: 'Open Settings',
    openDeviceLogs: 'Open Device Logs',
    groupTooltip: '{name} group',
  },
  logPanel: {
    logsTitle: '{name} Logs',
    minLevel: 'Min Level',
    textFilter: 'Text Filter',
    filterSubstring: 'Filter substring',
    filteringPresets: 'Filtering Presets',
    filterPresets: 'Filter presets',
    savePreset: 'Save preset',
    deletePreset: 'Delete preset',
    exportLogs: 'Export logs',
    editLogFile: 'Edit log file',
    refreshLogFile: 'Refresh log file',
    startAutoSave: 'Start auto-save',
    stopAutoSave: 'Stop auto-save',
    clearLogs: 'Clear logs',
    highlight: 'Highlight',
    wordWrap: 'Word wrap',
    autoScroll: 'Auto-scroll',
    autoReconnect: 'Auto-reconnect',
    toggleState: '{label} ({state})',
    toggleOn: 'on',
    toggleOff: 'off',
    find: 'Find',
    findInLogs: 'Find in logs (Ctrl/Cmd+F)',
    clearSearch: 'Clear search',
    previousMatch: 'Previous match',
    nextMatch: 'Next match',
    prev: 'Prev',
    next: 'Next',
    reconnect: 'Reconnect',
    disconnect: 'Disconnect',
    highlights: 'Highlights',
    addHighlight: 'add',
    removeAllHighlights: 'remove all',
    highlightKeywords: 'Highlight keywords',
    lineLimitLive:
      'Configured display line limit reached. Older lines are being replaced with newer entries.',
    lineLimitOffline:
      'Configured display line limit reached. Older imported lines were hidden from this view.',
    upToTenHighlights: 'You can highlight up to 10 keys.',
    keyToHighlight: 'Key to highlight',
    removeHighlight: 'Remove highlight',
    noPreset: '(no preset)',
    filterPresetNamed: 'Filter preset: {name}',
    connectedStreaming: 'Connected. Streaming logs...',
    bookmarkLabel: 'Bookmark label',
    enterBookmarkLabel: 'Enter bookmark label',
    addBookmark: 'Add bookmark',
    editBookmarkLabel: 'Edit bookmark label',
    removeBookmark: 'Remove bookmark',
    removeAllBookmarks: 'Remove all bookmarks',
    goToNextBookmark: 'Go to next bookmark',
    goToPreviousBookmark: 'Go to previous bookmark',
    clearStatusMessage: 'Clear status message',
    connectionClosed: 'Connection closed.',
    retryingInSeconds: '{message} Retrying in {seconds} seconds...',
    reconnecting: 'Reconnecting...',
    disconnecting: 'Disconnecting...',
    hostKeyFailedDetails:
      'Host key verification failed. Expected {expected} but received {received}. Update the fingerprint to reconnect.',
    hostKeyFailed:
      'Host key verification failed. Update the stored fingerprint before reconnecting.',
    sessionClosed: 'Session closed.',
    sshSessionClosedOn: '--- SSH session closed on {timestamp}',
    dateAtTime: '{date} at {time}',
    autoSavingTo: 'Auto-saving to',
    autoSaveEnabled: 'Auto-save enabled.',
    autoSaveFailed: 'Auto-save failed.',
    waitingForPassword: 'Waiting for the user to enter the password…',
  },
  extension: {
    missingHost: 'Device "{name}" is missing a host.',
    missingUsername: 'Device "{name}" is missing a username.',
    invalidPort: 'Device "{name}" has an invalid port.',
    credentialsMigrationWarning:
      'Credentials were migrated to Secret Storage, but the "password" or "privateKeyPassphrase" fields could not be removed. Please delete them from embeddedLogger.devices in your settings.',
    sftpPresetsMigrationFailed:
      'Failed to migrate SFTP presets into embeddedLogger.devices. Existing presets remain in extension storage.',
    noHostFound: 'No host found for the selected device.',
    webUrlMustStart: 'Web browser URLs must start with http:// or https://.',
    invalidWebUrl: 'Invalid web URL for {name}: {message}',
    deviceNotFound: 'Device not found. Check embeddedLogger.devices.',
    workspaceTrustDeviceResources: 'Workspace trust is required before opening device resources.',
    workspaceTrustConnect: 'Workspace trust is required before connecting to devices.',
    embeddedBrowserUnavailable: 'VS Code embedded browser support is unavailable.',
    failedToOpenUri: 'Failed to open {uri}: {message}',
    sshCommandNoControlCharacters: 'SSH command must not contain control characters or new lines.',
    runningCommandOnDevice: 'Running "{command}" on {device}',
    commandFinishedOnDevice: 'Command "{command}" finished on {device}.',
    noDevicesConfigured: 'No devices configured. Check embeddedLogger.devices.',
    selectDeviceForSftp: 'Select a device to open the SFTP explorer',
    selectDeviceForExternalBrowser: 'Select a device to open in the external web browser',
    selectDeviceForEmbeddedBrowser: 'Select a device to open in the embedded web browser',
    storedPasswordsRemovedFor: 'Stored passwords and passphrases have been removed for {device}.',
    noDevicesToClearPasswords: 'No devices configured to clear passwords for.',
    storedPasswordsRemoved:
      'Stored passwords and passphrases have been removed for configured devices.',
    openLogFile: 'Open log file',
    failedToReadLogFile: 'Failed to read log file: {message}',
    localPanelSuffix: 'Local',
    noDeviceInfo: 'No device information supplied.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Cannot create a log session without a device.',
    loadedLines: 'Loaded {count} lines.',
    presetSaved: 'Preset "{name}" saved for {target}.',
    presetRemoved: 'Preset "{name}" removed for {target}.',
    exportLogsSaveLabel: 'Export logs',
    exportedLines: 'Exported {count} lines from {target}.',
    failedToExportLogs: 'Failed to export logs: {message}',
    failedToExportLogsFallback: 'Failed to export logs.',
    editOnlyImported: 'Edit is only available for imported log files.',
    failedToOpenLogFile: 'Failed to open log file: {message}',
    failedToOpenLogFileFallback: 'Failed to open log file.',
    refreshOnlyImported: 'Refresh is only available for imported log files.',
    failedToReadLogFile: 'Failed to read log file: {message}',
    failedToReadLogFileFallback: 'Failed to read log file.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: 'Session closed.',
    disconnected: 'Disconnected.',
    reconnecting: 'Reconnecting...',
    failedToReconnect: 'Failed to reconnect.',
    autoSaveDialogTitle: 'Select log file to auto-save SSH output',
    allFiles: 'All Files',
    autoSaveCancelled: 'Auto-save cancelled.',
    autoSaveFailed: 'Auto-save failed: {message}',
    autoSaveFailedFallback: 'Auto-save failed.',
    hostKeyVerificationFailed:
      'Host key verification failed for {target}. Expected {expected} but received {received}. Update the fingerprint in settings to reconnect.',
    sshSessionClosedOn: '--- SSH session closed on {timestamp}',
  },
};
