/* eslint-disable spellcheck/spell-checker */
import type { en } from './en';

export const es: typeof en = {
  languageId: 'es',
  htmlLang: 'es',
  languageNames: {
    vscode: 'Predeterminado de VSCode',
    en: 'Inglés',
    es: 'Español',
    it: 'Italiano',
    'zh-cn': 'Chino simplificado',
    'zh-tw': 'Chino tradicional',
    fr: 'Francés',
    de: 'Alemán',
    ja: 'Japonés',
    ko: 'Coreano',
    ru: 'Ruso',
    'pt-br': 'Portugués (Brasil)',
    tr: 'Turco',
    pl: 'Polaco',
    cs: 'Checo',
    hu: 'Húngaro',
  },
  common: {
    add: 'Agregar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    command: 'Comando',
    copy: 'Copiar',
    default: 'Predeterminado',
    disabled: 'Deshabilitado',
    enabled: 'Habilitado',
    exportSettings: 'Exportar ajustes',
    importSettings: 'Importar ajustes',
    name: 'Nombre',
    none: 'Ninguno',
    remove: 'Quitar',
    save: 'Guardar',
    select: 'Seleccionar',
  },
  deviceManager: {
    title: 'Embedded Device Logger v{version}',
    panelTitle: 'Administrador de dispositivos embebidos',
    intro: 'Administra dispositivos y la configuracion predeterminada.',
    removeStoredPasswords: 'Quitar contrasenas guardadas',
    editJson: 'Editar en JSON',
    viewConfigurationExample: 'Ver ejemplo de configuracion',
    saveChanges: 'Guardar cambios',
    defaults: 'Valores predeterminados',
    defaultsDescription:
      'Valores predeterminados para todos los dispositivos. Cada dispositivo puede cambiarlos en la tabla si lo necesita.',
    enableSshTerminal: 'Habilitar terminal SSH',
    enableSftpExplorer: 'Habilitar explorador SFTP',
    enableExternalWebBrowser: 'Habilitar navegador web externo',
    enableEmbeddedWebBrowser: 'Habilitar navegador web embebido',
    enableDevicePing: 'Habilitar ping de dispositivos',
    language: 'Idioma de la extension',
    port: 'Puerto',
    logCommand: 'Comando de logs',
    maxLinesPerTab: 'Lineas maximas por pestana',
    pingIntervalSeconds: 'Intervalo de ping (segundos)',
    pingIntervalPlaceholder: 'Dejar en blanco para ping manual',
    sshCommands: 'Comandos SSH',
    groups: 'Grupos',
    groupsDescription: 'Define grupos opcionales para organizar dispositivos en la vista.',
    addGroup: 'Agregar grupo',
    devices: 'Dispositivos',
    devicesDescription: 'Agrega o quita filas y luego edita los campos en linea.',
    addDevice: 'Agregar dispositivo',
    moveSelectedDevicesUp: 'Mover los dispositivos seleccionados hacia arriba',
    moveSelectedDevicesDown: 'Mover los dispositivos seleccionados hacia abajo',
    resetPassword: 'Restablecer contrasena',
    removeStoredPasswordsForSelectedDevices:
      'Quitar contrasenas y frases de clave guardadas para los dispositivos seleccionados',
    columnId: 'ID',
    columnGroup: 'Grupo',
    columnColor: 'Color',
    columnHost: 'Host',
    columnUser: 'Usuario',
    columnHostFingerprint: 'Huella del host',
    columnSecondaryHost: 'Host secundario',
    columnSecondaryFingerprint: 'Huella secundaria',
    columnSshTerminal: 'Terminal SSH',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'Presets SFTP (remoto)',
    columnSftpPresetsLocal: 'Presets SFTP (local)',
    columnExternalWebBrowser: 'Navegador web externo',
    columnEmbeddedWebBrowser: 'Navegador web embebido',
    columnWebUrl: 'URL web',
    columnPrivateKeyPath: 'Ruta de clave privada',
    columnPrivateKeyPassphrase: 'Frase de clave privada',
    columnPasswordWriteOnly: 'Contrasena (solo escritura)',
    columnShowDefaultSshCommands: 'Mostrar comandos SSH pred.',
    columnBastionHost: 'Host bastion',
    columnBastionPort: 'Puerto bastion',
    columnBastionUser: 'Usuario bastion',
    columnBastionFingerprint: 'Huella bastion',
    columnBastionKeyPath: 'Ruta de clave bastion',
    columnBastionKeyPassphrase: 'Frase de clave bastion',
    columnBastionPasswordWriteOnly: 'Contrasena bastion (solo escritura)',
    groupNamePlaceholder: 'Nombre del grupo',
    editScript: 'Editar script',
    editScriptFor: 'Editar script para {name}',
    sshCommandFallback: 'comando SSH',
    scriptDescription: 'Escribe el script que se copiara a /tmp y se ejecutara.',
    sshCommandScriptEditor: 'Editor de script de comando SSH',
    commandNamesEmojiHelp: 'Los nombres de comandos admiten emojis desde https://emojidb.org/',
    openSshPanel: 'Abrir panel SSH',
    rerunOnReconnection: 'Reejecutar al reconectar',
    copyAndRunScript: 'Copiar y ejecutar script',
    addCommand: 'Agregar comando',
    openCommandInSshPanel: 'Abrir este comando en un panel SSH',
    openNamedCommandInSshPanel: 'Abrir {name} en un panel SSH',
    rerunCommandAfterReconnect: 'Reejecutar este comando despues de reconectar el panel SSH',
    rerunNamedCommandOnReconnect: 'Reejecutar {name} al reconectar',
    copyScriptToTmp: 'Copiar un script a /tmp y ejecutarlo despues del comando',
    copyAndRunScriptFor: 'Copiar y ejecutar script para {name}',
    removeCommand: 'Quitar comando',
    dragToResize: 'Arrastrar para cambiar el tamano',
    selectDeviceRow: 'Seleccionar fila del dispositivo',
    removedSelectedDevice: 'Dispositivo seleccionado quitado.',
    removedSelectedDevices: 'Se quitaron {count} dispositivos seleccionados.',
    saving: 'Guardando...',
    openingSettingsJson: 'Abriendo settings.json...',
    removingStoredPasswords: 'Quitando contrasenas guardadas...',
    exportingSettings: 'Exportando ajustes...',
    importingSettings: 'Importando ajustes...',
    setSelectedDeviceIdBeforeReset:
      'Define el ID de al menos un dispositivo seleccionado antes de restablecer la contrasena guardada.',
    removingStoredPasswordForDevice: 'Quitando contrasena guardada para {id}...',
    removingStoredPasswordsForDevices:
      'Quitando contrasenas guardadas para {count} dispositivos seleccionados...',
    configurationExample: 'Ejemplo de configuracion',
    configurationExampleDescription: 'Copia y pega estos valores en tu settings.json.',
    copiedConfigurationExample: 'Ejemplo de configuracion copiado.',
    failedToCopyConfigurationExample: 'No se pudo copiar el ejemplo de configuracion.',
    savedSettings: 'Ajustes guardados.',
    failedToSaveSettings: 'No se pudieron guardar los ajustes.',
    importedSettingsApply: 'Ajustes importados. Revisalos y haz clic en Guardar cambios.',
    failedToImportSettings: 'No se pudieron importar los ajustes.',
    exportSettingsSaveLabel: 'Exportar ajustes',
    exportCanceled: 'Exportacion cancelada.',
    exportedSettingsTo: 'Ajustes exportados a {path}.',
    failedToExportSettings: 'No se pudieron exportar los ajustes: {message}',
    importSettingsOpenLabel: 'Importar ajustes',
    importCanceled: 'Importacion cancelada.',
    importedSettingsFrom:
      'Ajustes importados desde {path}. Revisalos y haz clic en Guardar cambios para aplicarlos.',
    failedToImportSettingsWithMessage: 'No se pudieron importar los ajustes: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      'Ajustes guardados. Recarga la ventana o el host de la extension y vuelve a guardar para persistir el navegador web embebido predeterminado.',
  },
  sidebar: {
    title: 'Dispositivos de Embedded Logger',
    copyUrl: 'Copiar URL',
    copyName: 'Copiar nombre',
    pingInProgress: 'Ping en curso',
    pingReachable: 'Ping accesible',
    pingUnreachable: 'Ping inaccesible',
    openLogs: 'Abrir logs',
    openLogsFor: 'Abrir logs de {name}',
    openSshTerminal: 'Abrir terminal SSH',
    openSshTerminalFor: 'Abrir una sesion de terminal SSH para {name}',
    openSftpExplorer: 'Abrir explorador SFTP',
    browseAndTransferFilesFor: 'Explorar y transferir archivos para {name}',
    openExternalWebBrowser: 'Abrir navegador web externo',
    openExternalWebBrowserFor: 'Abrir la URL web configurada para {name} en un navegador externo',
    openEmbeddedWebBrowser: 'Abrir navegador web embebido',
    openEmbeddedWebBrowserFor: 'Abrir la URL web configurada para {name} en VS Code',
    copyScriptCommandTitle: 'Copiar script a /tmp, chmod 777 y ejecutarlo',
    noDevicesConfigured: 'No hay dispositivos configurados. Actualiza "embeddedLogger.devices".',
    deviceNameLabel: 'Nombre del dispositivo',
    deviceUrlLabel: 'URL del dispositivo',
    copiedToClipboard: '{label} copiado al portapapeles.',
  },
  deviceTree: {
    noDevicesConfigured: 'No hay dispositivos configurados. Actualiza "embeddedLogger.devices".',
    openSettingsToConfigure: 'Abrir ajustes para configurar dispositivos embebidos.',
    openSettings: 'Abrir ajustes',
    openDeviceLogs: 'Abrir logs del dispositivo',
    groupTooltip: 'Grupo {name}',
  },
  logPanel: {
    logsTitle: 'Logs de {name}',
    minLevel: 'Nivel minimo',
    textFilter: 'Filtro de texto',
    filterSubstring: 'Filtrar subcadena',
    filteringPresets: 'Presets de filtrado',
    filterPresets: 'Presets de filtro',
    savePreset: 'Guardar preset',
    deletePreset: 'Eliminar preset',
    exportLogs: 'Exportar logs',
    editLogFile: 'Editar archivo de log',
    refreshLogFile: 'Actualizar archivo de log',
    startAutoSave: 'Iniciar autoguardado',
    stopAutoSave: 'Detener autoguardado',
    clearLogs: 'Limpiar logs',
    highlight: 'Resaltar',
    wordWrap: 'Ajuste de linea',
    autoScroll: 'Desplazamiento automatico',
    autoReconnect: 'Reconexion automatica',
    toggleState: '{label} ({state})',
    toggleOn: 'activado',
    toggleOff: 'desactivado',
    find: 'Buscar',
    findInLogs: 'Buscar en logs (Ctrl/Cmd+F)',
    clearSearch: 'Limpiar busqueda',
    previousMatch: 'Coincidencia anterior',
    nextMatch: 'Coincidencia siguiente',
    prev: 'Ant.',
    next: 'Sig.',
    reconnect: 'Reconectar',
    disconnect: 'Desconectar',
    highlights: 'Resaltados',
    addHighlight: 'agregar',
    removeAllHighlights: 'quitar todo',
    highlightKeywords: 'Palabras resaltadas',
    lineLimitLive:
      'Se alcanzo el limite configurado de lineas visibles. Las lineas antiguas se reemplazan por nuevas entradas.',
    lineLimitOffline:
      'Se alcanzo el limite configurado de lineas visibles. Las lineas importadas antiguas se ocultaron en esta vista.',
    upToTenHighlights: 'Puedes resaltar hasta 10 claves.',
    keyToHighlight: 'Clave a resaltar',
    removeHighlight: 'Quitar resaltado',
    noPreset: '(sin preset)',
    filterPresetNamed: 'Preset de filtro: {name}',
    connectedStreaming: 'Conectado. Transmitiendo logs...',
    bookmarkLabel: 'Etiqueta del marcador',
    enterBookmarkLabel: 'Ingresar etiqueta del marcador',
    addBookmark: 'Agregar marcador',
    editBookmarkLabel: 'Editar etiqueta del marcador',
    removeBookmark: 'Quitar marcador',
    removeAllBookmarks: 'Quitar todos los marcadores',
    goToNextBookmark: 'Ir al marcador siguiente',
    goToPreviousBookmark: 'Ir al marcador anterior',
    clearStatusMessage: 'Limpiar mensaje de estado',
    connectionClosed: 'Conexion cerrada.',
    retryingInSeconds: '{message} Reintentando en {seconds} segundos...',
    reconnecting: 'Reconectando...',
    disconnecting: 'Desconectando...',
    hostKeyFailedDetails:
      'Fallo la verificacion de la clave del host. Se esperaba {expected}, pero se recibio {received}. Actualiza la huella para reconectar.',
    hostKeyFailed:
      'Fallo la verificacion de la clave del host. Actualiza la huella guardada antes de reconectar.',
    sessionClosed: 'Sesion cerrada.',
    sshSessionClosedOn: '--- Sesion SSH cerrada el {timestamp}',
    dateAtTime: '{date} a las {time}',
    autoSavingTo: 'Autoguardando en',
    autoSaveEnabled: 'Autoguardado habilitado.',
    autoSaveFailed: 'Fallo el autoguardado.',
    waitingForPassword: 'Esperando a que el usuario ingrese la contrasena…',
  },
  extension: {
    missingHost: 'Al dispositivo "{name}" le falta un host.',
    missingUsername: 'Al dispositivo "{name}" le falta un usuario.',
    invalidPort: 'El dispositivo "{name}" tiene un puerto no valido.',
    credentialsMigrationWarning:
      'Las credenciales se migraron a Secret Storage, pero los campos "password" o "privateKeyPassphrase" no se pudieron quitar. Eliminalos de embeddedLogger.devices en tus ajustes.',
    sftpPresetsMigrationFailed:
      'No se pudieron migrar los presets SFTP a embeddedLogger.devices. Los presets existentes permanecen en el almacenamiento de la extension.',
    noHostFound: 'No se encontro un host para el dispositivo seleccionado.',
    webUrlMustStart: 'Las URL web deben comenzar con http:// o https://.',
    invalidWebUrl: 'URL web no valida para {name}: {message}',
    deviceNotFound: 'Dispositivo no encontrado. Revisa embeddedLogger.devices.',
    workspaceTrustDeviceResources:
      'Se requiere confianza del espacio de trabajo antes de abrir recursos del dispositivo.',
    workspaceTrustConnect:
      'Se requiere confianza del espacio de trabajo antes de conectar con dispositivos.',
    embeddedBrowserUnavailable: 'El soporte de navegador embebido de VS Code no esta disponible.',
    failedToOpenUri: 'No se pudo abrir {uri}: {message}',
    sshCommandNoControlCharacters:
      'El comando SSH no debe contener caracteres de control ni saltos de linea.',
    runningCommandOnDevice: 'Ejecutando "{command}" en {device}',
    commandFinishedOnDevice: 'El comando "{command}" finalizo en {device}.',
    noDevicesConfigured: 'No hay dispositivos configurados. Revisa embeddedLogger.devices.',
    selectDeviceForSftp: 'Selecciona un dispositivo para abrir el explorador SFTP',
    selectDeviceForExternalBrowser:
      'Selecciona un dispositivo para abrirlo en el navegador externo',
    selectDeviceForEmbeddedBrowser:
      'Selecciona un dispositivo para abrirlo en el navegador embebido',
    storedPasswordsRemovedFor:
      'Se quitaron las contrasenas y frases de clave guardadas para {device}.',
    noDevicesToClearPasswords: 'No hay dispositivos configurados para limpiar contrasenas.',
    storedPasswordsRemoved:
      'Se quitaron las contrasenas y frases de clave guardadas para los dispositivos configurados.',
    openLogFile: 'Abrir archivo de log',
    failedToReadLogFile: 'No se pudo leer el archivo de log: {message}',
    localPanelSuffix: 'Local',
    noDeviceInfo: 'No se proporciono informacion del dispositivo.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'No se puede crear una sesion de logs sin un dispositivo.',
    loadedLines: 'Se cargaron {count} lineas.',
    presetSaved: 'Preset "{name}" guardado para {target}.',
    presetRemoved: 'Preset "{name}" quitado para {target}.',
    exportLogsSaveLabel: 'Exportar logs',
    exportedLines: 'Se exportaron {count} lineas desde {target}.',
    failedToExportLogs: 'No se pudieron exportar los logs: {message}',
    failedToExportLogsFallback: 'No se pudieron exportar los logs.',
    editOnlyImported: 'Editar solo esta disponible para archivos de log importados.',
    failedToOpenLogFile: 'No se pudo abrir el archivo de log: {message}',
    failedToOpenLogFileFallback: 'No se pudo abrir el archivo de log.',
    refreshOnlyImported: 'Actualizar solo esta disponible para archivos de log importados.',
    failedToReadLogFile: 'No se pudo leer el archivo de log: {message}',
    failedToReadLogFileFallback: 'No se pudo leer el archivo de log.',
    reloadedLinesFrom: 'Se recargaron {count} lineas desde {file}.',
    sessionClosed: 'Sesion cerrada.',
    disconnected: 'Desconectado.',
    reconnecting: 'Reconectando...',
    failedToReconnect: 'No se pudo reconectar.',
    autoSaveDialogTitle: 'Seleccionar archivo de log para autoguardar la salida SSH',
    allFiles: 'Todos los archivos',
    autoSaveCancelled: 'Autoguardado cancelado.',
    autoSaveFailed: 'Fallo el autoguardado: {message}',
    autoSaveFailedFallback: 'Fallo el autoguardado.',
    hostKeyVerificationFailed:
      'Fallo la verificacion de la clave del host para {target}. Se esperaba {expected}, pero se recibio {received}. Actualiza la huella en los ajustes para reconectar.',
    sshSessionClosedOn: '--- Sesion SSH cerrada el {timestamp}',
  },
};
