/* eslint-disable spellcheck/spell-checker */
import type { en } from './en';

export const fr: typeof en = {
  languageId: 'fr',
  htmlLang: 'fr',
  languageNames: {
    vscode: 'Par défaut de VSCode',
    en: 'Anglais',
    es: 'Espagnol',
    it: 'Italien',
    'zh-cn': 'Chinois simplifié',
    'zh-tw': 'Chinois traditionnel',
    fr: 'Français',
    de: 'Allemand',
    ja: 'Japonais',
    ko: 'Coréen',
    ru: 'Russe',
    'pt-br': 'Portugais (Brésil)',
    tr: 'Turc',
    pl: 'Polonais',
    cs: 'Tchèque',
    hu: 'Hongrois',
  },
  common: {
    add: 'Ajouter',
    cancel: 'Annuler',
    close: 'Fermer',
    command: 'Commande',
    copy: 'Copier',
    default: 'Par défaut',
    disabled: 'Désactivé',
    enabled: 'Activé',
    exportSettings: 'Exporter les paramètres',
    importSettings: 'Importer les paramètres',
    name: 'Nom',
    none: 'Aucun',
    remove: 'Supprimer',
    save: 'Enregistrer',
    select: 'Sélectionner',
  },
  deviceManager: {
    title: 'Enregistreur de périphérique intégré v{version}',
    panelTitle: 'Gestionnaire des appareils embarqués',
    intro: 'Gérez les appareils et la configuration par défaut.',
    removeStoredPasswords: 'Supprimer les mots de passe stockés',
    editJson: 'Modifier dans JSON',
    viewConfigurationExample: "Affichage de l'exemple de configuration",
    saveChanges: 'Enregistrer les modifications',
    defaults: 'Par défaut',
    defaultsDescription:
      'Valeurs par défaut pour tous les appareils. Chaque appareil peut le modifier dans la table des appareils si désiré.',
    enableSshTerminal: 'Activer le terminal SSH',
    enableSftpExplorer: "Activer l'explorateur SFTP",
    enableExternalWebBrowser: 'Activer le navigateur Web externe',
    enableEmbeddedWebBrowser: 'Activer le navigateur Web intégré',
    enableDevicePing: 'Activer le ping du périphérique',
    showBastionOptions: 'Afficher les options de bastion',
    language: "Langue de l'extension",
    port: 'Port',
    logCommand: 'Commande de journal',
    maxLinesPerTab: 'Max lignes par onglet',
    pingIntervalSeconds: 'Intervalle de ping (secondes)',
    pingIntervalPlaceholder: 'Laisser en blanc pour ping manuel seulement',
    sshCommands: 'Commandes SSH',
    groups: 'Groupes',
    groupsDescription:
      'Définir des groupes optionnels pour organiser les appareils dans la vue des appareils embarqués.',
    addGroup: 'Ajouter un groupe',
    devices: 'Dispositifs',
    devicesDescription: 'Ajouter ou supprimer des lignes, puis modifier les champs en ligne.',
    addDevice: 'Ajouter un périphérique',
    moveSelectedDevicesUp: 'Déplacer les appareils sélectionnés vers le haut dans la liste',
    moveSelectedDevicesDown: 'Déplacer les appareils sélectionnés vers le bas dans la liste',
    resetPassword: 'Réinitialiser le mot de passe',
    removeStoredPasswordsForSelectedDevices:
      'Supprimer les mots de passe et les mots de passe stockés pour certains appareils',
    columnId: 'ID',
    columnGroup: 'Groupe',
    columnColor: 'Couleur',
    columnHost: 'Hébergement',
    columnUser: 'Utilisateur',
    columnHostFingerprint: "Empreinte de l'hôte",
    columnSecondaryHost: 'Hôte secondaire',
    columnSecondaryFingerprint: 'Empreinte secondaire',
    columnSshTerminal: 'Terminal SSH',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'Préréglages SFTP (à distance)',
    columnSftpPresetsLocal: 'Préréglages SFTP (local)',
    columnExternalWebBrowser: 'Navigateur Web externe',
    columnEmbeddedWebBrowser: 'Navigateur Web intégré',
    columnWebUrl: 'Web URL',
    columnPrivateKeyPath: 'Chemin de la clé privée',
    columnPrivateKeyPassphrase: 'Clé privée',
    columnPasswordWriteOnly: 'Mot de passe (écrire seulement)',
    columnShowDefaultSshCommands: 'Afficher les commandes SSH par défaut',
    columnBastionHost: 'Hôte de bastion',
    columnBastionPort: 'Port de bastion',
    columnBastionUser: 'Utilisateur du bastion',
    columnBastionFingerprint: 'Empreinte de bastion',
    columnBastionKeyPath: 'Chemin de la clé de bastion',
    columnBastionKeyPassphrase: 'Mots de passe clés de bastion',
    columnBastionPasswordWriteOnly: 'Mot de passe Bastion (écriture seulement)',
    groupNamePlaceholder: 'Nom du groupe',
    editScript: 'Éditer le script',
    editScriptFor: 'Modifier le script pour {name}',
    sshCommandFallback: 'Commande SSH',
    scriptDescription: 'Écrivez le script qui sera copié à /tmp et exécuté.',
    sshCommandScriptEditor: 'Éditeur de script de commande SSH',
    commandNamesEmojiHelp: 'Les noms de commandes supportent les émojis de https://emojidb.org/',
    openSshPanel: 'Ouvrir SSH Groupe',
    rerunOnReconnection: 'Ré-exécution lors de la reconnexion',
    copyAndRunScript: 'Copier et exécuter le script',
    addCommand: 'Ajouter une commande',
    openCommandInSshPanel: 'Ouvrez cette commande dans un panneau SSH',
    openNamedCommandInSshPanel: 'Ouvrir {name} dans le panneau SSH',
    rerunCommandAfterReconnect: 'Relancer cette commande après que le panneau SSH se reconnecte',
    rerunNamedCommandOnReconnect: 'Relancez {name} lors de la reconnexion',
    copyScriptToTmp: "Copier un script vers /tmp et l'exécuter après la commande",
    copyAndRunScriptFor: 'Copier et exécuter le script pour {name}',
    removeCommand: 'Supprimer la commande',
    dragToResize: 'Faites glisser pour redimensionner',
    selectDeviceRow: 'Sélectionner la ligne du périphérique',
    removedSelectedDevice: 'Supprimé le périphérique sélectionné.',
    removedSelectedDevices: 'Supprimé les périphériques sélectionnés {count}.',
    saving: 'Sauver...',
    openingSettingsJson: 'Ouverture de settings.json...',
    removingStoredPasswords: 'Suppression des mots de passe stockés...',
    exportingSettings: 'Exporter les paramètres...',
    importingSettings: 'Importation des paramètres...',
    setSelectedDeviceIdBeforeReset:
      'Définir au moins un périphérique sélectionné ID avant de réinitialiser le mot de passe stocké.',
    removingStoredPasswordForDevice: 'Suppression du mot de passe stocké pour {id}...',
    removingStoredPasswordsForDevices:
      'Suppression des mots de passe stockés pour les appareils sélectionnés {count}...',
    configurationExample: 'Exemple de configuration',
    configurationExampleDescription:
      'Copiez et collez ces valeurs par défaut dans votre settings.json.',
    copiedConfigurationExample: 'Exemple de configuration copié.',
    failedToCopyConfigurationExample: "Impossible de copier l'exemple de configuration.",
    savedSettings: 'Paramètres enregistrés.',
    failedToSaveSettings: "Impossible d'enregistrer les paramètres.",
    importedSettingsApply:
      'Paramètres importés. Consultez-les et cliquez sur Enregistrer les modifications pour les appliquer.',
    failedToImportSettings: "Impossible d'importer les paramètres.",
    exportSettingsSaveLabel: "Paramètres d'exportation",
    exportCanceled: 'Exportation annulée.',
    exportedSettingsTo: 'Paramètres exportés vers {path}.',
    failedToExportSettings: "Impossible d'exporter les paramètres : {message}",
    importSettingsOpenLabel: "Paramètres d'importation",
    importCanceled: 'Importation annulée.',
    importedSettingsFrom:
      'Paramètres importés de {path}. Consultez et cliquez sur Enregistrer les modifications pour les appliquer.',
    failedToImportSettingsWithMessage: "Impossible d'importer les paramètres : {message}",
    reloadToPersistEmbeddedBrowserDefault:
      "Paramètres enregistrés. Rechargez la fenêtre ou l'hôte d'extension, puis enregistrez à nouveau pour persister le navigateur Web embarqué par défaut.",
    reloadToPersistNewDefaultSettings:
      "Paramètres enregistrés. Rechargez la fenêtre ou l'hôte d'extension, puis enregistrez à nouveau pour conserver les nouveaux paramètres par défaut.",
  },
  sidebar: {
    title: 'Enregistreur intégré',
    copyUrl: 'Copier URL',
    copyName: 'Copier le nom',
    pingInProgress: 'Ping en cours',
    pingReachable: 'Ping accessible',
    pingUnreachable: 'Ping inaccessible',
    openLogs: 'Ouvrir des journaux',
    openLogsFor: 'Ouvrir des journaux pour {name}',
    openSshTerminal: 'Ouvrir SSH Terminal',
    openSshTerminalFor: 'Ouvrir une session de terminal SSH pour {name}',
    openSftpExplorer: 'Ouvrir SFTP Explorateur',
    browseAndTransferFilesFor: 'Parcourir et transférer des fichiers pour {name}',
    openExternalWebBrowser: 'Ouvrir le navigateur Web externe',
    openExternalWebBrowserFor: 'Ouvrir le web URL configuré pour {name} dans un navigateur externe',
    openEmbeddedWebBrowser: 'Ouvrir le navigateur Web intégré',
    openEmbeddedWebBrowserFor: 'Ouvrir le web URL configuré pour {name} dans VS Code',
    copyScriptCommandTitle: "Copier le script vers /tmp, chmod 777, et l'exécuter",
    noDevicesConfigured:
      'Aucun périphérique configuré. Mettre à jour "embeddedLogger.devices" dans les paramètres.',
    deviceNameLabel: 'Nom du périphérique',
    deviceUrlLabel: 'Appareil URL',
    copiedToClipboard: '{label} a été copié dans le presse-papiers.',
  },
  deviceTree: {
    noDevicesConfigured:
      'Aucun périphérique configuré. Mettre à jour "embeddedLogger.devices" dans les paramètres.',
    openSettingsToConfigure: 'Ouvrez les paramètres pour configurer les périphériques embarqués.',
    openSettings: 'Ouvrir les paramètres',
    openDeviceLogs: 'Ouvrir les journaux des périphériques',
    groupTooltip: 'Groupe {name}',
  },
  logPanel: {
    logsTitle: '{name} Registres',
    minLevel: 'Niveau minimum',
    textFilter: 'Filtre de texte',
    filterSubstring: 'Sous-chaîne de filtres',
    filteringPresets: 'Préréglage',
    filterPresets: 'Préréglage du filtre',
    savePreset: 'Enregistrer le préréglage',
    deletePreset: 'Supprimer le préréglage',
    exportLogs: "Registres d'exportation",
    editLogFile: 'Modifier le fichier journal',
    refreshLogFile: 'Rafraîchir le fichier journal',
    startAutoSave: "Démarrer l'enregistrement automatique",
    stopAutoSave: "Arrêtez d'enregistrer automatiquement",
    clearLogs: 'Effacer les journaux',
    highlight: 'Mettre en évidence',
    wordWrap: 'Enveloppe de mots',
    autoScroll: 'Roulement automatique',
    autoReconnect: 'Reconnecter automatiquement',
    toggleState: '{label} ({state})',
    toggleOn: 'le',
    toggleOff: 'départ',
    find: 'Rechercher',
    findInLogs: 'Trouver dans les journaux (Ctrl/Cmd+F)',
    clearSearch: 'Effacer la recherche',
    previousMatch: 'Match précédent',
    nextMatch: 'Prochain match',
    prev: 'Précédent',
    next: 'Suivant',
    reconnect: 'Reconnecter',
    disconnect: 'Déconnecter',
    highlights: 'Faits marquants',
    addHighlight: 'ajouter',
    removeAllHighlights: 'supprimer tout',
    highlightKeywords: 'Mettre en évidence les mots clés',
    lineLimitLive:
      "La limite de ligne d'affichage configurée a été atteinte. Les anciennes lignes sont remplacées par de nouvelles entrées.",
    lineLimitOffline:
      "La limite de ligne d'affichage configurée a été atteinte. Les anciennes lignes importées étaient cachées de cette vue.",
    upToTenHighlights: "Vous pouvez mettre en valeur jusqu'à 10 clés.",
    keyToHighlight: 'Clé à retenir',
    removeHighlight: 'Supprimer le point fort',
    noPreset: '(pas de préréglage)',
    filterPresetNamed: 'Préréglage du filtre : {name}',
    connectedStreaming: 'Connecté. En streaming...',
    bookmarkLabel: 'Étiquette des signets',
    enterBookmarkLabel: "Entrez l'étiquette du signet",
    addBookmark: 'Ajouter un signet',
    editBookmarkLabel: "Modifier l'étiquette du signet",
    removeBookmark: 'Supprimer le signet',
    removeAllBookmarks: 'Supprimer tous les signets',
    goToNextBookmark: 'Aller au signet suivant',
    goToPreviousBookmark: 'Aller au précédent signet',
    clearStatusMessage: "Effacer le message d'état",
    connectionClosed: 'Connexion fermée.',
    retryingInSeconds: '{message} Réessayer en {seconds} secondes...',
    reconnecting: 'Reconnecter...',
    disconnecting: 'Déconnecter...',
    hostKeyFailedDetails:
      "La vérification de la clé de l'hôte a échoué. {expected} attendu mais reçu {received}. Mettre à jour l'empreinte digitale pour se reconnecter.",
    hostKeyFailed:
      "La vérification de la clé de l'hôte a échoué. Mettre à jour les empreintes digitales stockées avant de se reconnecter.",
    sessionClosed: 'Séance close.',
    sshSessionClosedOn: '--- Session SSH close sur {timestamp}',
    dateAtTime: '{date} à {time}',
    autoSavingTo: 'Auto-économie vers',
    autoSaveEnabled: 'Enregistrer automatiquement activé.',
    autoSaveFailed: "L'enregistrement automatique a échoué.",
    waitingForPassword: "Attendre que l'utilisateur entre le mot de passe..",
  },
  extension: {
    missingHost: 'Le périphérique "{name}" manque un hôte.',
    missingUsername: 'Le périphérique "{name}" manque un nom d\'utilisateur.',
    invalidPort: 'Le périphérique "{name}" a un port invalide.',
    credentialsMigrationWarning:
      'Les lettres de créances ont été migrées vers Secret Storage, mais les champs "mot de passe" ou "privateKeyPassphrase" n\'ont pas pu être supprimés. Veuillez les supprimer de embeddedLogger.devices dans vos paramètres.',
    sftpPresetsMigrationFailed:
      "Impossible de migrer les préréglages SFTP vers embeddedLogger.devices. Les préréglages existants restent dans le stockage d'extension.",
    noHostFound: 'Aucun hôte trouvé pour le périphérique sélectionné.',
    webUrlMustStart: 'Les navigateurs Web URL doivent commencer par http:// ou https://.',
    invalidWebUrl: 'Web URL non valide pour {name}: {message}',
    deviceNotFound: 'Appareil introuvable. Vérifiez embeddedLogger.devices.',
    workspaceTrustDeviceResources:
      "La confiance dans l'espace de travail est requise avant d'ouvrir les ressources de l'appareil.",
    workspaceTrustConnect:
      "La confiance dans l'espace de travail est requise avant de se connecter aux appareils.",
    embeddedBrowserUnavailable:
      "La prise en charge du navigateur intégré VS Code n'est pas disponible.",
    failedToOpenUri: "Échec de l'ouverture {uri}: {message}",
    sshCommandNoControlCharacters:
      'La commande SSH ne doit pas contenir de caractères de contrôle ou de nouvelles lignes.',
    runningCommandOnDevice: 'Lancer "{command}" sur {device}',
    commandFinishedOnDevice: 'Commande "{command}" terminée sur {device}.',
    noDevicesConfigured: 'Aucun périphérique configuré. Vérifiez embeddedLogger.devices.',
    selectDeviceForSftp: "Sélectionnez un périphérique pour ouvrir l'explorateur SFTP",
    selectDeviceForExternalBrowser:
      'Sélectionnez un appareil à ouvrir dans le navigateur Web externe',
    selectDeviceForEmbeddedBrowser:
      'Sélectionnez un appareil à ouvrir dans le navigateur Web intégré',
    storedPasswordsRemovedFor:
      'Les mots de passe et les mots de passe stockés ont été supprimés pour {device}.',
    noDevicesToClearPasswords: 'Aucun périphérique configuré pour effacer les mots de passe.',
    storedPasswordsRemoved:
      'Les mots de passe et les mots de passe stockés ont été supprimés pour les appareils configurés.',
    openLogFile: 'Ouvrir le fichier journal',
    failedToReadLogFile: 'Impossible de lire le fichier journal : {message}',
    localPanelSuffix: 'Local',
    noDeviceInfo: "Aucune information fournie sur l'appareil.",
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Impossible de créer une session de journal sans appareil.',
    loadedLines: 'Lignes {count} chargées.',
    presetSaved: 'Préréglage "{name}" enregistré pour {target}.',
    presetRemoved: 'Préréglage "{name}" supprimé pour {target}.',
    exportLogsSaveLabel: "Registres d'exportation",
    exportedLines: 'Exporté des lignes {count} de {target}.',
    failedToExportLogs: "Échec de l'exportation des registres : {message}",
    failedToExportLogsFallback: 'Il a échoué à exporter des grumes.',
    editOnlyImported: "Éditer n'est disponible que pour les fichiers journaux importés.",
    failedToOpenLogFile: "Impossible d'ouvrir le fichier journal : {message}",
    failedToOpenLogFileFallback: "Impossible d'ouvrir le fichier journal.",
    refreshOnlyImported: "Refresh n'est disponible que pour les fichiers journaux importés.",
    failedToReadLogFile: 'Impossible de lire le fichier journal : {message}',
    failedToReadLogFileFallback: 'Impossible de lire le fichier journal.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: 'Séance close.',
    disconnected: 'Déconnecté.',
    reconnecting: 'Reconnecter...',
    failedToReconnect: 'Il a échoué.',
    autoSaveDialogTitle:
      'Sélectionnez le fichier journal pour enregistrer automatiquement la sortie SSH',
    allFiles: 'Tous les fichiers',
    autoSaveCancelled: 'Enregistrement automatique annulé.',
    autoSaveFailed: "L'enregistrement automatique a échoué : {message}",
    autoSaveFailedFallback: "L'enregistrement automatique a échoué.",
    hostKeyVerificationFailed:
      "La vérification de la clé de l'hôte a échoué pour {target}. {expected} attendu mais reçu {received}. Mettre à jour l'empreinte digitale dans les paramètres pour se reconnecter.",
    sshSessionClosedOn: '--- Session SSH close sur {timestamp}',
  },
};
