/* eslint-disable spellcheck/spell-checker */
import type { en } from './en';

export const hu: typeof en = {
  languageId: 'hu',
  htmlLang: 'hu',
  languageNames: {
    vscode: 'VSCode alapértelmezett',
    en: 'Angol',
    es: 'Spanyol',
    it: 'Olasz',
    'zh-cn': 'Egyszerűsített kínai',
    'zh-tw': 'Hagyományos kínai',
    fr: 'Francia',
    de: 'Német',
    ja: 'Japán',
    ko: 'Koreai',
    ru: 'Orosz',
    'pt-br': 'Portugál (Brazília)',
    tr: 'Török',
    pl: 'Lengyel',
    cs: 'Cseh',
    hu: 'Magyar',
  },
  common: {
    add: 'Hozzáadás',
    cancel: 'Mégse',
    close: 'Bezárás',
    command: 'Parancs',
    copy: 'Másolás',
    default: 'Alapértelmezett',
    disabled: 'Letiltva',
    enabled: 'Engedélyezve',
    exportSettings: 'Beállítások exportálása',
    importSettings: 'Beállítások importálása',
    name: 'Név',
    none: 'Nincs',
    remove: 'Eltávolítás',
    save: 'Mentés',
    select: 'Kiválasztás',
  },
  deviceManager: {
    title: 'Beágyazott eszköz Logger v{version}',
    panelTitle: 'Beágyazott eszközök kezelője',
    intro: 'Eszközök és alapértelmezett konfiguráció kezelése.',
    removeStoredPasswords: 'Eltárolt jelszavak eltávolítása',
    editJson: 'Szerkesztés JSON-ben',
    viewConfigurationExample: 'Konfigurációs példa',
    saveChanges: 'Változások mentése',
    defaults: 'Alapértelmezés',
    defaultsDescription:
      'Alapértelmezett értékek minden eszközre. Minden eszköz megváltoztathatja az eszköztáblában, ha szükséges.',
    enableSshTerminal: 'SSH terminál engedélyezése',
    enableSftpExplorer: 'SFTP felfedező engedélyezése',
    enableExternalWebBrowser: 'Külső böngésző engedélyezése',
    enableEmbeddedWebBrowser: 'Beágyazott böngésző engedélyezése',
    enableDevicePing: 'A készülék pingelésének engedélyezése',
    showBastionOptions: 'Bastion beallitasok megjelenitese',
    language: 'Bővítmény nyelve',
    port: 'Kikötő',
    logCommand: 'Naplózási parancs',
    maxLinesPerTab: 'Maximális sorok fülenként',
    pingIntervalSeconds: 'Ping intervallum (másodperc)',
    pingIntervalPlaceholder: 'Csak a manuális pingeléshez hagyjon üreset',
    sshCommands: 'SSH parancsok',
    groups: 'Csoportok',
    groupsDescription:
      'Határozza meg az opcionális csoportokat, hogy az eszközök a beágyazott eszközök nézetben legyenek rendszerezve.',
    addGroup: 'Csoport hozzáadása',
    devices: 'Eszközök',
    devicesDescription: 'Sorok hozzáadása vagy eltávolítása, majd mezők szerkesztése inline.',
    addDevice: 'Eszköz hozzáadása',
    moveSelectedDevicesUp: 'A kijelölt eszközök mozgatása felfelé a listában',
    moveSelectedDevicesDown: 'A kijelölt eszközök lefelé mozgatása a listában',
    resetPassword: 'Jelszó újraindítása',
    removeStoredPasswordsForSelectedDevices:
      'A tárolt jelszavak és jelszavak eltávolítása a kiválasztott eszközökhöz',
    columnId: 'ID',
    columnGroup: 'Csoport',
    columnColor: 'Szín',
    columnHost: 'Host',
    columnUser: 'Felhasználó',
    columnHostFingerprint: 'Házi ujjlenyomat',
    columnSecondaryHost: 'Másodlagos host',
    columnSecondaryFingerprint: 'Másodlagos ujjlenyomat',
    columnSshTerminal: 'SSH terminál',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'SFTP beállítások (távoli)',
    columnSftpPresetsLocal: 'SFTP presets (helyi)',
    columnExternalWebBrowser: 'Külső böngésző',
    columnEmbeddedWebBrowser: 'Beágyazott webböngésző',
    columnWebUrl: 'Web URL',
    columnPrivateKeyPath: 'Privát kulcsút',
    columnPrivateKeyPassphrase: 'Privát kulcsjelszó',
    columnPasswordWriteOnly: 'Jelszó (csak írni)',
    columnShowDefaultSshCommands: 'Az alapértelmezett SSH parancsok megjelenítése',
    columnBastionHost: 'Bastion host',
    columnBastionPort: 'Bástya kikötő',
    columnBastionUser: 'Bástya felhasználó',
    columnBastionFingerprint: 'Bázis ujjlenyomat',
    columnBastionKeyPath: 'Bástya kulcsút',
    columnBastionKeyPassphrase: 'Báziskulcs jelszó',
    columnBastionPasswordWriteOnly: 'Bástya jelszó (csak írj)',
    groupNamePlaceholder: 'Csoportnév',
    editScript: 'Szkript szerkesztése',
    editScriptFor: 'Szkript szerkesztése a {name}-hez',
    sshCommandFallback: 'SSH parancs',
    scriptDescription: 'Írja le azt a szkriptet, amelyet a /tmp-re másolunk és végrehajtunk.',
    sshCommandScriptEditor: 'SSH parancsszerkesztő',
    commandNamesEmojiHelp: 'Parancsnevek támogatják emojis a https://emojidb.org/',
    openSshPanel: 'SSH megnyitása Panel',
    rerunOnReconnection: 'Újrafuttatás újracsatlakoztatáskor',
    copyAndRunScript: 'A szkript másolása és futtatása',
    addCommand: 'Parancs hozzáadása',
    openCommandInSshPanel: 'A parancs megnyitása SSH panelben',
    openNamedCommandInSshPanel: '{name} megnyitása a SSH panelben',
    rerunCommandAfterReconnect: 'A parancs újrafuttatása a SSH panel újbóli csatlakoztatása után',
    rerunNamedCommandOnReconnect: 'A {name} újraindítása a csatlakozáskor',
    copyScriptToTmp: 'Másolj egy szkriptet a /tmp-re és futtasd le a parancs után',
    copyAndRunScriptFor: 'A {name} parancsfájl másolása és futtatása',
    removeCommand: 'A parancs törlése',
    dragToResize: 'Húzza át a méretre',
    selectDeviceRow: 'Az eszközsor kiválasztása',
    removedSelectedDevice: 'Kiürített eszköz.',
    removedSelectedDevices: 'Eltávolított {count} kijelölt eszközök.',
    saving: 'Megmentem...',
    openingSettingsJson: 'settings.json megnyitása...',
    removingStoredPasswords: 'Tárolt jelszavak eltávolítása...',
    exportingSettings: 'Exportálási beállítások...',
    importingSettings: 'Importáló beállítások...',
    setSelectedDeviceIdBeforeReset:
      'A tárolt jelszó visszaállítása előtt állítsa be legalább egy kiválasztott eszközt, a ID-t.',
    removingStoredPasswordForDevice: 'A {id} jelszó eltávolítása...',
    removingStoredPasswordsForDevices:
      'A {count} kiválasztott eszközökhöz tárolt jelszavak eltávolítása...',
    configurationExample: 'Beállítási példa',
    configurationExampleDescription:
      'Másold le és illeszd be ezeket az alapértelmezéseket a settings.json-be.',
    copiedConfigurationExample: 'Másolt konfigurációs példa.',
    failedToCopyConfigurationExample: 'Nem sikerült másolni a konfigurációs példát.',
    savedSettings: 'Mentett beállítások.',
    failedToSaveSettings: 'Nem sikerült elmenteni a beállításokat.',
    importedSettingsApply:
      'Importált beállítások. Tekintse át őket, és kattintson a Mentés változások alkalmazni őket.',
    failedToImportSettings: 'Nem sikerült importálni a beállításokat.',
    exportSettingsSaveLabel: 'Kiviteli beállítások',
    exportCanceled: 'Export törölve.',
    exportedSettingsTo: 'Exportált beállítások {path}-re.',
    failedToExportSettings: 'Nem sikerült exportálnia: {message}',
    importSettingsOpenLabel: 'Beállítások importálása',
    importCanceled: 'Import törölve.',
    importedSettingsFrom:
      'Importált beállítások a {path}-től. Áttekintés és kattintson a Mentés a módosítások alkalmazásához.',
    failedToImportSettingsWithMessage: 'Nem sikerült importálni: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      'Mentett beállítások. Újratölti az ablakot vagy kiterjesztési host, majd újra elmenti, hogy fenntartsa a beágyazott Web böngésző alapértelmezett.',
    reloadToPersistNewDefaultSettings:
      'A beállítások mentve. Töltse újra az ablakot vagy a bővítménygazdát, majd mentse újra az újonnan hozzáadott alapértelmezett beállítások megőrzéséhez.',
  },
  sidebar: {
    title: 'Beágyazott Logger eszközök',
    copyUrl: 'Másolás URL',
    copyName: 'Név másolása',
    pingInProgress: 'Ping folyamatban',
    pingReachable: 'Ping elérhető',
    pingUnreachable: 'Ping elérhetetlen',
    openLogs: 'Bejelentések megnyitása',
    openLogsFor: 'A {name} naplóinak megnyitása',
    openSshTerminal: 'SSH megnyitása Terminál',
    openSshTerminalFor: 'SSH terminálülés megnyitása a {name} számára',
    openSftpExplorer: 'SFTP megnyitása Felfedező',
    browseAndTransferFilesFor: 'Böngészés és transzfer fájlok {name}',
    openExternalWebBrowser: 'Külső böngésző megnyitása',
    openExternalWebBrowserFor: 'Open the configured web URL for {name} in an external browser',
    openEmbeddedWebBrowser: 'A beágyazott webböngésző megnyitása',
    openEmbeddedWebBrowserFor: 'Nyissa meg a beállított webes URL a {name} a VS Code',
    copyScriptCommandTitle: 'Másold a szkriptet /tmp, chmod 777-re, és futtasd le',
    noDevicesConfigured:
      'Nincs beállított eszköz. Frissítse "embeddedLogger.devices" a beállítások.',
    deviceNameLabel: 'Az eszköz neve',
    deviceUrlLabel: 'URL készülék',
    copiedToClipboard: '{label} másolt vágólapra.',
  },
  deviceTree: {
    noDevicesConfigured:
      'Nincs beállított eszköz. Frissítse "embeddedLogger.devices" a beállítások.',
    openSettingsToConfigure: 'Beágyazott eszközök beállításainak megnyitása.',
    openSettings: 'Beállítások megnyitása',
    openDeviceLogs: 'Eszköznaplók megnyitása',
    groupTooltip: '{name} csoport',
  },
  logPanel: {
    logsTitle: '{name} Naplók',
    minLevel: 'Min- szint',
    textFilter: 'Szövegszűrő',
    filterSubstring: 'Szűrő alsztring',
    filteringPresets: 'Szűrő',
    filterPresets: 'Szűrőelőjelek',
    savePreset: 'A beállítás mentése',
    deletePreset: 'A beállítás törlése',
    exportLogs: 'Exportnaplók',
    editLogFile: 'A naplófájl szerkesztése',
    refreshLogFile: 'A naplófájl frissítése',
    startAutoSave: 'Automatikus mentés indítása',
    stopAutoSave: 'Az automatikus mentés leállítása',
    clearLogs: 'A naplók törlése',
    highlight: 'Kiemelés',
    wordWrap: 'Wordwrap',
    autoScroll: 'Auto- görgetés',
    autoReconnect: 'Automatikus visszacsatlakozás',
    toggleState: '{label} ({state})',
    toggleOn: '-',
    toggleOff: 'kikapcsolva',
    find: 'Keresés',
    findInLogs: 'Keresés naplókban (Ctrl/Cmd+F)',
    clearSearch: 'Keresés törlése',
    previousMatch: 'Előző mérkőzés',
    nextMatch: 'Következő mérkőzés',
    prev: 'Előző',
    next: 'Következő',
    reconnect: 'Csatlakozás',
    disconnect: 'Váltás',
    highlights: 'Kiemelés',
    addHighlight: 'hozzáadás',
    removeAllHighlights: 'távolítsa el az összes',
    highlightKeywords: 'Kulcsszavak kiemelése',
    lineLimitLive:
      'Beállított kijelzősor limit elérte. Az idősebb vonalak helyébe újabb bejegyzések lépnek.',
    lineLimitOffline:
      'Beállított kijelzősor limit elérte. Az idősebb importált vonalakat elrejtették erről a kilátásról.',
    upToTenHighlights: 'Akár 10 billentyűt is kiemelhetsz.',
    keyToHighlight: 'A kiemelés kulcsa',
    removeHighlight: 'A kiemelés eltávolítása',
    noPreset: '(no preset)',
    filterPresetNamed: 'Szűrő előre: {name}',
    connectedStreaming: 'Összekapcsolva. Az áramló naplók...',
    bookmarkLabel: 'Könyvjelző címke',
    enterBookmarkLabel: 'Könyvjelző címke',
    addBookmark: 'Könyvjelző hozzáadása',
    editBookmarkLabel: 'Könyvjelző címke szerkesztése',
    removeBookmark: 'Könyvjelző eltávolítása',
    removeAllBookmarks: 'Minden könyvjelző eltávolítása',
    goToNextBookmark: 'Menj a következő könyvjelzőhöz',
    goToPreviousBookmark: 'Ugrás az előző könyvjelzőre',
    clearStatusMessage: 'Az állapotüzenet törlése',
    connectionClosed: 'Kapcsolat lezárva.',
    retryingInSeconds: '{message} A {seconds} másodperc újraindítása...',
    reconnecting: 'Visszaszerzés...',
    disconnecting: 'Kikapcsolás...',
    hostKeyFailedDetails:
      'A fogadó kulcs ellenőrzése sikertelen. Várható {expected}, de {received}-t kapott. Frissítse az ujjlenyomatot, hogy újra összekapcsolódjon.',
    hostKeyFailed:
      'A fogadó kulcs ellenőrzése sikertelen. Frissítse a tárolt ujjlenyomatot, mielőtt újra összekapcsolódik.',
    sessionClosed: 'Az ülés lezárva.',
    sshSessionClosedOn: '--- SSH munkamenet lezárva {timestamp}',
    dateAtTime: '{date} a {time}-nél',
    autoSavingTo: 'Auto-megtakarítás',
    autoSaveEnabled: 'Auto-mentés engedélyezve.',
    autoSaveFailed: 'Az automatikus mentés nem sikerült.',
    waitingForPassword: 'Várja, hogy a felhasználó beírja a jelszót..',
  },
  extension: {
    missingHost: 'A "{name}" eszköz hiányzik egy gazdatestből.',
    missingUsername: 'A {name} eszközből hiányzik egy felhasználónév.',
    invalidPort: 'Az eszköz "{name}" érvénytelen port.',
    credentialsMigrationWarning:
      'A credents-t a Secret Storage-re vándorolták, de a "jelszó" vagy a "privateKeyPassphrase" mezőket nem sikerült eltávolítani. Kérjük, törölje őket a embeddedLogger.devices-ből a beállításaiban.',
    sftpPresetsMigrationFailed:
      'Nem sikerült a SFTP-t a embeddedLogger.devices.-be migrálni. A meglévő előjelek tovább tárolva maradnak.',
    noHostFound: 'A kiválasztott eszközhöz nem található gazdatest.',
    webUrlMustStart: 'Web böngésző URL kell kezdeni http: / / or https://.',
    invalidWebUrl: 'Érvénytelen webes URL a {name} esetében: {message}',
    deviceNotFound: 'Az eszköz nem található. Ellenőrizze a embeddedLogger.devices.',
    workspaceTrustDeviceResources:
      'A munkatér bizalmára van szükség az eszközforrások megnyitása előtt.',
    workspaceTrustConnect: 'A munkatér-bizalom szükséges az eszközökhöz való csatlakozás előtt.',
    embeddedBrowserUnavailable: 'A VS Code beágyazott böngésző támogatása nem érhető el.',
    failedToOpenUri: 'Nem sikerült megnyitni {uri}: {message}',
    sshCommandNoControlCharacters:
      'A SSH parancs nem tartalmazhat ellenőrző karaktereket vagy új sorokat.',
    runningCommandOnDevice: '"{command}" fut a {device}-n',
    commandFinishedOnDevice: 'A "{command}" parancs befejeződött a {device}-n.',
    noDevicesConfigured: 'Nincs beállított eszköz. Ellenőrizze a embeddedLogger.devices.',
    selectDeviceForSftp: 'Válasszon ki egy eszközt a SFTP felfedező megnyitásához',
    selectDeviceForExternalBrowser: 'Válasszon ki egy eszközt a külső böngészőben',
    selectDeviceForEmbeddedBrowser: 'Válasszon ki egy eszközt a beágyazott böngészőben',
    storedPasswordsRemovedFor:
      'A {device} esetében a tárolt jelszavakat és jelszavakat eltávolították.',
    noDevicesToClearPasswords: 'Nincs beállított eszköz a jelszavak törlésére.',
    storedPasswordsRemoved:
      'A beállított eszközök esetében a tárolt jelszavakat és jelszavakat eltávolították.',
    openLogFile: 'Naplófájl megnyitása',
    failedToReadLogFile: 'Nem sikerült elolvasni a naplófájlt: {message}',
    localPanelSuffix: 'Helyi',
    noDeviceInfo: 'Az eszköz adatai nem állnak rendelkezésre.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Nem lehet naplózási munkamenetet létrehozni eszköz nélkül.',
    loadedLines: 'Töltött {count} vonalak.',
    presetSaved: 'Preset "{name}" mentett a {target}.',
    presetRemoved: 'A {target} esetében eltávolított "{name}" előtag.',
    exportLogsSaveLabel: 'Exportnaplók',
    exportedLines: 'Exportált {count} vonalak {target}.',
    failedToExportLogs: 'Nem sikerült exportrönköket exportálni: {message}',
    failedToExportLogsFallback: 'Nem sikerült exportálni a naplót.',
    editOnlyImported: 'Szerkesztés csak import log fájlok.',
    failedToOpenLogFile: 'Nem sikerült megnyitni a naplófájlt: {message}',
    failedToOpenLogFileFallback: 'Nem sikerült megnyitni a naplófájlt.',
    refreshOnlyImported: 'Frissítés csak importált log fájlok.',
    failedToReadLogFile: 'Nem sikerült elolvasni a naplófájlt: {message}',
    failedToReadLogFileFallback: 'Nem sikerült elolvasni a naplófájlt.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: 'Az ülés lezárva.',
    disconnected: 'Kikapcsolva.',
    reconnecting: 'Visszaszerzés...',
    failedToReconnect: 'Nem sikerült újra csatlakozni.',
    autoSaveDialogTitle: 'Válassza ki a log fájlt az auto- mentés SSH kimenetéhez',
    allFiles: 'Minden fájl',
    autoSaveCancelled: 'Auto-mentés törölve.',
    autoSaveFailed: 'Az automatikus mentés nem sikerült: {message}',
    autoSaveFailedFallback: 'Az automatikus mentés nem sikerült.',
    hostKeyVerificationFailed:
      'A {target} esetében nem sikerült a fogadási kulcs hitelesítése. Várható {expected}, de {received}-t kapott. Frissítse az ujjlenyomatot a beállítások, hogy újra csatlakozik.',
    sshSessionClosedOn: '--- SSH munkamenet lezárva {timestamp}',
  },
};
