/* eslint-disable spellcheck/spell-checker */
import type { en } from './en';

export const it: typeof en = {
  languageId: 'it',
  htmlLang: 'it',
  languageNames: {
    vscode: 'Predefinito di VSCode',
    en: 'Inglese',
    es: 'Spagnolo',
    it: 'Italiano',
  },
  common: {
    add: 'Aggiungi',
    cancel: 'Annulla',
    close: 'Chiudi',
    command: 'Comando',
    copy: 'Copia',
    default: 'Predefinito',
    disabled: 'Disabilitato',
    enabled: 'Abilitato',
    exportSettings: 'Esporta impostazioni',
    importSettings: 'Importa impostazioni',
    name: 'Nome',
    none: 'Nessuno',
    remove: 'Rimuovi',
    save: 'Salva',
    select: 'Seleziona',
  },
  deviceManager: {
    title: 'Embedded Device Logger v{version}',
    panelTitle: 'Gestore dispositivi embedded',
    intro: 'Gestisci dispositivi e configurazione predefinita.',
    removeStoredPasswords: 'Rimuovi password salvate',
    editJson: 'Modifica in JSON',
    viewConfigurationExample: 'Visualizza esempio di configurazione',
    saveChanges: 'Salva modifiche',
    defaults: 'Predefiniti',
    defaultsDescription:
      'Valori predefiniti per tutti i dispositivi. Ogni dispositivo puo cambiarli nella tabella se necessario.',
    enableSshTerminal: 'Abilita terminale SSH',
    enableSftpExplorer: 'Abilita esplora SFTP',
    enableExternalWebBrowser: 'Abilita browser web esterno',
    enableEmbeddedWebBrowser: 'Abilita browser web embedded',
    enableDevicePing: 'Abilita ping dispositivi',
    language: 'Lingua estensione',
    port: 'Porta',
    logCommand: 'Comando log',
    maxLinesPerTab: 'Righe massime per scheda',
    pingIntervalSeconds: 'Intervallo ping (secondi)',
    pingIntervalPlaceholder: 'Lascia vuoto per ping manuale',
    sshCommands: 'Comandi SSH',
    groups: 'Gruppi',
    groupsDescription: 'Definisci gruppi opzionali per organizzare i dispositivi nella vista.',
    addGroup: 'Aggiungi gruppo',
    devices: 'Dispositivi',
    devicesDescription: 'Aggiungi o rimuovi righe, poi modifica i campi in linea.',
    addDevice: 'Aggiungi dispositivo',
    moveSelectedDevicesUp: 'Sposta in alto i dispositivi selezionati',
    moveSelectedDevicesDown: 'Sposta in basso i dispositivi selezionati',
    resetPassword: 'Reimposta password',
    removeStoredPasswordsForSelectedDevices:
      'Rimuovi password e passphrase salvate per i dispositivi selezionati',
    columnId: 'ID',
    columnGroup: 'Gruppo',
    columnColor: 'Colore',
    columnHost: 'Host',
    columnUser: 'Utente',
    columnHostFingerprint: 'Fingerprint host',
    columnSecondaryHost: 'Host secondario',
    columnSecondaryFingerprint: 'Fingerprint secondaria',
    columnSshTerminal: 'Terminale SSH',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'Preset SFTP (remoto)',
    columnSftpPresetsLocal: 'Preset SFTP (locale)',
    columnExternalWebBrowser: 'Browser web esterno',
    columnEmbeddedWebBrowser: 'Browser web embedded',
    columnWebUrl: 'URL web',
    columnPrivateKeyPath: 'Percorso chiave privata',
    columnPrivateKeyPassphrase: 'Passphrase chiave privata',
    columnPasswordWriteOnly: 'Password (solo scrittura)',
    columnShowDefaultSshCommands: 'Mostra comandi SSH predef.',
    columnBastionHost: 'Host bastion',
    columnBastionPort: 'Porta bastion',
    columnBastionUser: 'Utente bastion',
    columnBastionFingerprint: 'Fingerprint bastion',
    columnBastionKeyPath: 'Percorso chiave bastion',
    columnBastionKeyPassphrase: 'Passphrase chiave bastion',
    columnBastionPasswordWriteOnly: 'Password bastion (solo scrittura)',
    groupNamePlaceholder: 'Nome gruppo',
    editScript: 'Modifica script',
    editScriptFor: 'Modifica script per {name}',
    sshCommandFallback: 'comando SSH',
    scriptDescription: 'Scrivi lo script che verra copiato in /tmp ed eseguito.',
    sshCommandScriptEditor: 'Editor script comando SSH',
    commandNamesEmojiHelp: 'I nomi dei comandi supportano emoji da https://emojidb.org/',
    openSshPanel: 'Apri pannello SSH',
    rerunOnReconnection: 'Riesegui alla riconnessione',
    copyAndRunScript: 'Copia ed esegui script',
    addCommand: 'Aggiungi comando',
    openCommandInSshPanel: 'Apri questo comando in un pannello SSH',
    openNamedCommandInSshPanel: 'Apri {name} in un pannello SSH',
    rerunCommandAfterReconnect: 'Riesegui questo comando dopo la riconnessione del pannello SSH',
    rerunNamedCommandOnReconnect: 'Riesegui {name} alla riconnessione',
    copyScriptToTmp: 'Copia uno script in /tmp ed eseguilo dopo il comando',
    copyAndRunScriptFor: 'Copia ed esegui script per {name}',
    removeCommand: 'Rimuovi comando',
    dragToResize: 'Trascina per ridimensionare',
    selectDeviceRow: 'Seleziona riga dispositivo',
    removedSelectedDevice: 'Dispositivo selezionato rimosso.',
    removedSelectedDevices: 'Rimossi {count} dispositivi selezionati.',
    saving: 'Salvataggio...',
    openingSettingsJson: 'Apertura settings.json...',
    removingStoredPasswords: 'Rimozione password salvate...',
    exportingSettings: 'Esportazione impostazioni...',
    importingSettings: 'Importazione impostazioni...',
    setSelectedDeviceIdBeforeReset:
      "Imposta l'ID di almeno un dispositivo selezionato prima di reimpostare la password salvata.",
    removingStoredPasswordForDevice: 'Rimozione password salvata per {id}...',
    removingStoredPasswordsForDevices:
      'Rimozione password salvate per {count} dispositivi selezionati...',
    configurationExample: 'Esempio di configurazione',
    configurationExampleDescription: 'Copia e incolla questi valori nel tuo settings.json.',
    copiedConfigurationExample: 'Esempio di configurazione copiato.',
    failedToCopyConfigurationExample: "Impossibile copiare l'esempio di configurazione.",
    savedSettings: 'Impostazioni salvate.',
    failedToSaveSettings: 'Impossibile salvare le impostazioni.',
    importedSettingsApply: 'Impostazioni importate. Controllale e fai clic su Salva modifiche.',
    failedToImportSettings: 'Impossibile importare le impostazioni.',
    exportSettingsSaveLabel: 'Esporta impostazioni',
    exportCanceled: 'Esportazione annullata.',
    exportedSettingsTo: 'Impostazioni esportate in {path}.',
    failedToExportSettings: 'Impossibile esportare le impostazioni: {message}',
    importSettingsOpenLabel: 'Importa impostazioni',
    importCanceled: 'Importazione annullata.',
    importedSettingsFrom:
      'Impostazioni importate da {path}. Controllale e fai clic su Salva modifiche per applicarle.',
    failedToImportSettingsWithMessage: 'Impossibile importare le impostazioni: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      "Impostazioni salvate. Ricarica la finestra o l'host dell'estensione, poi salva di nuovo per rendere persistente il browser web embedded predefinito.",
  },
  sidebar: {
    title: 'Dispositivi di Embedded Logger',
    copyUrl: 'Copia URL',
    copyName: 'Copia nome',
    pingInProgress: 'Ping in corso',
    pingReachable: 'Ping raggiungibile',
    pingUnreachable: 'Ping non raggiungibile',
    openLogs: 'Apri log',
    openLogsFor: 'Apri log per {name}',
    openSshTerminal: 'Apri terminale SSH',
    openSshTerminalFor: 'Apri una sessione terminale SSH per {name}',
    openSftpExplorer: 'Apri esplora SFTP',
    browseAndTransferFilesFor: 'Sfoglia e trasferisci file per {name}',
    openExternalWebBrowser: 'Apri browser web esterno',
    openExternalWebBrowserFor: 'Apri nel browser esterno la URL web configurata per {name}',
    openEmbeddedWebBrowser: 'Apri browser web embedded',
    openEmbeddedWebBrowserFor: 'Apri in VS Code la URL web configurata per {name}',
    copyScriptCommandTitle: 'Copia script in /tmp, chmod 777 ed eseguilo',
    noDevicesConfigured: 'Nessun dispositivo configurato. Aggiorna "embeddedLogger.devices".',
    deviceNameLabel: 'Nome dispositivo',
    deviceUrlLabel: 'URL dispositivo',
    copiedToClipboard: '{label} copiato negli appunti.',
  },
  deviceTree: {
    noDevicesConfigured: 'Nessun dispositivo configurato. Aggiorna "embeddedLogger.devices".',
    openSettingsToConfigure: 'Apri impostazioni per configurare dispositivi embedded.',
    openSettings: 'Apri impostazioni',
    openDeviceLogs: 'Apri log dispositivo',
    groupTooltip: 'Gruppo {name}',
  },
  logPanel: {
    logsTitle: 'Log di {name}',
    minLevel: 'Livello minimo',
    textFilter: 'Filtro testo',
    filterSubstring: 'Filtra sottostringa',
    filteringPresets: 'Preset di filtro',
    filterPresets: 'Preset filtro',
    savePreset: 'Salva preset',
    deletePreset: 'Elimina preset',
    exportLogs: 'Esporta log',
    editLogFile: 'Modifica file log',
    refreshLogFile: 'Aggiorna file log',
    startAutoSave: 'Avvia salvataggio automatico',
    stopAutoSave: 'Ferma salvataggio automatico',
    clearLogs: 'Cancella log',
    highlight: 'Evidenzia',
    wordWrap: 'A capo automatico',
    autoScroll: 'Scorrimento automatico',
    autoReconnect: 'Riconnessione automatica',
    toggleState: '{label} ({state})',
    toggleOn: 'attivo',
    toggleOff: 'non attivo',
    find: 'Trova',
    findInLogs: 'Trova nei log (Ctrl/Cmd+F)',
    clearSearch: 'Cancella ricerca',
    previousMatch: 'Corrispondenza precedente',
    nextMatch: 'Corrispondenza successiva',
    prev: 'Prec.',
    next: 'Succ.',
    reconnect: 'Riconnetti',
    disconnect: 'Disconnetti',
    highlights: 'Evidenziazioni',
    addHighlight: 'aggiungi',
    removeAllHighlights: 'rimuovi tutto',
    highlightKeywords: 'Parole da evidenziare',
    lineLimitLive:
      'Raggiunto il limite configurato di righe visualizzate. Le righe meno recenti vengono sostituite con nuove voci.',
    lineLimitOffline:
      'Raggiunto il limite configurato di righe visualizzate. Le righe importate meno recenti sono state nascoste in questa vista.',
    upToTenHighlights: 'Puoi evidenziare fino a 10 chiavi.',
    keyToHighlight: 'Chiave da evidenziare',
    removeHighlight: 'Rimuovi evidenziazione',
    noPreset: '(nessun preset)',
    filterPresetNamed: 'Preset filtro: {name}',
    connectedStreaming: 'Connesso. Streaming log...',
    bookmarkLabel: 'Etichetta segnalibro',
    enterBookmarkLabel: 'Inserisci etichetta segnalibro',
    addBookmark: 'Aggiungi segnalibro',
    editBookmarkLabel: 'Modifica etichetta segnalibro',
    removeBookmark: 'Rimuovi segnalibro',
    removeAllBookmarks: 'Rimuovi tutti i segnalibri',
    goToNextBookmark: 'Vai al segnalibro successivo',
    goToPreviousBookmark: 'Vai al segnalibro precedente',
    clearStatusMessage: 'Cancella messaggio di stato',
    connectionClosed: 'Connessione chiusa.',
    retryingInSeconds: '{message} Nuovo tentativo tra {seconds} secondi...',
    reconnecting: 'Riconnessione...',
    disconnecting: 'Disconnessione...',
    hostKeyFailedDetails:
      'Verifica chiave host non riuscita. Previsto {expected}, ricevuto {received}. Aggiorna la fingerprint per riconnettere.',
    hostKeyFailed:
      'Verifica chiave host non riuscita. Aggiorna la fingerprint salvata prima di riconnettere.',
    sessionClosed: 'Sessione chiusa.',
    sshSessionClosedOn: '--- Sessione SSH chiusa il {timestamp}',
    dateAtTime: '{date} alle {time}',
    autoSavingTo: 'Salvataggio automatico in',
    autoSaveEnabled: 'Salvataggio automatico abilitato.',
    autoSaveFailed: 'Salvataggio automatico non riuscito.',
    waitingForPassword: "In attesa dell'inserimento della password da parte dell'utente…",
  },
  extension: {
    missingHost: 'Al dispositivo "{name}" manca un host.',
    missingUsername: 'Al dispositivo "{name}" manca un nome utente.',
    invalidPort: 'Il dispositivo "{name}" ha una porta non valida.',
    credentialsMigrationWarning:
      'Le credenziali sono state migrate in Secret Storage, ma i campi "password" o "privateKeyPassphrase" non sono stati rimossi. Rimuovili da embeddedLogger.devices nelle impostazioni.',
    sftpPresetsMigrationFailed:
      "Impossibile migrare i preset SFTP in embeddedLogger.devices. I preset esistenti restano nell'archiviazione dell'estensione.",
    noHostFound: 'Nessun host trovato per il dispositivo selezionato.',
    webUrlMustStart: 'Le URL web devono iniziare con http:// o https://.',
    invalidWebUrl: 'URL web non valida per {name}: {message}',
    deviceNotFound: 'Dispositivo non trovato. Controlla embeddedLogger.devices.',
    workspaceTrustDeviceResources:
      'La fiducia nel workspace e richiesta prima di aprire risorse del dispositivo.',
    workspaceTrustConnect:
      'La fiducia nel workspace e richiesta prima di connettersi ai dispositivi.',
    embeddedBrowserUnavailable: 'Il supporto browser embedded di VS Code non e disponibile.',
    failedToOpenUri: 'Impossibile aprire {uri}: {message}',
    sshCommandNoControlCharacters:
      'Il comando SSH non deve contenere caratteri di controllo o nuove righe.',
    runningCommandOnDevice: 'Esecuzione di "{command}" su {device}',
    commandFinishedOnDevice: 'Comando "{command}" terminato su {device}.',
    noDevicesConfigured: 'Nessun dispositivo configurato. Controlla embeddedLogger.devices.',
    selectDeviceForSftp: 'Seleziona un dispositivo per aprire esplora SFTP',
    selectDeviceForExternalBrowser: 'Seleziona un dispositivo da aprire nel browser web esterno',
    selectDeviceForEmbeddedBrowser: 'Seleziona un dispositivo da aprire nel browser web embedded',
    storedPasswordsRemovedFor: 'Password e passphrase salvate sono state rimosse per {device}.',
    noDevicesToClearPasswords: 'Nessun dispositivo configurato da cui rimuovere password.',
    storedPasswordsRemoved:
      'Password e passphrase salvate sono state rimosse per i dispositivi configurati.',
    openLogFile: 'Apri file log',
    failedToReadLogFile: 'Impossibile leggere il file log: {message}',
    localPanelSuffix: 'Locale',
    noDeviceInfo: 'Nessuna informazione dispositivo fornita.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Impossibile creare una sessione log senza dispositivo.',
    loadedLines: 'Caricate {count} righe.',
    presetSaved: 'Preset "{name}" salvato per {target}.',
    presetRemoved: 'Preset "{name}" rimosso per {target}.',
    exportLogsSaveLabel: 'Esporta log',
    exportedLines: 'Esportate {count} righe da {target}.',
    failedToExportLogs: 'Impossibile esportare i log: {message}',
    failedToExportLogsFallback: 'Impossibile esportare i log.',
    editOnlyImported: 'La modifica e disponibile solo per file log importati.',
    failedToOpenLogFile: 'Impossibile aprire il file log: {message}',
    failedToOpenLogFileFallback: 'Impossibile aprire il file log.',
    refreshOnlyImported: "L'aggiornamento e disponibile solo per file log importati.",
    failedToReadLogFile: 'Impossibile leggere il file log: {message}',
    failedToReadLogFileFallback: 'Impossibile leggere il file log.',
    reloadedLinesFrom: 'Ricaricate {count} righe da {file}.',
    sessionClosed: 'Sessione chiusa.',
    disconnected: 'Disconnesso.',
    reconnecting: 'Riconnessione...',
    failedToReconnect: 'Impossibile riconnettere.',
    autoSaveDialogTitle: 'Seleziona file log per salvare automaticamente output SSH',
    allFiles: 'Tutti i file',
    autoSaveCancelled: 'Salvataggio automatico annullato.',
    autoSaveFailed: 'Salvataggio automatico non riuscito: {message}',
    autoSaveFailedFallback: 'Salvataggio automatico non riuscito.',
    hostKeyVerificationFailed:
      'Verifica chiave host non riuscita per {target}. Previsto {expected}, ricevuto {received}. Aggiorna la fingerprint nelle impostazioni per riconnettere.',
    sshSessionClosedOn: '--- Sessione SSH chiusa il {timestamp}',
  },
};
