import type { en } from './en';

export const ja: typeof en = {
  languageId: 'ja',
  htmlLang: 'ja',
  languageNames: {
    vscode: 'VSCode の既定',
    en: '英語',
    es: 'スペイン語',
    it: 'イタリア語',
    'zh-cn': '簡体字中国語',
    'zh-tw': '繁体字中国語',
    fr: 'フランス語',
    de: 'ドイツ語',
    ja: '日本語',
    ko: '韓国語',
    ru: 'ロシア語',
    'pt-br': 'ポルトガル語 (ブラジル)',
    tr: 'トルコ語',
    pl: 'ポーランド語',
    cs: 'チェコ語',
    hu: 'ハンガリー語',
  },
  common: {
    add: '追加',
    cancel: 'キャンセル',
    close: '閉じる',
    command: 'コマンド',
    copy: 'コピー',
    default: '既定',
    disabled: '無効',
    enabled: '有効',
    exportSettings: '設定をエクスポート',
    importSettings: '設定をインポート',
    name: '名前',
    none: 'なし',
    remove: '削除',
    save: '保存',
    select: '選択',
  },
  deviceManager: {
    title: '組み込みデバイスロガーv{version}',
    panelTitle: '組み込みデバイス マネージャー',
    intro: 'デバイスと既定の構成を管理します。',
    removeStoredPasswords: '保存したパスワードを削除します',
    editJson: 'JSONで編集',
    viewConfigurationExample: '設定例を見る',
    saveChanges: '変更を保存',
    defaults: 'デフォルト',
    defaultsDescription:
      'すべてのデバイスのデフォルト値。 各デバイスは、必要に応じてデバイステーブルで変更できます.',
    enableSshTerminal: 'SSHターミナルを有効にする',
    enableSftpExplorer: 'SFTPエクスプローラを有効にする',
    enableExternalWebBrowser: '外部Webブラウザを有効にする',
    enableEmbeddedWebBrowser: '埋め込まれたWebブラウザを有効にする',
    enableDevicePing: 'デバイスのpingを有効にする',
    language: '拡張機能の言語',
    port: 'ポートレート',
    logCommand: 'ログコマンド',
    maxLinesPerTab: 'タブごとの最高のライン',
    pingIntervalSeconds: 'ピン間隔(秒)',
    pingIntervalPlaceholder: '手動のpingだけのための空白を残す',
    sshCommands: 'SSHコマンド',
    groups: 'グループ',
    groupsDescription:
      '組み込みデバイスビューでデバイスを整理するためのオプショングループを定義します.',
    addGroup: 'グループを追加',
    devices: 'デバイス',
    devicesDescription: '行を追加または削除し、フィールドのインラインを編集します.',
    addDevice: 'デバイスを追加',
    moveSelectedDevicesUp: '選択したデバイスをリストに移動する',
    moveSelectedDevicesDown: '選択したデバイスをリストに移動する',
    resetPassword: 'パスワードの再設定',
    removeStoredPasswordsForSelectedDevices:
      '保存されたパスワードとパスフレーズを選択したデバイスに削除する',
    columnId: 'IDの特長',
    columnGroup: 'グループ',
    columnColor: 'カラー',
    columnHost: 'ホスト',
    columnUser: 'ユーザー登録',
    columnHostFingerprint: 'ホストの指紋',
    columnSecondaryHost: '二次ホスト',
    columnSecondaryFingerprint: '二次指紋',
    columnSshTerminal: 'SSHターミナル',
    columnSftp: 'SFTPの特長',
    columnSftpPresetsRemote: 'SFTPプリセット(リモート)',
    columnSftpPresetsLocal: 'SFTPプリセット(ローカル)',
    columnExternalWebBrowser: '外部Webブラウザ',
    columnEmbeddedWebBrowser: '組み込みWebブラウザ',
    columnWebUrl: 'ウェブ URL',
    columnPrivateKeyPath: 'プライベートキーパス',
    columnPrivateKeyPassphrase: 'プライベートキーパスフレーズ',
    columnPasswordWriteOnly: 'パスワード(書き込みのみ)',
    columnShowDefaultSshCommands: 'デフォルト SSH コマンドを表示',
    columnBastionHost: 'Bastion ホスト',
    columnBastionPort: 'バスションポート',
    columnBastionUser: 'Bastion ユーザー',
    columnBastionFingerprint: '洗練の指紋',
    columnBastionKeyPath: 'Bastionキーパス',
    columnBastionKeyPassphrase: 'Bastionのキーのパスフレーズ',
    columnBastionPasswordWriteOnly: 'Bastion パスワード (書き込みのみ)',
    groupNamePlaceholder: 'グループ名',
    editScript: 'スクリプトの編集',
    editScriptFor: '{name}の編集スクリプト',
    sshCommandFallback: 'SSHコマンド',
    scriptDescription: '/tmpにコピーして実行するスクリプトを書きます.',
    sshCommandScriptEditor: 'SSHコマンドスクリプトエディタ',
    commandNamesEmojiHelp: 'コマンド名は https://emojidb.org/ から emoji をサポート',
    openSshPanel: 'SSHを開く パネル',
    rerunOnReconnection: '再接続で再実行',
    copyAndRunScript: 'スクリプトのコピーと実行',
    addCommand: 'コマンドの追加',
    openCommandInSshPanel: 'SSHパネルでこのコマンドを開く',
    openNamedCommandInSshPanel: 'SSHのパネルの{name}を開けて下さい',
    rerunCommandAfterReconnect: 'SSHパネル再接続後、このコマンドを再実行',
    rerunNamedCommandOnReconnect: '再接続の{name}を再実行',
    copyScriptToTmp: 'スクリプトを/tmpにコピーし、コマンドの後に実行します',
    copyAndRunScriptFor: '{name}のスクリプトをコピーして実行する',
    removeCommand: 'コマンドの削除',
    dragToResize: 'ドラッグしてサイズを変更',
    selectDeviceRow: 'デバイス行を選択',
    removedSelectedDevice: '選択したデバイスを削除します.',
    removedSelectedDevices: '{count} 選択したデバイスを削除します.',
    saving: '保存...',
    openingSettingsJson: 'settings.jsonをオープン...',
    removingStoredPasswords: '保存したパスワードを削除...',
    exportingSettings: 'エクスポート設定...',
    importingSettings: 'インポート設定...',
    setSelectedDeviceIdBeforeReset:
      '保存されたパスワードをリセットする前に、少なくとも1つの選択したデバイスIDを設定します.',
    removingStoredPasswordForDevice: '{id}の保存されたパスワードを削除する...',
    removingStoredPasswordsForDevices:
      '{count}の保存されたパスワードを削除する 選択したデバイス...',
    configurationExample: '設定例',
    configurationExampleDescription: 'これらのデフォルトをsettings.jsonにコピーして貼り付けます.',
    copiedConfigurationExample: 'コンパイルされた設定例.',
    failedToCopyConfigurationExample: '設定例をコピーできません.',
    savedSettings: '保存された設定.',
    failedToSaveSettings: '設定を保存できません.',
    importedSettingsApply:
      'インポートされた設定。 それらを見直し、変更を保存をクリックして、それらを適用します.',
    failedToImportSettings: '設定をインポートできませんでした.',
    exportSettingsSaveLabel: 'エクスポート設定',
    exportCanceled: '輸出キャンセル.',
    exportedSettingsTo: '{path}へのエクスポート設定.',
    failedToExportSettings: '設定をエクスポートできなかった: {message}の特長',
    importSettingsOpenLabel: 'インポート設定',
    importCanceled: 'キャンセルをインポートします.',
    importedSettingsFrom:
      '{path}からインポートされた設定。 変更を保存してクリックして、それらを適用します.',
    failedToImportSettingsWithMessage: '設定をインポートできなかった: {message}の特長',
    reloadToPersistEmbeddedBrowserDefault:
      '保存された設定。 ウィンドウまたは拡張ホストをリロードし、埋め込みWebブラウザのデフォルトを永続的に保存します.',
    reloadToPersistNewDefaultSettings:
      '設定を保存しました。新しく追加された既定の設定を保持するには、ウィンドウまたは拡張機能ホストを再読み込みしてから、もう一度保存してください。',
  },
  sidebar: {
    title: '組込みロガーデバイス',
    copyUrl: 'URLのコピー',
    copyName: 'コピー名',
    pingInProgress: '進行中のピン',
    pingReachable: 'ピン到達可能',
    pingUnreachable: 'ピンの到達不能',
    openLogs: 'ログを開く',
    openLogsFor: '{name}用のログを開く',
    openSshTerminal: 'SSHを開く ターミナル',
    openSshTerminalFor: '{name}用のSSHターミナルセッションを開く',
    openSftpExplorer: 'SFTPを開く エクスプローラー',
    browseAndTransferFilesFor: '{name}用のファイルをブラウズして転送する',
    openExternalWebBrowser: '外部Webブラウザを開く',
    openExternalWebBrowserFor: '外部ブラウザで{name}用の設定されたWeb URLを開きます',
    openEmbeddedWebBrowser: '組み込みWebブラウザを開く',
    openEmbeddedWebBrowserFor: 'Open the configured web URL for {name} in VS Code',
    copyScriptCommandTitle: 'スクリプトを/tmp、chmod 777にコピーし、実行します',
    noDevicesConfigured:
      'デバイスの設定はありません。 設定で「embeddedLogger.devices」を更新します.',
    deviceNameLabel: 'デバイス名',
    deviceUrlLabel: 'デバイス URL',
    copiedToClipboard: '{label}はクリップボードにコピーしました.',
  },
  deviceTree: {
    noDevicesConfigured:
      'デバイスの設定はありません。 設定で「embeddedLogger.devices」を更新します.',
    openSettingsToConfigure: '埋め込まれたデバイスを構成する設定を開きます.',
    openSettings: '設定を開く',
    openDeviceLogs: 'デバイスログを開く',
    groupTooltip: '{name}グループ',
  },
  logPanel: {
    logsTitle: '{name}の特長 ログイン',
    minLevel: '最低レベル',
    textFilter: 'テキスト フィルター',
    filterSubstring: 'フィルター サブストリング',
    filteringPresets: 'フィルタリングプリセット',
    filterPresets: 'フィルタープリセット',
    savePreset: 'プリセットを保存',
    deletePreset: 'プリセットの削除',
    exportLogs: 'エクスポートログ',
    editLogFile: 'ログファイルを編集する',
    refreshLogFile: 'ログファイルを更新',
    startAutoSave: '自動保存を開始する',
    stopAutoSave: '自動保存を停止する',
    clearLogs: 'クリアログ',
    highlight: 'ハイライト',
    wordWrap: 'ワードラップ',
    autoScroll: '自動スクロールロール',
    autoReconnect: '自動再接続',
    toggleState: '{label} ({state})',
    toggleOn: 'お問い合わせ',
    toggleOff: 'オフ',
    find: '詳しくはこちら',
    findInLogs: 'ログで探す (Ctrl/Cmd+F)',
    clearSearch: '明確な検索',
    previousMatch: '前の試合',
    nextMatch: '次のマッチ',
    prev: '前のページ',
    next: '次へ',
    reconnect: '再接続',
    disconnect: '接続解除',
    highlights: 'ハイライト',
    addHighlight: '追加する',
    removeAllHighlights: 'すべて削除',
    highlightKeywords: 'ハイライトキーワード',
    lineLimitLive: '設定された表示ライン限界に達しました。 古い行は新しいエントリに置換されます.',
    lineLimitOffline:
      '設定された表示ライン限界に達しました。 古いインポートラインは、このビューから隠されました.',
    upToTenHighlights: '10キーまでハイライトできます.',
    keyToHighlight: 'ハイライトするキー',
    removeHighlight: 'ハイライトを削除',
    noPreset: '(プリセットなし)',
    filterPresetNamed: 'フィルタープリセット: {name}',
    connectedStreaming: '接続しました。 ログをストリーミング...',
    bookmarkLabel: 'ブックマークラベル',
    enterBookmarkLabel: 'ブックマークラベルを入力',
    addBookmark: 'ブックマークを追加',
    editBookmarkLabel: 'ブックマークラベルの編集',
    removeBookmark: 'ブックマークの削除',
    removeAllBookmarks: 'すべてのブックマークを削除します',
    goToNextBookmark: '次のブックマークへ',
    goToPreviousBookmark: '前のブックマークに移動',
    clearStatusMessage: 'ステータスメッセージをクリアする',
    connectionClosed: '関係は閉まりました.',
    retryingInSeconds: '{message}の特長 {seconds}秒で再試行...',
    reconnecting: '再接続...',
    disconnecting: '切断...',
    hostKeyFailedDetails:
      'ホストキーの検証が失敗しました。 {expected}を期待していたが、{received}を受け取った。 指紋を更新して再接続します.',
    hostKeyFailed: 'ホストキーの検証が失敗しました。 再接続する前に保存された指紋を更新します.',
    sessionClosed: 'セッションは終了しました.',
    sshSessionClosedOn: '--- SSH セッションは {timestamp} でクローズ',
    dateAtTime: '{time}の{date}',
    autoSavingTo: '自動セービングへの',
    autoSaveEnabled: '自動保存を有効にしました.',
    autoSaveFailed: '自動保存が失敗しました.',
    waitingForPassword: 'ユーザがパスワードを入力するのを待って..',
  },
  extension: {
    missingHost: 'デバイス "{name}" はホストが欠落しています.',
    missingUsername: 'デバイス "{name}" はユーザ名が欠落しています.',
    invalidPort: 'デバイス「{name}」は無効なポートを持っています.',
    credentialsMigrationWarning:
      'クレデンシャルはSecret Storageに移行しましたが、「パスワード」または「privateKeyPassphrase」フィールドは削除できませんでした。 設定のembeddedLogger.devicesから削除してください.',
    sftpPresetsMigrationFailed:
      'SFTP プリセットを embeddedLogger.devices. に移行できなかった 既存のプリセットは、拡張ストレージに残ります.',
    noHostFound: '選択したデバイスでホストが見つかりません.',
    webUrlMustStart: 'ウェブブラウザ URLs は http:// または https://. から始まる必要があります',
    invalidWebUrl: '{name}のための無効なウェブURL:{message}',
    deviceNotFound: 'デバイスが見つかりません。 embeddedLogger.devices.をチェック',
    workspaceTrustDeviceResources: 'デバイスリソースを開く前に、ワークスペースの信頼が必要です.',
    workspaceTrustConnect: 'デバイスに接続する前に、ワークスペースの信頼が必要です.',
    embeddedBrowserUnavailable: 'VS Code 組込みブラウザのサポートは利用できません.',
    failedToOpenUri: '開くことの失敗 {uri}: {message}',
    sshCommandNoControlCharacters: 'SSHコマンドは、制御文字や新しい行が含まれていません.',
    runningCommandOnDevice: '{device}で{command}を実行',
    commandFinishedOnDevice: '{device} でコマンド "{command}" が完成しました.',
    noDevicesConfigured: 'デバイスの設定はありません。 embeddedLogger.devices.をチェック',
    selectDeviceForSftp: 'SFTPエクスプローラを開くためにデバイスを選択',
    selectDeviceForExternalBrowser: '外部Webブラウザで開くデバイスを選択します',
    selectDeviceForEmbeddedBrowser: '埋め込まれたWebブラウザで開くデバイスを選択します',
    storedPasswordsRemovedFor: '{device}では、パスワードとパスフレーズが削除されました.',
    noDevicesToClearPasswords: 'パスワードをクリアするように設定されたデバイスはありません.',
    storedPasswordsRemoved: '設定されたデバイスでパスワードとパスフレーズを削除しました.',
    openLogFile: 'ログファイルを開く',
    failedToReadLogFile: 'ログファイルを読むのに失敗した: {message}',
    localPanelSuffix: 'ローカル',
    noDeviceInfo: '提供されているデバイス情報はありません.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'デバイスなしでログセッションを作成できません.',
    loadedLines: 'ロードされた{count}ライン.',
    presetSaved: '{target}に保存されたプリセット「{name}」.',
    presetRemoved: '{target} 用に削除されたプリセット "{name}".',
    exportLogsSaveLabel: 'エクスポートログ',
    exportedLines: '{target}から{count}ラインをエクスポートしました.',
    failedToExportLogs: 'ログをエクスポートできない: {message}の特長',
    failedToExportLogsFallback: 'ログをエクスポートできません.',
    editOnlyImported: 'インポートされたログファイルのみ編集が可能です.',
    failedToOpenLogFile: 'ログファイルを開くのに失敗した: {message}',
    failedToOpenLogFileFallback: 'ログファイルを開くことができません.',
    refreshOnlyImported: 'インポートされたログファイルのみでリフレッシュできます.',
    failedToReadLogFile: 'ログファイルを読むのに失敗した: {message}',
    failedToReadLogFileFallback: 'ログファイルを読むのに失敗しました.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: 'セッションは終了しました.',
    disconnected: '切断.',
    reconnecting: '再接続...',
    failedToReconnect: '再接続に失敗しました.',
    autoSaveDialogTitle: 'ログファイルを選択して、SSH出力を自動保存',
    allFiles: 'すべてのファイル',
    autoSaveCancelled: '自動保存キャンセル.',
    autoSaveFailed: '自動保存失敗: {message}',
    autoSaveFailedFallback: '自動保存が失敗しました.',
    hostKeyVerificationFailed:
      '{target}のホストキーの検証に失敗しました。 {expected}を期待していたが、{received}を受け取った。 再接続するための設定で指紋を更新します.',
    sshSessionClosedOn: '--- SSH セッションは {timestamp} でクローズ',
  },
};
