import type { en } from './en';

export const ko: typeof en = {
  languageId: 'ko',
  htmlLang: 'ko',
  languageNames: {
    vscode: 'VSCode 기본값',
    en: '영어',
    es: '스페인어',
    it: '이탈리아어',
    'zh-cn': '중국어 간체',
    'zh-tw': '중국어 번체',
    fr: '프랑스어',
    de: '독일어',
    ja: '일본어',
    ko: '한국어',
    ru: '러시아어',
    'pt-br': '포르투갈어(브라질)',
    tr: '터키어',
    pl: '폴란드어',
    cs: '체코어',
    hu: '헝가리어',
  },
  common: {
    add: '추가',
    cancel: '취소',
    close: '닫기',
    command: '명령',
    copy: '복사',
    default: '기본값',
    disabled: '비활성화됨',
    enabled: '활성화됨',
    exportSettings: '설정 내보내기',
    importSettings: '설정 가져오기',
    name: '이름',
    none: '없음',
    remove: '제거',
    save: '저장',
    select: '선택',
  },
  deviceManager: {
    title: '임베디드 장치 로거 v{version}',
    panelTitle: '임베디드 장치 관리자',
    intro: '장치와 기본 구성을 관리합니다.',
    removeStoredPasswords: '비밀번호 제거',
    editJson: 'JSON에서 편집',
    viewConfigurationExample: '구성 보기',
    saveChanges: '자주 묻는 질문',
    defaults: '기본 사항',
    defaultsDescription:
      '모든 장치에 대한 기본 값. 각 장치는 당신이 원하는 경우에 장치 테이블에서 그것을 바꿀 수 있습니다.',
    enableSshTerminal: '사용 가능한 SSH 터미널',
    enableSftpExplorer: 'SFTP 탐색기 사용',
    enableExternalWebBrowser: '외부 웹 브라우저 사용',
    enableEmbeddedWebBrowser: 'Enable Embedded 웹 브라우저',
    enableDevicePing: 'Enable 장치 ping',
    language: '확장 언어',
    port: '항구',
    logCommand: '로그 명령',
    maxLinesPerTab: '탭 당 최대 선',
    pingIntervalSeconds: 'Ping 간격 (둘째로)',
    pingIntervalPlaceholder: '수동 ping만을 위한 공백을 남겨두십시오',
    sshCommands: 'SSH 명령',
    groups: '그룹',
    groupsDescription: '임베디드 기기 보기에서 장치를 구성하는 옵션 그룹 정의.',
    addGroup: '그룹 추가',
    devices: '제품정보',
    devicesDescription: '줄을 추가하거나 제거 한 다음 필드 인라인을 편집합니다.',
    addDevice: '관련 제품',
    moveSelectedDevicesUp: '목록에서 선택된 장치를 이동',
    moveSelectedDevicesDown: '목록에서 선택한 장치를 이동',
    resetPassword: '비밀번호 재설정',
    removeStoredPasswordsForSelectedDevices:
      '저장된 암호를 제거하고 선택한 장치에 대한 passphrases',
    columnId: '사이트맵',
    columnGroup: '그룹',
    columnColor: '색깔: 백색',
    columnHost: '(주)',
    columnUser: '사용자 이름',
    columnHostFingerprint: '호스트 지문',
    columnSecondaryHost: '두 번째 호스트',
    columnSecondaryFingerprint: '두 번째 지문',
    columnSshTerminal: 'SSH 터미널',
    columnSftp: '사이트맵',
    columnSftpPresetsRemote: 'SFTP 프리셋 (레모드)',
    columnSftpPresetsLocal: 'SFTP 사전 설정 (현지)',
    columnExternalWebBrowser: '외부 웹 브라우저',
    columnEmbeddedWebBrowser: '웹 브라우저',
    columnWebUrl: '웹 URL',
    columnPrivateKeyPath: '개인 키 경로',
    columnPrivateKeyPassphrase: '개인 키 passphrase',
    columnPasswordWriteOnly: '비밀번호 (만 작성)',
    columnShowDefaultSshCommands: '기본 SSH 명령 표시',
    columnBastionHost: 'Bastion 호스트',
    columnBastionPort: 'Bastion 항구',
    columnBastionUser: 'Bastion 사용자',
    columnBastionFingerprint: 'Bastion 지문',
    columnBastionKeyPath: 'Bastion 키 경로',
    columnBastionKeyPassphrase: '분지 열쇠 passphrase',
    columnBastionPasswordWriteOnly: 'Bastion 암호 (만 쓰기)',
    groupNamePlaceholder: '그룹 이름',
    editScript: '편집 스크립트',
    editScriptFor: '{name}에 대한 스크립트 편집',
    sshCommandFallback: 'SSH 명령',
    scriptDescription: '/tmp로 복사한 스크립트를 작성하고 실행합니다.',
    sshCommandScriptEditor: 'SSH 명령 스크립트 편집기',
    commandNamesEmojiHelp: 'https://emojidb.org/에서 명령 이름 지원 이모티콘',
    openSshPanel: 'SSH를 여십시오 제품정보',
    rerunOnReconnection: '재연결에 다시 실행',
    copyAndRunScript: '복사 및 실행 Script',
    addCommand: '명령 추가',
    openCommandInSshPanel: 'SSH 패널에서 이 명령을 엽니다',
    openNamedCommandInSshPanel: 'SSH 패널에서 {name}를 엽니 다',
    rerunCommandAfterReconnect: 'SSH 패널 재연결 후 이 명령을 다시 실행',
    rerunNamedCommandOnReconnect: '재연결에 재 실행 {name}',
    copyScriptToTmp: '/tmp에 스크립트를 복사하고 명령 후 실행',
    copyAndRunScriptFor: '{name}에 대한 복사 및 실행 스크립트',
    removeCommand: '명령 제거',
    dragToResize: '크기 조정',
    selectDeviceRow: '선택 장치 행',
    removedSelectedDevice: '선택된 장치를 제거.',
    removedSelectedDevices: '{count} 선택된 장치 제거.',
    saving: '저장...',
    openingSettingsJson: '오픈 settings.json ...',
    removingStoredPasswords: '저장된 암호 제거 ...',
    exportingSettings: '수출 설정 ...',
    importingSettings: '설정 가져 오기 ...',
    setSelectedDeviceIdBeforeReset:
      '저장된 암호를 다시 놓기 전에 적어도 1개의 선택된 장치 ID를 설치하십시오.',
    removingStoredPasswordForDevice: '{id}에 저장된 암호 제거 ...',
    removingStoredPasswordsForDevices: '{count}의 저장된 암호 제거 선택된 장치...',
    configurationExample: '설정 예',
    configurationExampleDescription: 'settings.json로 이 기본값을 복사하고 붙여넣으십시오.',
    copiedConfigurationExample: 'Copied 구성 예.',
    failedToCopyConfigurationExample: '구성 예제 복사 실패.',
    savedSettings: '저장된 설정.',
    failedToSaveSettings: '설정 저장 실패.',
    importedSettingsApply: '수입된 설정. 그들을 검토하고 저장 변경을 클릭하여 적용하십시오.',
    failedToImportSettings: '설정 가져오기 실패.',
    exportSettingsSaveLabel: '수출 설정',
    exportCanceled: '수출 취소.',
    exportedSettingsTo: '{path}로 설정 내보내기.',
    failedToExportSettings: 'Failed to export settings: {message}',
    importSettingsOpenLabel: '가져오기 설정',
    importCanceled: '수입 취소.',
    importedSettingsFrom: '{path}에서 가져온 설정. 리뷰 및 클릭 Save changes to apply them.',
    failedToImportSettingsWithMessage: 'Failed to import settings: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      '저장된 설정. 창 또는 확장 호스트를 다시로드하면 임베디드 웹 브라우저 기본값을 persist로 다시 저장합니다.',
    reloadToPersistNewDefaultSettings:
      '설정이 저장되었습니다. 새로 추가된 기본 설정을 유지하려면 창 또는 확장 호스트를 다시 로드한 다음 다시 저장하세요.',
  },
  sidebar: {
    title: '임베디드 Logger 장치',
    copyUrl: '복사 URL',
    copyName: '복사 이름',
    pingInProgress: '진행 중',
    pingReachable: '공급 능력',
    pingUnreachable: '불변의 것',
    openLogs: '공지사항',
    openLogsFor: '{name}용 로그 열기',
    openSshTerminal: 'SSH를 여십시오 기타 제품',
    openSshTerminalFor: '{name}의 SSH 터미널 세션을 엽니다',
    openSftpExplorer: 'SFTP를 여십시오 회사 소개',
    browseAndTransferFilesFor: '{name}에 대한 검색 및 전송 파일',
    openExternalWebBrowser: '외부 웹 브라우저',
    openExternalWebBrowserFor: '외부 브라우저에서 {name}를 위한 형성된 웹 URL를 엽니다',
    openEmbeddedWebBrowser: 'Open Embedded 웹 브라우저',
    openEmbeddedWebBrowserFor: 'VS Code의 {name}에 대한 구성 웹 URL를 엽니 다',
    copyScriptCommandTitle: '/tmp, chmod 777에 스크립트를 복사하고 실행하십시오',
    noDevicesConfigured: '설정된 장치 없음. 설정에서 "embeddedLogger.devices"를 업데이트하십시오.',
    deviceNameLabel: '장치 이름',
    deviceUrlLabel: '장치 URL',
    copiedToClipboard: '{label} 클립 보드에 복사.',
  },
  deviceTree: {
    noDevicesConfigured: '설정된 장치 없음. 설정에서 "embeddedLogger.devices"를 업데이트하십시오.',
    openSettingsToConfigure: '임베디드 장치를 구성하는 설정 열기.',
    openSettings: '설정 열기',
    openDeviceLogs: '장치 로그',
    groupTooltip: '{name} 그룹',
  },
  logPanel: {
    logsTitle: '{name} Logs',
    minLevel: '분 수준',
    textFilter: '텍스트 필터',
    filterSubstring: '필터 substring',
    filteringPresets: '필터링 Presets',
    filterPresets: '필터 프리셋',
    savePreset: '저장 preset',
    deletePreset: '사전 설정',
    exportLogs: '수출 통',
    editLogFile: '로그 파일',
    refreshLogFile: '새로 고침 파일',
    startAutoSave: '자동 저장 시작',
    stopAutoSave: '자동 저장',
    clearLogs: '비밀번호',
    highlight: '높은 빛',
    wordWrap: '워드랩',
    autoScroll: '자동 회로',
    autoReconnect: '자동 연결',
    toggleState: '{label} ({state})',
    toggleOn: '으로',
    toggleOff: '뚱 베어',
    find: '제품정보',
    findInLogs: '로그에서 찾기 (Ctrl/Cmd+F)',
    clearSearch: '자주 묻는 질문',
    previousMatch: '이전 경기',
    nextMatch: '다음 경기',
    prev: '이름 *',
    next: '이름 *',
    reconnect: '연결하기',
    disconnect: '연결하기',
    highlights: '주요 특징',
    addHighlight: '더 보기',
    removeAllHighlights: '모든 제품',
    highlightKeywords: 'Highlight 키워드',
    lineLimitLive: '구성 표시 줄 제한 도달. 이전 라인은 더 새로운 항목으로 대체됩니다.',
    lineLimitOffline: '구성 표시 줄 제한 도달. 이전 수입 라인은이보기에서 숨겨졌습니다.',
    upToTenHighlights: '최대 10개의 키로 강조할 수 있습니다.',
    keyToHighlight: '키 강조',
    removeHighlight: '자주 묻는 질문',
    noPreset: '(전 세트 없음)',
    filterPresetNamed: '여과기 미리 설치: {name}',
    connectedStreaming: '연결. 스트리밍 로그 ...',
    bookmarkLabel: '북마크 라벨',
    enterBookmarkLabel: 'Bookmark 상표를 입력하십시오',
    addBookmark: '책갈피',
    editBookmarkLabel: '책갈피 라벨',
    removeBookmark: '책갈피를 제거',
    removeAllBookmarks: '모든 책갈피 제거',
    goToNextBookmark: '본문 바로가기',
    goToPreviousBookmark: '본문 바로가기',
    clearStatusMessage: '취소 상태 메시지',
    connectionClosed: '연결 폐쇄.',
    retryingInSeconds: '{message} Retrying in {seconds} seconds...',
    reconnecting: '연결 ...',
    disconnecting: '연결 ...',
    hostKeyFailedDetails:
      '호스트 키 검증 실패. 예상 {expected} 하지만 수신 {received}. 재연결에 지문을 업데이트합니다.',
    hostKeyFailed: '호스트 키 검증 실패. 재연결하기 전에 저장된 지문을 업데이트하십시오.',
    sessionClosed: '세션 폐쇄.',
    sshSessionClosedOn: '--- SSH 세션은 {timestamp}에 닫힙니다',
    dateAtTime: '{date}에서 {time}',
    autoSavingTo: '자동차 절약',
    autoSaveEnabled: '자동 저장 가능.',
    autoSaveFailed: '자동 득점방해 실패.',
    waitingForPassword: '암호를 입력 할 수있는 사용자를위한 대기 ..',
  },
  extension: {
    missingHost: '장치 "{name}"는 호스트가 누락됩니다.',
    missingUsername: '장치 "{name}"는 사용자 이름을 누락.',
    invalidPort: '장치 "{name}"는 잘못된 포트가 있습니다.',
    credentialsMigrationWarning:
      'Credentials는 Secret Storage로 마이그레이션되었지만, "password" 또는 "privateKeyPassphrase" 필드는 제거 할 수 없습니다. 설정에서 embeddedLogger.devices에서 삭제하십시오.',
    sftpPresetsMigrationFailed:
      'SFTP를 embeddedLogger.devices. Existing presets로 마이그레이션하는 실패는 연장 저장에서 남아 있습니다.',
    noHostFound: '선택된 장치에 대한 호스트가 없습니다.',
    webUrlMustStart: '웹 브라우저 URL는 http:// 또는 https://.로 시작해야 합니다',
    invalidWebUrl: '{name}에 대한 잘못된 웹 URL : {message}',
    deviceNotFound: '찾을 수 없습니다. embeddedLogger.devices.를 확인하십시오',
    workspaceTrustDeviceResources: 'Workspace 신뢰는 장치 리소스를 열어야 합니다.',
    workspaceTrustConnect: 'Workspace 신뢰는 장치에 연결하기 전에 필요합니다.',
    embeddedBrowserUnavailable: 'VS Code 임베디드 브라우저 지원은 사용할 수 없습니다.',
    failedToOpenUri: '오픈 실패 {uri}: {message}',
    sshCommandNoControlCharacters: 'SSH 명령은 제어 문자 또는 새로운 줄을 포함하지 않아야합니다.',
    runningCommandOnDevice: '{device}에서 "{command}" 실행',
    commandFinishedOnDevice: '{device}에서 완료된 명령 "{command}".',
    noDevicesConfigured: '설정된 장치 없음. embeddedLogger.devices.를 확인하십시오',
    selectDeviceForSftp: 'SFTP 탐험가를 열려면 장치를 선택하십시오',
    selectDeviceForExternalBrowser: '외부 웹 브라우저에서 열린 장치 선택',
    selectDeviceForEmbeddedBrowser: '임베디드 웹 브라우저에서 장치를 선택',
    storedPasswordsRemovedFor: '저장된 암호와 passphrases는 {device}를 위해 제거되었습니다.',
    noDevicesToClearPasswords: '비밀번호로 설정된 장치가 없습니다.',
    storedPasswordsRemoved: '암호를 저장하고 Passphrases는 형성된 장치를 위해 제거되었습니다.',
    openLogFile: '로그 파일 열기',
    failedToReadLogFile: '로그 파일을 읽는 실패: {message}',
    localPanelSuffix: '한국어',
    noDeviceInfo: '공급되는 장치 정보 없음.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: '장치 없이 로그 세션을 만들 수 없습니다.',
    loadedLines: '적재된 {count} 선.',
    presetSaved: '{target}에 저장된 "{name}"를 미리 설치하십시오.',
    presetRemoved: '미리 설치 "{name}" {target}에 대한 제거.',
    exportLogsSaveLabel: '수출 통',
    exportedLines: '{target}의 {count} 라인 수출.',
    failedToExportLogs: 'Failed to export logs: {message}',
    failedToExportLogsFallback: '수출 로그에 실패.',
    editOnlyImported: '편집은 수입된 로그 파일에서만 가능합니다.',
    failedToOpenLogFile: '로그 파일을 열 실패: {message}',
    failedToOpenLogFileFallback: '로그 파일을 엽니다.',
    refreshOnlyImported: '새로 고침은 수입된 로그 파일에서만 가능합니다.',
    failedToReadLogFile: '로그 파일을 읽는 실패: {message}',
    failedToReadLogFileFallback: '로그 파일을 읽는 실패.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: '세션 폐쇄.',
    disconnected: '연결.',
    reconnecting: '연결 ...',
    failedToReconnect: '연결 실패.',
    autoSaveDialogTitle: '자동 저장 SSH 산출에 로그 파일을 선택하십시오',
    allFiles: '모든 파일',
    autoSaveCancelled: '자동 저장 취소.',
    autoSaveFailed: '자동 득점방해: {message}',
    autoSaveFailedFallback: '자동 득점방해 실패.',
    hostKeyVerificationFailed:
      '호스트 키 검증은 {target}에 실패했습니다. 예상 {expected} 하지만 수신 {received}. 설정에 지문을 다시 연결하십시오.',
    sshSessionClosedOn: '--- SSH 세션은 {timestamp}에 닫힙니다',
  },
};
