/* eslint-disable spellcheck/spell-checker */
import type { en } from './en';

export const pl: typeof en = {
  languageId: 'pl',
  htmlLang: 'pl',
  languageNames: {
    vscode: 'Domyślny VSCode',
    en: 'Angielski',
    es: 'Hiszpański',
    it: 'Włoski',
    'zh-cn': 'Chiński uproszczony',
    'zh-tw': 'Chiński tradycyjny',
    fr: 'Francuski',
    de: 'Niemiecki',
    ja: 'Japoński',
    ko: 'Koreański',
    ru: 'Rosyjski',
    'pt-br': 'Portugalski (Brazylia)',
    tr: 'Turecki',
    pl: 'Polski',
    cs: 'Czeski',
    hu: 'Węgierski',
  },
  common: {
    add: 'Dodaj',
    cancel: 'Anuluj',
    close: 'Zamknij',
    command: 'Polecenie',
    copy: 'Kopiuj',
    default: 'Domyślne',
    disabled: 'Wyłączone',
    enabled: 'Włączone',
    exportSettings: 'Eksportuj ustawienia',
    importSettings: 'Importuj ustawienia',
    name: 'Nazwa',
    none: 'Brak',
    remove: 'Usuń',
    save: 'Zapisz',
    select: 'Wybierz',
  },
  deviceManager: {
    title: 'Wbudowane urządzenie Logger v{version}',
    panelTitle: 'Menedżer urządzeń wbudowanych',
    intro: 'Zarządzaj urządzeniami i konfiguracją domyślną.',
    removeStoredPasswords: 'Usuń zapisane hasła',
    editJson: 'Edycja w JSON',
    viewConfigurationExample: 'Wyświetl przykład konfiguracji',
    saveChanges: 'Zapisz zmiany',
    defaults: 'Domyślne',
    defaultsDescription:
      'Domyślne wartości dla wszystkich urządzeń. Każde urządzenie może zmienić go w tabeli urządzeń, jeśli jest to wymagane.',
    enableSshTerminal: 'Włącz terminal SSH',
    enableSftpExplorer: 'Włącz odkrywacz SFTP',
    enableExternalWebBrowser: 'Włącz zewnętrzną przeglądarkę internetową',
    enableEmbeddedWebBrowser: 'Włącz wbudowaną przeglądarkę internetową',
    enableDevicePing: 'Włącz ping urządzenia',
    language: 'Język rozszerzenia',
    port: 'Port',
    logCommand: 'Polecenie dziennika',
    maxLinesPerTab: 'Maksymalne linie na zakładkę',
    pingIntervalSeconds: 'Przedział ping (sekundy)',
    pingIntervalPlaceholder: 'Pozostawić puste tylko dla ręcznego ping',
    sshCommands: 'Polecenia SSH',
    groups: 'Grupy',
    groupsDescription:
      'Zdefiniuj grupy opcjonalne do organizacji urządzeń w widoku urządzeń wbudowanych.',
    addGroup: 'Dodaj grupę',
    devices: 'Urządzenia',
    devicesDescription: 'Dodaj lub usuń wiersze, a następnie edytuj pola w linii.',
    addDevice: 'Dodaj urządzenie',
    moveSelectedDevicesUp: 'Przenieś wybrane urządzenia na listę',
    moveSelectedDevicesDown: 'Przenieś wybrane urządzenia w dół listy',
    resetPassword: 'Zmień hasło',
    removeStoredPasswordsForSelectedDevices: 'Usuń zapisane hasła i hasła dla wybranych urządzeń',
    columnId: 'ID',
    columnGroup: 'Grupa',
    columnColor: 'Kolor',
    columnHost: 'Host',
    columnUser: 'Użytkownik',
    columnHostFingerprint: 'Odcisk palca hosta',
    columnSecondaryHost: 'Zastępca gospodarza',
    columnSecondaryFingerprint: 'Drugi odcisk palca',
    columnSshTerminal: 'Terminal SSH',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'Ustawienia SFTP (zdalne)',
    columnSftpPresetsLocal: 'Presety SFTP (lokalne)',
    columnExternalWebBrowser: 'Zewnętrzny przeglądarka internetowa',
    columnEmbeddedWebBrowser: 'Wbudowana przeglądarka internetowa',
    columnWebUrl: 'Web URL',
    columnPrivateKeyPath: 'Prywatna ścieżka klucza',
    columnPrivateKeyPassphrase: 'Prywatny klucz passphrase',
    columnPasswordWriteOnly: 'Hasło (tylko zapis)',
    columnShowDefaultSshCommands: 'Pokaż domyślne polecenia SSH',
    columnBastionHost: 'Host bastionowy',
    columnBastionPort: 'Bastion port',
    columnBastionUser: 'Użytkownik bastionu',
    columnBastionFingerprint: 'Odcisk bastionu',
    columnBastionKeyPath: 'Ścieżka klucza bastionu',
    columnBastionKeyPassphrase: 'Hasło klucza bastionowego',
    columnBastionPasswordWriteOnly: 'Hasło bastionowe (tylko zapis)',
    groupNamePlaceholder: 'Nazwa grupy',
    editScript: 'Edytuj skrypt',
    editScriptFor: 'Edytuj skrypt dla {name}',
    sshCommandFallback: 'Polecenie SSH',
    scriptDescription: 'Napisz skrypt, który zostanie skopiowany do /tmp i wykonany.',
    sshCommandScriptEditor: 'Edytor skryptów poleceń SSH',
    commandNamesEmojiHelp: 'Nazwy poleceń obsługują emojis z https://emojidb.org/',
    openSshPanel: 'Otwórz panel SSH',
    rerunOnReconnection: 'Uruchom ponownie przy ponownym połączeniu',
    copyAndRunScript: 'Kopiuj i uruchom skrypt',
    addCommand: 'Dodaj polecenie',
    openCommandInSshPanel: 'Otwórz to polecenie w panelu SSH',
    openNamedCommandInSshPanel: 'Otwórz {name} w panelu SSH',
    rerunCommandAfterReconnect: 'Uruchom ponownie to polecenie po ponownym połączeniu panelu SSH',
    rerunNamedCommandOnReconnect: 'Uruchom ponownie {name} podczas ponownego połączenia',
    copyScriptToTmp: 'Skopiuj skrypt do /tmp i uruchom go po poleceniu',
    copyAndRunScriptFor: 'Skopiuj i uruchom skrypt dla {name}',
    removeCommand: 'Usuń polecenie',
    dragToResize: 'Przeciągnij do zmiany rozmiaru',
    selectDeviceRow: 'Wybierz wiersz urządzenia',
    removedSelectedDevice: 'Usunięto wybrane urządzenie.',
    removedSelectedDevices: 'Usunięto wybrane urządzenia {count}.',
    saving: 'Zapisywanie...',
    openingSettingsJson: 'Otwarcie settings.json...',
    removingStoredPasswords: 'Usuwanie zapisanych haseł...',
    exportingSettings: 'Ustawienia eksportu...',
    importingSettings: 'Importowanie ustawień...',
    setSelectedDeviceIdBeforeReset:
      'Ustaw co najmniej jedno wybrane urządzenie ID przed resetowaniem zapisanego hasła.',
    removingStoredPasswordForDevice: 'Usuwanie zapisanego hasła dla {id}...',
    removingStoredPasswordsForDevices:
      'Usuwanie zapisanych haseł dla wybranych urządzeń {count}...',
    configurationExample: 'Przykład konfiguracji',
    configurationExampleDescription:
      'Kopiuj i wklej te wartości domyślne do swojego settings.json.',
    copiedConfigurationExample: 'Skopiowany przykład konfiguracji.',
    failedToCopyConfigurationExample: 'Nie udało się skopiować przykładu konfiguracji.',
    savedSettings: 'Zapisane ustawienia.',
    failedToSaveSettings: 'Nie udało się zapisać ustawień.',
    importedSettingsApply:
      'Importowane ustawienia. Sprawdź je i kliknij Zapisz zmiany, aby je zastosować.',
    failedToImportSettings: 'Nie udało się zaimportować ustawień.',
    exportSettingsSaveLabel: 'Ustawienia eksportu',
    exportCanceled: 'Eksport odwołany.',
    exportedSettingsTo: 'Eksportowane ustawienia na {path}.',
    failedToExportSettings: 'Ustawienia eksportu nie powiodły się: {message}',
    importSettingsOpenLabel: 'Importuj ustawienia',
    importCanceled: 'Import odwołany.',
    importedSettingsFrom:
      'Importowane ustawienia z {path}. Przegląd i kliknij Zapisz zmiany, aby je zastosować.',
    failedToImportSettingsWithMessage: 'Nie udało się zaimportować ustawień: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      'Zapisane ustawienia. Wczytaj ponownie okno lub rozszerzenie komputera, a następnie zapisz ponownie, aby utrzymać domyślną przeglądarkę WWW.',
    reloadToPersistNewDefaultSettings:
      'Ustawienia zapisane. Załaduj ponownie okno lub host rozszerzenia, a następnie zapisz ponownie, aby utrwalić nowo dodane ustawienia domyślne.',
  },
  sidebar: {
    title: 'Wbudowane urządzenia rejestrujące',
    copyUrl: 'Kopiuj URL',
    copyName: 'Kopiuj nazwę',
    pingInProgress: 'Ping w toku',
    pingReachable: 'Ping osiągalny',
    pingUnreachable: 'Ping nieosiągalny',
    openLogs: 'Otwórz logi',
    openLogsFor: 'Logi otwarte dla {name}',
    openSshTerminal: 'Otwórz terminal SSH',
    openSshTerminalFor: 'Otwórz sesję terminala SSH dla {name}',
    openSftpExplorer: 'Otwórz SFTP Explorer',
    browseAndTransferFilesFor: 'Przeglądaj i przenoś pliki dla {name}',
    openExternalWebBrowser: 'Otwórz zewnętrzną przeglądarkę WWW',
    openExternalWebBrowserFor:
      'Otwórz skonfigurowaną sieć URL dla {name} w zewnętrznej przeglądarce',
    openEmbeddedWebBrowser: 'Otwórz wbudowaną przeglądarkę internetową',
    openEmbeddedWebBrowserFor: 'Otwórz skonfigurowaną sieć URL dla {name} w VS Code',
    copyScriptCommandTitle: 'Skopiuj skrypt do /tmp, chmod 777 i uruchom go',
    noDevicesConfigured:
      'Brak skonfigurowanych urządzeń. Aktualizuj "embeddedLogger.devices" w ustawieniach.',
    deviceNameLabel: 'Nazwa urządzenia',
    deviceUrlLabel: 'Urządzenie URL',
    copiedToClipboard: '{label} skopiowany do schowka.',
  },
  deviceTree: {
    noDevicesConfigured:
      'Brak skonfigurowanych urządzeń. Aktualizuj "embeddedLogger.devices" w ustawieniach.',
    openSettingsToConfigure: 'Otwórz ustawienia do konfiguracji wbudowanych urządzeń.',
    openSettings: 'Otwórz ustawienia',
    openDeviceLogs: 'Otwórz logi urządzeń',
    groupTooltip: 'Grupa {name}',
  },
  logPanel: {
    logsTitle: '{name} Logs',
    minLevel: 'Min Poziom',
    textFilter: 'Filtr tekstu',
    filterSubstring: 'Podciąg filtrujący',
    filteringPresets: 'Recepty filtrujące',
    filterPresets: 'Ustawienia filtrów',
    savePreset: 'Zapisz wstępnie',
    deletePreset: 'Usuń zakładkę',
    exportLogs: 'Rejestry wywozu',
    editLogFile: 'Edytuj plik dziennika',
    refreshLogFile: 'Odśwież plik dziennika',
    startAutoSave: 'Uruchom auto- zapisz',
    stopAutoSave: 'Zatrzymaj auto- zapisz',
    clearLogs: 'Wyczyść dzienniki',
    highlight: 'Podświetlenie',
    wordWrap: 'Zawijanie wyrazów',
    autoScroll: 'Auto- przewijanie',
    autoReconnect: 'Auto- reconnect',
    toggleState: '{label} ({state})',
    toggleOn: 'dnia',
    toggleOff: 'wyłączony',
    find: 'Znajdź',
    findInLogs: 'Znajdź w dziennikach (Ctrl/Cmd+F)',
    clearSearch: 'Wyczyść wyszukiwanie',
    previousMatch: 'Poprzedni mecz',
    nextMatch: 'Następny mecz',
    prev: 'Poprzedni',
    next: 'Następny',
    reconnect: 'Rozpuszczenie',
    disconnect: 'Rozłącz',
    highlights: 'Najważniejsze',
    addHighlight: 'dodaj',
    removeAllHighlights: 'usunąć wszystkie',
    highlightKeywords: 'Podświetl słowa kluczowe',
    lineLimitLive:
      'Skonfigurowany limit linii wyświetlania osiągnięty. Starsze linie są zastępowane nowszymi wpisami.',
    lineLimitOffline:
      'Configured display line limit reached. Older imported lines were hidden from this view.',
    upToTenHighlights: 'Możesz podświetlić do 10 klawiszy.',
    keyToHighlight: 'Klucz do podkreślenia',
    removeHighlight: 'Usuń podświetlenie',
    noPreset: '(nie założono)',
    filterPresetNamed: 'Konfiguracja filtra: {name}',
    connectedStreaming: 'Połączony. Uruchamianie dzienników...',
    bookmarkLabel: 'Etykieta zakładki',
    enterBookmarkLabel: 'Wpisz etykietę zakładki',
    addBookmark: 'Dodaj zakładkę',
    editBookmarkLabel: 'Edytuj etykietę zakładki',
    removeBookmark: 'Usuń zakładkę',
    removeAllBookmarks: 'Usuń wszystkie zakładki',
    goToNextBookmark: 'Przejdź do następnej zakładki',
    goToPreviousBookmark: 'Przejdź do poprzedniej zakładki',
    clearStatusMessage: 'Wyczyść komunikat stanu',
    connectionClosed: 'Połączenie zamknięte.',
    retryingInSeconds: '{message} Retring in {seconds} seconds...',
    reconnecting: 'Rozpoczynam...',
    disconnecting: 'Odłączam...',
    hostKeyFailedDetails:
      'Weryfikacja klucza hosta nie powiodła się. Spodziewany {expected}, ale otrzymał {received}. Uaktualnij odcisk palca, aby ponownie się połączyć.',
    hostKeyFailed:
      'Weryfikacja klucza hosta nie powiodła się. Uaktualnij zapisany odcisk palca przed ponownym połączeniem.',
    sessionClosed: 'Sesja zamknięta.',
    sshSessionClosedOn: '--- SSH sesja zamknięta na {timestamp}',
    dateAtTime: '{date} w {time}',
    autoSavingTo: 'Autooszczędzanie do',
    autoSaveEnabled: 'Auto- zapisz włączone.',
    autoSaveFailed: 'Auto- save nie powiodło się.',
    waitingForPassword: 'Czekam, aż użytkownik wprowadzi hasło..',
  },
  extension: {
    missingHost: 'Urządzenie "{name}" brakuje hosta.',
    missingUsername: 'Urządzenie "{name}" nie posiada nazwy użytkownika.',
    invalidPort: 'Urządzenie "{name}" posiada nieprawidłowy port.',
    credentialsMigrationWarning:
      'Pola "hasło" lub "privateKeyPassphrase" nie mogły zostać usunięte. Proszę usunąć je z embeddedLogger.devices w ustawieniach.',
    sftpPresetsMigrationFailed:
      'Nie udało się przenieść presetów SFTP do presetów embeddedLogger.devices. Istniejące presety pozostają w pamięci rozszerzającej.',
    noHostFound: 'Nie znaleziono hosta dla wybranego urządzenia.',
    webUrlMustStart: 'Przeglądarka internetowa URL musi rozpocząć się od http: / / lub https://.',
    invalidWebUrl: 'Nieprawidłowa strona internetowa URL dla {name}: {message}',
    deviceNotFound: 'Urządzenie nie znaleziono. Sprawdź embeddedLogger.devices.',
    workspaceTrustDeviceResources:
      'Przed otwarciem zasobów urządzeń wymagane jest zaufanie do przestrzeni roboczej.',
    workspaceTrustConnect:
      'Przed podłączeniem do urządzeń wymagane jest zaufanie do przestrzeni roboczej.',
    embeddedBrowserUnavailable: 'Obsługa wbudowanej przeglądarki VS Code jest niedostępna.',
    failedToOpenUri: 'Nie udało się otworzyć {uri}: {message}',
    sshCommandNoControlCharacters:
      'Polecenie SSH nie może zawierać znaków sterujących ani nowych linii.',
    runningCommandOnDevice: 'Uruchomienie "{command}" na {device}',
    commandFinishedOnDevice: 'Polecenie "{command}" zakończone na {device}.',
    noDevicesConfigured: 'Brak skonfigurowanych urządzeń. Sprawdź embeddedLogger.devices.',
    selectDeviceForSftp: 'Wybierz urządzenie do otwarcia odkrywcy SFTP',
    selectDeviceForExternalBrowser:
      'Wybierz urządzenie do otwarcia w zewnętrznej przeglądarce internetowej',
    selectDeviceForEmbeddedBrowser:
      'Wybierz urządzenie do otwarcia w wbudowanej przeglądarce internetowej',
    storedPasswordsRemovedFor: 'Dla {device} usunięto przechowywane hasła i hasła.',
    noDevicesToClearPasswords: 'Brak urządzeń skonfigurowanych do usuwania haseł.',
    storedPasswordsRemoved: 'Dla skonfigurowanych urządzeń usunięto hasła i hasła.',
    openLogFile: 'Otwórz plik dziennika',
    failedToReadLogFile: 'Nie można odczytać pliku dziennika: {message}',
    localPanelSuffix: 'Lokalne',
    noDeviceInfo: 'Brak informacji o urządzeniu.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Nie można utworzyć sesji logowania bez urządzenia.',
    loadedLines: 'Załadowane linie {count}.',
    presetSaved: 'Preset "{name}" zapisany dla {target}.',
    presetRemoved: 'Preset "{name}" usunięty dla {target}.',
    exportLogsSaveLabel: 'Rejestry wywozu',
    exportedLines: 'Eksportowane linie {count} z {target}.',
    failedToExportLogs: 'Nie udało się wyeksportować dzienników: {message}',
    failedToExportLogsFallback: 'Nie udało się wyeksportować dzienników.',
    editOnlyImported: 'Edycja jest dostępna tylko dla zaimportowanych plików dziennika.',
    failedToOpenLogFile: 'Nie udało się otworzyć pliku dziennika: {message}',
    failedToOpenLogFileFallback: 'Nie udało się otworzyć pliku dziennika.',
    refreshOnlyImported: 'Odśwież jest dostępny tylko dla importowanych plików dziennika.',
    failedToReadLogFile: 'Nie można odczytać pliku dziennika: {message}',
    failedToReadLogFileFallback: 'Nie udało się odczytać pliku dziennika.',
    reloadedLinesFrom: 'Przeładowane linie {count} z {file}.',
    sessionClosed: 'Sesja zamknięta.',
    disconnected: 'Rozłączony.',
    reconnecting: 'Rozpoczynam...',
    failedToReconnect: 'Nie udało się ponownie połączyć.',
    autoSaveDialogTitle: 'Wybierz plik dziennika, aby automatycznie zapisać wyjście SSH',
    allFiles: 'Wszystkie pliki',
    autoSaveCancelled: 'Auto- zapisać anulowane.',
    autoSaveFailed: 'Auto- save nie powiodło się: {message}',
    autoSaveFailedFallback: 'Auto- save nie powiodło się.',
    hostKeyVerificationFailed:
      'Weryfikacja klucza hosta nie powiodła się dla {target}. Spodziewany {expected}, ale otrzymał {received}. Aktualizuj odcisk palca w ustawieniach, aby ponownie się połączyć.',
    sshSessionClosedOn: '--- SSH sesja zamknięta na {timestamp}',
  },
};
