/* eslint-disable spellcheck/spell-checker */
import type { en } from './en';

export const ptBr: typeof en = {
  languageId: 'pt-br',
  htmlLang: 'pt-BR',
  languageNames: {
    vscode: 'Padrão do VSCode',
    en: 'Inglês',
    es: 'Espanhol',
    it: 'Italiano',
    'zh-cn': 'Chinês simplificado',
    'zh-tw': 'Chinês tradicional',
    fr: 'Francês',
    de: 'Alemão',
    ja: 'Japonês',
    ko: 'Coreano',
    ru: 'Russo',
    'pt-br': 'Português (Brasil)',
    tr: 'Turco',
    pl: 'Polonês',
    cs: 'Tcheco',
    hu: 'Húngaro',
  },
  common: {
    add: 'Adicionar',
    cancel: 'Cancelar',
    close: 'Fechar',
    command: 'Comando',
    copy: 'Copiar',
    default: 'Padrão',
    disabled: 'Desativado',
    enabled: 'Ativado',
    exportSettings: 'Exportar configurações',
    importSettings: 'Importar configurações',
    name: 'Nome',
    none: 'Nenhum',
    remove: 'Remover',
    save: 'Salvar',
    select: 'Selecionar',
  },
  deviceManager: {
    title: 'Registrador de dispositivos incorporado v{version}',
    panelTitle: 'Gerenciador de dispositivos embarcados',
    intro: 'Gerencie dispositivos e a configuração padrão.',
    removeStoredPasswords: 'Remover senhas armazenadas',
    editJson: 'Editar em JSON',
    viewConfigurationExample: 'Veja o exemplo de configuração',
    saveChanges: 'Salvar mudanças',
    defaults: 'Padrões',
    defaultsDescription:
      'Valores padrão para todos os dispositivos. Cada dispositivo pode mudá-lo na mesa de dispositivos, se desejar.',
    enableSshTerminal: 'Activar o terminal SSH',
    enableSftpExplorer: 'Activar explorador SFTP',
    enableExternalWebBrowser: 'Activar navegador web externo',
    enableEmbeddedWebBrowser: 'Activar o navegador incorporado',
    enableDevicePing: 'Activar o ping do dispositivo',
    showBastionOptions: 'Mostrar opcoes de bastion',
    language: 'Idioma da extensão',
    port: 'Porto',
    logCommand: 'Comando de registro',
    maxLinesPerTab: 'Max linhas por aba',
    pingIntervalSeconds: 'Intervalo de ping (segundos)',
    pingIntervalPlaceholder: 'Deixe em branco apenas para ping manual',
    sshCommands: 'Comandos SSH',
    groups: 'Grupos',
    groupsDescription:
      'Defina grupos opcionais para organizar dispositivos na visão de dispositivos incorporados.',
    addGroup: 'Adicionar grupo',
    devices: 'Dispositivos',
    devicesDescription: 'Adicione ou remova linhas, depois edite os campos em linha.',
    addDevice: 'Adicionar dispositivo',
    moveSelectedDevicesUp: 'Mover os dispositivos selecionados para cima na lista',
    moveSelectedDevicesDown: 'Mover os dispositivos selecionados para baixo na lista',
    resetPassword: 'Reinicie a senha',
    removeStoredPasswordsForSelectedDevices:
      'Remover senhas e senhas armazenadas para dispositivos selecionados',
    columnId: 'ID',
    columnGroup: 'Grupo',
    columnColor: 'Cor',
    columnHost: 'Host',
    columnUser: 'Usuário',
    columnHostFingerprint: 'Impressões digitais do hospedeiro',
    columnSecondaryHost: 'Hospedeiro secundário',
    columnSecondaryFingerprint: 'Impressões digitais secundárias',
    columnSshTerminal: 'Terminal SSH',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'SFTP presets (remote)',
    columnSftpPresetsLocal: 'SFTP predefinições (local)',
    columnExternalWebBrowser: 'Navegador externo da Web',
    columnEmbeddedWebBrowser: 'Navegador da Web incorporado',
    columnWebUrl: 'Web URL',
    columnPrivateKeyPath: 'Caminho da chave privada',
    columnPrivateKeyPassphrase: 'Senha da chave privada',
    columnPasswordWriteOnly: 'Senha (somente escrita)',
    columnShowDefaultSshCommands: 'Mostrar os comandos padrão do SSH',
    columnBastionHost: 'Bastion host',
    columnBastionPort: 'Porto de Bastion',
    columnBastionUser: 'Bastion user',
    columnBastionFingerprint: 'Impressões digitais do Bastion',
    columnBastionKeyPath: 'Caminho da chave da bacia',
    columnBastionKeyPassphrase: 'Senha da chave de base',
    columnBastionPasswordWriteOnly: 'Senha da base (somente escrita)',
    groupNamePlaceholder: 'Nome do grupo',
    editScript: 'Editar script',
    editScriptFor: 'Editar script para {name}',
    sshCommandFallback: 'Comando SSH',
    scriptDescription: 'Escreva o script que será copiado para /tmp e executado.',
    sshCommandScriptEditor: 'Editor de scripts de comando SSH',
    commandNamesEmojiHelp: 'Nomes de comando suportam emojis de https://emojidb.org/',
    openSshPanel: 'Abra SSH Painel',
    rerunOnReconnection: 'Refazer a reconexão',
    copyAndRunScript: 'Copiar e executar o script',
    addCommand: 'Adicionar comando',
    openCommandInSshPanel: 'Abra este comando em um painel SSH',
    openNamedCommandInSshPanel: 'Abra {name} no painel SSH',
    rerunCommandAfterReconnect: 'Repita este comando após o painel SSH se reconectar',
    rerunNamedCommandOnReconnect: 'Refazer {name} na reconexão',
    copyScriptToTmp: 'Copie um script para /tmp e execute-o após o comando',
    copyAndRunScriptFor: 'Copiar e executar script para {name}',
    removeCommand: 'Remover comando',
    dragToResize: 'Arraste para redimensionar',
    selectDeviceRow: 'Selecione a linha do dispositivo',
    removedSelectedDevice: 'Dispositivo removido selecionado.',
    removedSelectedDevices: 'Dispositivos {count} removidos.',
    saving: 'Salvando...',
    openingSettingsJson: 'Abrindo settings.json...',
    removingStoredPasswords: 'Removendo senhas armazenadas...',
    exportingSettings: 'Exportando configurações...',
    importingSettings: 'Importando configurações...',
    setSelectedDeviceIdBeforeReset:
      'Defina pelo menos um dispositivo selecionado ID antes de reiniciar a senha armazenada.',
    removingStoredPasswordForDevice: 'Removendo senha armazenada para {id}...',
    removingStoredPasswordsForDevices:
      'Removendo senhas armazenadas para dispositivos selecionados pelo {count}...',
    configurationExample: 'Exemplo de configuração',
    configurationExampleDescription: 'Copie e cole esses padrões em seu settings.json.',
    copiedConfigurationExample: 'Exemplo de configuração copiada.',
    failedToCopyConfigurationExample: 'Não copiou o exemplo de configuração.',
    savedSettings: 'Configurações salvas.',
    failedToSaveSettings: 'Não consegui salvar as configurações.',
    importedSettingsApply:
      'Configurações importadas. Revise-os e clique em salvar mudanças para aplicá-los.',
    failedToImportSettings: 'Não foi possível importar as configurações.',
    exportSettingsSaveLabel: 'Exportar configurações',
    exportCanceled: 'Exportação cancelada.',
    exportedSettingsTo: 'Configurações exportadas para {path}.',
    failedToExportSettings: 'Falha na exportação de configurações: {message}',
    importSettingsOpenLabel: 'Importar configurações',
    importCanceled: 'Importação cancelada.',
    importedSettingsFrom:
      'Configurações importadas de {path}. Reveja e clique em Salvar mudanças para aplicá-las.',
    failedToImportSettingsWithMessage: 'Falha ao importar as configurações: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      'Configurações salvas. Recarregar a janela ou extensão host, em seguida, salvar novamente para persistir o navegador de Web Incorporado padrão.',
    reloadToPersistNewDefaultSettings:
      'Configurações salvas. Recarregue a janela ou o host da extensão e salve novamente para persistir as novas configurações padrão.',
  },
  sidebar: {
    title: 'Dispositivos de registro incorporados',
    copyUrl: 'Tradução e Sincronia:',
    copyName: 'Copiar Nome',
    pingInProgress: 'Ping em progresso',
    pingReachable: 'Ping alcançável',
    pingUnreachable: 'Ping inalcançável',
    openLogs: 'Abrir logs',
    openLogsFor: 'Registros abertos para {name}',
    openSshTerminal: 'Abra SSH Terminal',
    openSshTerminalFor: 'Abra uma sessão de terminal SSH para {name}',
    openSftpExplorer: 'Abra SFTP Explorador',
    browseAndTransferFilesFor: 'Navegue e transfira arquivos para {name}',
    openExternalWebBrowser: 'Abrir navegador externo da Web',
    openExternalWebBrowserFor: 'Abra a web configurada URL para {name} em um navegador externo',
    openEmbeddedWebBrowser: 'Abrir navegador incorporado',
    openEmbeddedWebBrowserFor: 'Abra a web configurada URL para {name} em VS Code',
    copyScriptCommandTitle: 'Copie o script para /tmp, chmod 777, e execute',
    noDevicesConfigured:
      'Nenhum dispositivo configurado. Atualizar "embeddedLogger.devices" em configurações.',
    deviceNameLabel: 'Nome do dispositivo',
    deviceUrlLabel: 'Dispositivo URL',
    copiedToClipboard: '{label} copiado para a prancheta.',
  },
  deviceTree: {
    noDevicesConfigured:
      'Nenhum dispositivo configurado. Atualizar "embeddedLogger.devices" em configurações.',
    openSettingsToConfigure: 'Abrir configurações para configurar dispositivos incorporados.',
    openSettings: 'Abrir configurações',
    openDeviceLogs: 'Abrir registros de dispositivos',
    groupTooltip: 'Grupo {name}',
  },
  logPanel: {
    logsTitle: '{name} Diários',
    minLevel: 'Nível Min',
    textFilter: 'Filtro de Texto',
    filterSubstring: 'Filtrar substring',
    filteringPresets: 'Filtrando predefinições',
    filterPresets: 'Predefinições do filtro',
    savePreset: 'Salvar predefinição',
    deletePreset: 'Apagar predefinição',
    exportLogs: 'Diários de exportação',
    editLogFile: 'Editar arquivo de registro',
    refreshLogFile: 'Atualizar arquivo de registro',
    startAutoSave: 'Comece a salvar automaticamente',
    stopAutoSave: 'Pare de salvar automaticamente',
    clearLogs: 'Limpar os registros',
    highlight: 'Destaque',
    wordWrap: 'Fim de linha',
    autoScroll: 'Rolagem automática',
    autoReconnect: 'Reconectar automaticamente',
    toggleState: '{label} ({state})',
    toggleOn: 'vamos',
    toggleOff: 'off',
    find: 'Encontrar',
    findInLogs: 'Encontre em logs (Ctrl/Cmd+F)',
    clearSearch: 'Limpar busca',
    previousMatch: 'Jogo anterior',
    nextMatch: 'Próxima partida',
    prev: 'Anterior',
    next: 'Próxima',
    reconnect: 'Reconectar',
    disconnect: 'Desconectar',
    highlights: 'Destaques',
    addHighlight: 'adicionar',
    removeAllHighlights: 'remova tudo',
    highlightKeywords: 'Realçar palavras-chave',
    lineLimitLive:
      'Limite de exibição configurado alcançado. Linhas antigas estão sendo substituídas por novas entradas.',
    lineLimitOffline:
      'Limite de exibição configurado alcançado. Linhas importadas antigas estavam escondidas desta vista.',
    upToTenHighlights: 'Você pode destacar até 10 chaves.',
    keyToHighlight: 'Chave para destacar',
    removeHighlight: 'Remover o realce',
    noPreset: '(sem predefinição)',
    filterPresetNamed: 'Predefinição do filtro: {name}',
    connectedStreaming: 'Conectado. Fluxo de registros...',
    bookmarkLabel: 'Marcador',
    enterBookmarkLabel: 'Digite o rótulo dos favoritos',
    addBookmark: 'Adicionar marcador',
    editBookmarkLabel: 'Editar rótulo de favoritos',
    removeBookmark: 'Remover marcador',
    removeAllBookmarks: 'Remova todos os favoritos',
    goToNextBookmark: 'Vá para o próximo marcador',
    goToPreviousBookmark: 'Vá para o marcador anterior',
    clearStatusMessage: 'Limpar mensagem de status',
    connectionClosed: 'Conexão fechada.',
    retryingInSeconds: '{message} Tentando novamente em segundos {seconds}...',
    reconnecting: 'Reconectando...',
    disconnecting: 'Desligando...',
    hostKeyFailedDetails:
      'Verificação da chave do host falhou. Esperava {expected} mas recebeu {received}. Atualize a impressão digital para reconectar.',
    hostKeyFailed:
      'Verificação da chave do host falhou. Atualizar a impressão digital antes de reconectar.',
    sessionClosed: 'Sessão encerrada.',
    sshSessionClosedOn: '--- SSH sessão fechada em {timestamp}',
    dateAtTime: '{date} em {time}',
    autoSavingTo: 'Salvamento automático para',
    autoSaveEnabled: 'Salvamento automático ativado.',
    autoSaveFailed: 'Salvamento automático falhou.',
    waitingForPassword: 'Esperando que o usuário digite a senha..',
  },
  extension: {
    missingHost: 'O dispositivo "{name}" está faltando um hospedeiro.',
    missingUsername: 'O dispositivo "{name}" está faltando um nome de usuário.',
    invalidPort: 'O dispositivo "{name}" tem uma porta inválida.',
    credentialsMigrationWarning:
      'Credenciais foram migrados para Secret Storage, mas os campos "senha" ou "privateKeyPassfrase" não puderam ser removidos. Por favor, apague-os de embeddedLogger.devices em suas configurações.',
    sftpPresetsMigrationFailed:
      'Falha em migrar as predefinições SFTP para embeddedLogger.devices. As predefinições existentes permanecem no armazenamento de extensão.',
    noHostFound: 'Nenhum hospedeiro encontrado para o dispositivo selecionado.',
    webUrlMustStart: 'URLs devem começar com http:// ou https://.',
    invalidWebUrl: 'URL inválido para {name}: {message}',
    deviceNotFound: 'Dispositivo não encontrado. Verifique embeddedLogger.devices.',
    workspaceTrustDeviceResources:
      'A confiança no espaço de trabalho é necessária antes de abrir os recursos do dispositivo.',
    workspaceTrustConnect:
      'A confiança no espaço de trabalho é necessária antes de se conectar aos dispositivos.',
    embeddedBrowserUnavailable: 'VS Code não está disponível.',
    failedToOpenUri: 'Failed to open {uri}: {message}',
    sshCommandNoControlCharacters:
      'O comando SSH não deve conter caracteres de controle ou novas linhas.',
    runningCommandOnDevice: 'Correndo "{command}" em {device}',
    commandFinishedOnDevice: 'O comando "{command}" terminou em {device}.',
    noDevicesConfigured: 'Nenhum dispositivo configurado. Verifique embeddedLogger.devices.',
    selectDeviceForSftp: 'Selecione um dispositivo para abrir o explorador SFTP',
    selectDeviceForExternalBrowser: 'Selecione um dispositivo para abrir no navegador externo',
    selectDeviceForEmbeddedBrowser: 'Selecione um dispositivo para abrir no navegador incorporado',
    storedPasswordsRemovedFor: 'Senhas e senhas armazenadas foram removidas para {device}.',
    noDevicesToClearPasswords: 'Nenhum dispositivo configurado para limpar senhas.',
    storedPasswordsRemoved:
      'Senhas e senhas armazenadas foram removidas para dispositivos configurados.',
    openLogFile: 'Abrir arquivo de log',
    failedToReadLogFile: 'Não foi possível ler o arquivo de registro {message}',
    localPanelSuffix: 'Local',
    noDeviceInfo: 'Nenhuma informação do dispositivo fornecida.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Não é possível criar uma sessão de registro sem um dispositivo.',
    loadedLines: 'Linhas {count} carregadas.',
    presetSaved: 'Predefinição "{name}" salvo para {target}.',
    presetRemoved: '"{name}" removido para {target}.',
    exportLogsSaveLabel: 'Diários de exportação',
    exportedLines: 'Linhas {count} exportadas de {target}.',
    failedToExportLogs: 'Falha na exportação de logs: {message}',
    failedToExportLogsFallback: 'Falha na exportação de logs.',
    editOnlyImported: 'Edit só está disponível para arquivos de log importados.',
    failedToOpenLogFile: 'Não foi possível abrir o arquivo de log: {message}',
    failedToOpenLogFileFallback: 'Não foi possível abrir o arquivo de registro.',
    refreshOnlyImported: 'Atualizar só está disponível para arquivos de log importados.',
    failedToReadLogFile: 'Não foi possível ler o arquivo de registro {message}',
    failedToReadLogFileFallback: 'Não consegui ler o arquivo de registro.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: 'Sessão encerrada.',
    disconnected: 'Desligado.',
    reconnecting: 'Reconectando...',
    failedToReconnect: 'Não conseguiu se reconectar.',
    autoSaveDialogTitle: 'Selecione o arquivo de registro para salvar automaticamente a saída SSH',
    allFiles: 'Todos os arquivos',
    autoSaveCancelled: 'Salvamento automático cancelado.',
    autoSaveFailed: 'Salvamento automático falhou: {message}',
    autoSaveFailedFallback: 'Salvamento automático falhou.',
    hostKeyVerificationFailed:
      'A verificação da chave do host falhou para {target}. Esperava {expected} mas recebeu {received}. Atualize as digitais para reconectar.',
    sshSessionClosedOn: '--- SSH sessão fechada em {timestamp}',
  },
};
