import type { en } from './en';

export const ru: typeof en = {
  languageId: 'ru',
  htmlLang: 'ru',
  languageNames: {
    vscode: 'По умолчанию VSCode',
    en: 'Английский',
    es: 'Испанский',
    it: 'Итальянский',
    'zh-cn': 'Упрощенный китайский',
    'zh-tw': 'Традиционный китайский',
    fr: 'Французский',
    de: 'Немецкий',
    ja: 'Японский',
    ko: 'Корейский',
    ru: 'Русский',
    'pt-br': 'Португальский (Бразилия)',
    tr: 'Турецкий',
    pl: 'Польский',
    cs: 'Чешский',
    hu: 'Венгерский',
  },
  common: {
    add: 'Добавить',
    cancel: 'Отмена',
    close: 'Закрыть',
    command: 'Команда',
    copy: 'Копировать',
    default: 'По умолчанию',
    disabled: 'Отключено',
    enabled: 'Включено',
    exportSettings: 'Экспорт настроек',
    importSettings: 'Импорт настроек',
    name: 'Имя',
    none: 'Нет',
    remove: 'Удалить',
    save: 'Сохранить',
    select: 'Выбрать',
  },
  deviceManager: {
    title: 'Встроенное устройство Logger v{version}',
    panelTitle: 'Диспетчер встроенных устройств',
    intro: 'Управление устройствами и конфигурацией по умолчанию.',
    removeStoredPasswords: 'Удалить сохраненные пароли',
    editJson: 'Редактировать в JSON',
    viewConfigurationExample: 'Пример конфигурации',
    saveChanges: 'Сохранить изменения',
    defaults: 'Недостатки',
    defaultsDescription:
      'Значения по умолчанию для всех устройств. При желании каждое устройство может изменить его в таблице устройств.',
    enableSshTerminal: 'Включить терминал SSH',
    enableSftpExplorer: 'Скачать SFTP Explorer',
    enableExternalWebBrowser: 'Включить внешний веб-браузер',
    enableEmbeddedWebBrowser: 'Включить встроенный веб-браузер',
    enableDevicePing: 'Включить устройство ping',
    language: 'Язык расширения',
    port: 'Порт',
    logCommand: 'Лог команды',
    maxLinesPerTab: 'Линии Макса на вкладку',
    pingIntervalSeconds: 'Пинг-интервал (секунды)',
    pingIntervalPlaceholder: 'Оставьте пустой только для ручного пинга',
    sshCommands: 'Команды SSH',
    groups: 'Группы',
    groupsDescription:
      'Определите дополнительные группы для организации устройств в представлении встраиваемых устройств.',
    addGroup: 'Добавить группу',
    devices: 'Устройства',
    devicesDescription: 'Добавить или удалить строки, затем редактировать поля inline.',
    addDevice: 'Добавить устройство',
    moveSelectedDevicesUp: 'Переместить выбранные устройства в список',
    moveSelectedDevicesDown: 'Переместить выбранные устройства в список',
    resetPassword: 'Сбросить пароль',
    removeStoredPasswordsForSelectedDevices:
      'Удалите сохраненные пароли и пароли для выбранных устройств',
    columnId: 'ID',
    columnGroup: 'Группа',
    columnColor: 'Цвет',
    columnHost: 'Ведущий',
    columnUser: 'Пользователь',
    columnHostFingerprint: 'Отпечаток пальца хозяина',
    columnSecondaryHost: 'Вторичный хост',
    columnSecondaryFingerprint: 'Вторичный отпечаток',
    columnSshTerminal: 'SSH терминал',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'SFTP Presets (удаленная версия)',
    columnSftpPresetsLocal: 'Пресеты SFTP (локальные)',
    columnExternalWebBrowser: 'Внешний веб-браузер',
    columnEmbeddedWebBrowser: 'Встроенный веб-браузер',
    columnWebUrl: 'Web URL',
    columnPrivateKeyPath: 'Частный ключ путь',
    columnPrivateKeyPassphrase: 'Частная ключевая фраза',
    columnPasswordWriteOnly: 'Пароль (только для записи)',
    columnShowDefaultSshCommands: 'Показать команды SSH по умолчанию',
    columnBastionHost: 'Бастион-хозяин',
    columnBastionPort: 'Порт Бастион',
    columnBastionUser: 'Пользователь Bastion',
    columnBastionFingerprint: 'Отпечаток пальца бастиона',
    columnBastionKeyPath: 'Ключевой путь бастиона',
    columnBastionKeyPassphrase: 'Ключевые фразы бастиона',
    columnBastionPasswordWriteOnly: 'Пароль Bastion (только для записи)',
    groupNamePlaceholder: 'Название группы',
    editScript: 'Редактировать сценарий',
    editScriptFor: 'Сценарий для {name}',
    sshCommandFallback: 'Команда SSH',
    scriptDescription: 'Напишите сценарий, который будет скопирован в /tmp и выполнен.',
    sshCommandScriptEditor: 'SSH командный скрипт редактор',
    commandNamesEmojiHelp: 'Имена команд поддерживают эмодзи от https://emojidb.org/',
    openSshPanel: 'Открыть SSH Группа',
    rerunOnReconnection: 'Повторное соединение',
    copyAndRunScript: 'Копировать и запускать сценарий',
    addCommand: 'Добавить команду',
    openCommandInSshPanel: 'Откройте эту команду в панели SSH',
    openNamedCommandInSshPanel: 'Открыть {name} в панели SSH',
    rerunCommandAfterReconnect: 'Перезапуск этой команды после пересоединения панели SSH',
    rerunNamedCommandOnReconnect: 'Перезапуск {name} при повторном подключении',
    copyScriptToTmp: 'Скопируйте сценарий в /tmp и запустите его после команды',
    copyAndRunScriptFor: 'Скопировать и запустить скрипт для {name}',
    removeCommand: 'Удалить команду',
    dragToResize: 'Перетаскивать для изменения размера',
    selectDeviceRow: 'Выберите строку',
    removedSelectedDevice: 'Снято выбранное устройство.',
    removedSelectedDevices: 'Удалены выбранные устройства {count}.',
    saving: 'Спасти...',
    openingSettingsJson: 'Открытие settings.json...',
    removingStoredPasswords: 'Удаление сохраненных паролей...',
    exportingSettings: 'Экспортные настройки...',
    importingSettings: 'Импортные настройки...',
    setSelectedDeviceIdBeforeReset:
      'Установите по меньшей мере одно выбранное устройство ID перед сбросом сохраненного пароля.',
    removingStoredPasswordForDevice: 'Удаление сохраненного пароля для {id}.',
    removingStoredPasswordsForDevices:
      'Удаление сохраненных паролей для выбранных устройств {count}.',
    configurationExample: 'Пример конфигурации',
    configurationExampleDescription: 'Скопируйте и вставьте эти дефолты в свой settings.json.',
    copiedConfigurationExample: 'Скопированный пример конфигурации.',
    failedToCopyConfigurationExample: 'Не удалось скопировать пример конфигурации.',
    savedSettings: 'Сохраненные настройки.',
    failedToSaveSettings: 'Не удалось сохранить настройки.',
    importedSettingsApply:
      'Импортные настройки. Просмотрите их и нажмите Сохранить изменения, чтобы применить их.',
    failedToImportSettings: 'Не удалось импортировать настройки.',
    exportSettingsSaveLabel: 'Экспортные настройки',
    exportCanceled: 'Экспорт отменен.',
    exportedSettingsTo: 'Экспортируем настройки в {path}.',
    failedToExportSettings: 'Failed to export settings: {message}',
    importSettingsOpenLabel: 'Условия импорта',
    importCanceled: 'Импорт отменен.',
    importedSettingsFrom:
      'Импортные настройки от {path}. Просмотрите и нажмите Сохранить изменения, чтобы применить их.',
    failedToImportSettingsWithMessage: 'Failed to import settings: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      'Сохраненные настройки. Перезагрузите окно или хост расширения, затем сохраните снова, чтобы сохранить встроенный веб-браузер по умолчанию.',
    reloadToPersistNewDefaultSettings:
      'Настройки сохранены. Перезагрузите окно или хост расширения, затем сохраните еще раз, чтобы закрепить новые настройки по умолчанию.',
  },
  sidebar: {
    title: 'Встроенные устройства Logger',
    copyUrl: 'Копия URL',
    copyName: 'Имя копия',
    pingInProgress: 'Пинг в процессе',
    pingReachable: 'Пинг достижимый',
    pingUnreachable: 'Пинг недосягаемый',
    openLogs: 'Открытые журналы',
    openLogsFor: 'Открытые журналы для {name}',
    openSshTerminal: 'Открыть SSH Терминал',
    openSshTerminalFor: 'Откройте терминал SSH для {name}',
    openSftpExplorer: 'Открыть SFTP исследователь',
    browseAndTransferFilesFor: 'Просмотр и передача файлов для {name}',
    openExternalWebBrowser: 'Открытый внешний веб-браузер',
    openExternalWebBrowserFor: 'Откройте настроенный веб URL для {name} во внешнем браузере',
    openEmbeddedWebBrowser: 'Открыть встроенный веб-браузер',
    openEmbeddedWebBrowserFor: 'Откройте настроенный веб URL для {name} в VS Code',
    copyScriptCommandTitle: 'Скопировать скрипт в /tmp, chmod 777 и запустить его',
    noDevicesConfigured:
      'Никаких приспособлений. Обновление «embeddedLogger.devices» в настройках.',
    deviceNameLabel: 'Имя устройства',
    deviceUrlLabel: 'Устройство URL',
    copiedToClipboard: '{label} скопирован в буфер обмена.',
  },
  deviceTree: {
    noDevicesConfigured:
      'Никаких приспособлений. Обновление «embeddedLogger.devices» в настройках.',
    openSettingsToConfigure: 'Откройте настройки для настройки встроенных устройств.',
    openSettings: 'Открытые настройки',
    openDeviceLogs: 'Открытые журналы устройств',
    groupTooltip: 'Группа {name}',
  },
  logPanel: {
    logsTitle: '{name} Logs',
    minLevel: 'Мин уровень',
    textFilter: 'Текстовый фильтр',
    filterSubstring: 'Фильтр подстроки',
    filteringPresets: 'Фильтрация предустановок',
    filterPresets: 'Предустановленные фильтры',
    savePreset: 'Сохранить preset',
    deletePreset: 'Удалить preset',
    exportLogs: 'Экспортные журналы',
    editLogFile: 'Редактировать файл log',
    refreshLogFile: 'Обновить файл log',
    startAutoSave: 'Начать автосохранение',
    stopAutoSave: 'Остановить автосохранение',
    clearLogs: 'Чистые журналы',
    highlight: 'Выделить',
    wordWrap: 'Завернуть слово',
    autoScroll: 'Автопрокрутка',
    autoReconnect: 'Автоподключение',
    toggleState: '{label} ({state})',
    toggleOn: 'на',
    toggleOff: 'выключать',
    find: 'Найти',
    findInLogs: 'Найти в журналах (Ctrl/Cmd+F)',
    clearSearch: 'Четкий поиск',
    previousMatch: 'Предыдущий матч',
    nextMatch: 'Следующий матч',
    prev: 'Прежний',
    next: 'Следующий',
    reconnect: 'Воссоединиться',
    disconnect: 'Отключить',
    highlights: 'Основные моменты',
    addHighlight: 'добавлять',
    removeAllHighlights: 'удалить все',
    highlightKeywords: 'Выделите ключевые слова',
    lineLimitLive:
      'Настроенный предел линии отображения достигнут. Старые линии заменяются новыми.',
    lineLimitOffline:
      'Настроенный предел линии отображения достигнут. С этой точки зрения были скрыты старые импортные линии.',
    upToTenHighlights: 'Можно выделить до 10 ключей.',
    keyToHighlight: 'Ключ к выделению',
    removeHighlight: 'Удалить Blight',
    noPreset: '(не предустановлено)',
    filterPresetNamed: 'Предустановленный фильтр: {name}',
    connectedStreaming: 'Подключен. Стриминговые бревна...',
    bookmarkLabel: 'Этикетка',
    enterBookmarkLabel: 'Введите ярлык Bookmark',
    addBookmark: 'Добавить закладку',
    editBookmarkLabel: 'Редактировать этикетку закладки',
    removeBookmark: 'Удалить закладку',
    removeAllBookmarks: 'Удалить все закладки',
    goToNextBookmark: 'Перейти к следующей закладке',
    goToPreviousBookmark: 'Перейти к предыдущей закладке',
    clearStatusMessage: 'Ясное сообщение о статусе',
    connectionClosed: 'Связь закрыта.',
    retryingInSeconds: '{message} Retrying in {seconds} seconds...',
    reconnecting: 'Воссоединение...',
    disconnecting: 'Отключение...',
    hostKeyFailedDetails:
      'Проверка ключа хоста провалилась. Ожидаемый {expected}, но получивший {received}. Обновите отпечаток пальца, чтобы восстановить соединение.',
    hostKeyFailed:
      'Проверка ключа хоста провалилась. Обновите сохраненный отпечаток пальца перед повторным подключением.',
    sessionClosed: 'Заседание закрыто.',
    sshSessionClosedOn: 'Сеанс SSH закрыт на {timestamp}',
    dateAtTime: '{date} в {time}',
    autoSavingTo: 'Автосбережение для',
    autoSaveEnabled: 'Автосохранение включено.',
    autoSaveFailed: 'Автосохранение провалилось.',
    waitingForPassword: 'В ожидании ввода пользователем пароля..',
  },
  extension: {
    missingHost: 'Устройства "{name}" отсутствует хост.',
    missingUsername: 'В устройстве «{name}» отсутствует имя пользователя.',
    invalidPort: 'Устройство «{name}» имеет недействительный порт.',
    credentialsMigrationWarning:
      'Полномочия были перенесены в Secret Storage, но поля «пароль» или «частная фраза» не могли быть удалены. Пожалуйста, удалите их из embeddedLogger.devices в настройках.',
    sftpPresetsMigrationFailed:
      'Не удалось перенести пресеты SFTP в существующие пресеты embeddedLogger.devices., которые остаются в хранилище расширений.',
    noHostFound: 'Хост не найден для выбранного устройства.',
    webUrlMustStart: 'Веб-браузер URL должен начинаться с http:// или https://.',
    invalidWebUrl: 'Недействительный веб URL для {name}: {message}',
    deviceNotFound: 'Устройство не найдено. Проверить embeddedLogger.devices.',
    workspaceTrustDeviceResources:
      'Доверие к рабочему пространству требуется перед открытием ресурсов устройства.',
    workspaceTrustConnect:
      'Доверие к рабочему пространству требуется перед подключением к устройствам.',
    embeddedBrowserUnavailable: 'Поддержка встроенного браузера VS Code недоступна.',
    failedToOpenUri: 'Не удалось открыть {uri}: {message}',
    sshCommandNoControlCharacters:
      'Команда SSH не должна содержать управляющих символов или новых строк.',
    runningCommandOnDevice: 'Запуск «{command}» на {device}',
    commandFinishedOnDevice: 'Командование «{command}» закончилось на {device}.',
    noDevicesConfigured: 'Никаких приспособлений. Проверить embeddedLogger.devices.',
    selectDeviceForSftp: 'Выберите устройство для открытия проводника SFTP',
    selectDeviceForExternalBrowser: 'Выберите устройство для открытия во внешнем веб-браузере',
    selectDeviceForEmbeddedBrowser: 'Выберите устройство для открытия во встроенном веб-браузере',
    storedPasswordsRemovedFor: 'Сохраненные пароли и пароли были удалены для {device}.',
    noDevicesToClearPasswords: 'Никаких устройств, настроенных для очистки паролей.',
    storedPasswordsRemoved: 'Сохраненные пароли и пароли были удалены для настроенных устройств.',
    openLogFile: 'Open log файл',
    failedToReadLogFile: 'Не удалось прочитать файл журнала: {message}',
    localPanelSuffix: 'Местный',
    noDeviceInfo: 'Информация об устройстве не предоставляется.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Невозможно создать лог-сессию без устройства.',
    loadedLines: 'Загруженные линии {count}.',
    presetSaved: 'Пресет «{name}» сохранен для {target}.',
    presetRemoved: 'Пресет "{name}" удален для {target}.',
    exportLogsSaveLabel: 'Экспортные журналы',
    exportedLines: 'Экспортировал линии {count} из {target}.',
    failedToExportLogs: 'Failed to export logs: {message}',
    failedToExportLogsFallback: 'Не удалось экспортировать бревна.',
    editOnlyImported: 'Редактирование доступно только для импортных файлов журналов.',
    failedToOpenLogFile: 'Не удалось открыть файл журнала: {message}',
    failedToOpenLogFileFallback: 'Не удалось открыть файл журнала.',
    refreshOnlyImported: 'Refresh доступен только для импортных файлов журналов.',
    failedToReadLogFile: 'Не удалось прочитать файл журнала: {message}',
    failedToReadLogFileFallback: 'Не удалось прочитать файл журнала.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: 'Заседание закрыто.',
    disconnected: 'Отключен.',
    reconnecting: 'Воссоединение...',
    failedToReconnect: 'Не удалось восстановить связь.',
    autoSaveDialogTitle: 'Выберите файл журнала для автоматического сохранения вывода SSH',
    allFiles: 'Все файлы',
    autoSaveCancelled: 'Автосохранение отменено.',
    autoSaveFailed: 'Автосохранение не удалось: {message}',
    autoSaveFailedFallback: 'Автосохранение провалилось.',
    hostKeyVerificationFailed:
      'Проверка ключа хоста не удалась для {target}. Ожидаемый {expected}, но получивший {received}. Обновите отпечаток пальца в настройках для повторного подключения.',
    sshSessionClosedOn: 'Сеанс SSH закрыт на {timestamp}',
  },
};
