/* eslint-disable spellcheck/spell-checker */
import type { en } from './en';

export const tr: typeof en = {
  languageId: 'tr',
  htmlLang: 'tr',
  languageNames: {
    vscode: 'VSCode varsayılanı',
    en: 'İngilizce',
    es: 'İspanyolca',
    it: 'İtalyanca',
    'zh-cn': 'Basitleştirilmiş Çince',
    'zh-tw': 'Geleneksel Çince',
    fr: 'Fransızca',
    de: 'Almanca',
    ja: 'Japonca',
    ko: 'Korece',
    ru: 'Rusça',
    'pt-br': 'Portekizce (Brezilya)',
    tr: 'Türkçe',
    pl: 'Lehçe',
    cs: 'Çekçe',
    hu: 'Macarca',
  },
  common: {
    add: 'Ekle',
    cancel: 'İptal',
    close: 'Kapat',
    command: 'Komut',
    copy: 'Kopyala',
    default: 'Varsayılan',
    disabled: 'Devre dışı',
    enabled: 'Etkin',
    exportSettings: 'Ayarları dışa aktar',
    importSettings: 'Ayarları içe aktar',
    name: 'Ad',
    none: 'Yok',
    remove: 'Kaldır',
    save: 'Kaydet',
    select: 'Seç',
  },
  deviceManager: {
    title: 'Gömülü Cihaz Logger v{version}',
    panelTitle: 'Gömülü Cihazlar Yöneticisi',
    intro: 'Cihazları ve varsayılan yapılandırmayı yönetin.',
    removeStoredPasswords: 'İndir Stored Passwords',
    editJson: 'JSON',
    viewConfigurationExample: 'View configuration example',
    saveChanges: 'Kaydet değişiklikler',
    defaults: 'Temsiller',
    defaultsDescription:
      'Tüm cihazlar için varsayılan değerler. Her cihaz, istenirse cihazlar masasında değiştirebilir.',
    enableSshTerminal: 'Enable SSH terminal',
    enableSftpExplorer: 'Enable SFTP Explorer',
    enableExternalWebBrowser: 'Enable dış web tarayıcı',
    enableEmbeddedWebBrowser: 'Enable gömülü web tarayıcı',
    enableDevicePing: 'Enable cihaz ping',
    language: 'Eklenti dili',
    port: 'Port',
    logCommand: 'Log komut',
    maxLinesPerTab: 'Sayfa başına Max hatları',
    pingIntervalSeconds: 'Ping interval (saniyeler)',
    pingIntervalPlaceholder: 'Kılavuz için boş bırakın sadece',
    sshCommands: 'SSH komutları',
    groups: 'Grup Grup Grupları',
    groupsDescription:
      'Korumalı cihazlardaki cihazları organize etmek için Seçmeli gruplar tanımlayın.',
    addGroup: 'Ekle grubu ekle',
    devices: 'Cihazlar',
    devicesDescription: 'Satırları ekleyin veya kaldırın, sonra alanları sıralayın.',
    addDevice: 'Ekle cihazı ekle',
    moveSelectedDevicesUp: 'Listede seçilen cihazlar hareket ettirin',
    moveSelectedDevicesDown: 'Listede seçilmiş cihazlar atlayın',
    resetPassword: 'Şifre sıfırlama parola sıfırlama',
    removeStoredPasswordsForSelectedDevices:
      'Seçilmiş cihazlar için depolanmış şifreler ve geçişler',
    columnId: 'ID',
    columnGroup: 'Grup Grup Grup Grubu',
    columnColor: 'Renkli Renk',
    columnHost: 'Host',
    columnUser: 'Kullanıcı',
    columnHostFingerprint: 'Host parmak izi',
    columnSecondaryHost: 'Orta ev sahibi',
    columnSecondaryFingerprint: 'İkinci parmak izi',
    columnSshTerminal: 'SSH terminali',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'SFTP presets (remote)',
    columnSftpPresetsLocal: 'SFTP presets (yerel)',
    columnExternalWebBrowser: 'Dış Web Browser',
    columnEmbeddedWebBrowser: 'Gömülü Web Browser',
    columnWebUrl: 'Web URL',
    columnPrivateKeyPath: 'Özel anahtar yol yolu',
    columnPrivateKeyPassphrase: 'Özel anahtar geçiş',
    columnPasswordWriteOnly: 'Şifre (sadece yazmak)',
    columnShowDefaultSshCommands: 'Show default SSH komutları',
    columnBastionHost: 'Bastion host host',
    columnBastionPort: 'Bastion port',
    columnBastionUser: 'Bastion user',
    columnBastionFingerprint: 'Bastion parmak izi',
    columnBastionKeyPath: 'Bastion key road',
    columnBastionKeyPassphrase: 'Bastion key passphrase',
    columnBastionPasswordWriteOnly: 'Bastion password (sadece yazmak)',
    groupNamePlaceholder: 'Grup adı',
    editScript: 'Edit script',
    editScriptFor: '{name} için Senaryo',
    sshCommandFallback: 'SSH komut',
    scriptDescription: "/tmp'e kopyalanacak ve idam edilecek senaryoyu yazın.",
    sshCommandScriptEditor: 'SSH komut senaryo editörü editörü editörü',
    commandNamesEmojiHelp: "Komutan isimleri https://emojidb.org/'den emojileri destekliyor",
    openSshPanel: 'Open SSH Panel Panel Panel',
    rerunOnReconnection: 'Re-run on reconnection',
    copyAndRunScript: 'Kopya ve Run',
    addCommand: 'Ekle komut ekle',
    openCommandInSshPanel: 'Bu komutu bir SSH panelinde açın',
    openNamedCommandInSshPanel: '{name} SSH panelinde',
    rerunCommandAfterReconnect: 'Bu komutu SSH paneli yeniden bağlantı kurduktan sonra satın alın',
    rerunNamedCommandOnReconnect: 'Re-run {name} yeniden bağlantı halinde',
    copyScriptToTmp: "/tmp'e bir senaryo gönderin ve komutdan sonra çalıştırın",
    copyAndRunScriptFor: '{name} için kopyalayın ve çalıştırın',
    removeCommand: 'Kaldır komut',
    dragToResize: 'Drag to resize',
    selectDeviceRow: 'Cihaz sırasını seçin',
    removedSelectedDevice: 'Seçilmiş cihaz kaldırıldı.',
    removedSelectedDevices: '{count} seçilmiş cihazlar.',
    saving: 'Tasarruf...',
    openingSettingsJson: 'Açılış settings.json...',
    removingStoredPasswords: 'Güvenli şifreleri geri yüklemek...',
    exportingSettings: 'İhracat ayarları...',
    importingSettings: 'İthalat ayarları...',
    setSelectedDeviceIdBeforeReset: "En az seçilmiş bir cihaz ID'i depolamadan önce sipariş edin.",
    removingStoredPasswordForDevice: '{id} için saklanan şifreyi geri yükleyin...',
    removingStoredPasswordsForDevices: '{count} için depolanmış şifreleri geri yüklemek...',
    configurationExample: 'Yapılandırma örneği',
    configurationExampleDescription:
      "Bu varsayılanları settings.json'inize kopyalayın ve yapıştırın.",
    copiedConfigurationExample: 'Copied konfigürasyon örneği.',
    failedToCopyConfigurationExample: 'Konfigürasyon örneklerini kopyalamaya başarısız oldu.',
    savedSettings: 'Kurtarılan ayarlar.',
    failedToSaveSettings: 'Ayarları kurtarmak için başarısız oldu.',
    importedSettingsApply:
      'İthalatlanmış ayarlar. Onları gözden geçirin ve onları uygulamak için Kaydet değişiklikleri tıklayın.',
    failedToImportSettings: 'Yükleme ayarlarına başarısız oldu.',
    exportSettingsSaveLabel: 'İhracat ayarları',
    exportCanceled: 'İhracat iptal edildi.',
    exportedSettingsTo: "{path}'e ihracat.",
    failedToExportSettings: 'İhracat ayarlarına başarısız oldu: {message}',
    importSettingsOpenLabel: 'İthalat ayarları',
    importCanceled: 'İthalat iptal edildi.',
    importedSettingsFrom:
      "{path}'den ithal edilen ayarlar. İnceleme ve tıklayın Onları uygulamak için Save changes.",
    failedToImportSettingsWithMessage: 'Yükleme ayarlarına başarısız oldu: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      'Kurtarılan ayarlar. Pencereyi ya da uzatma hostunu yeniden yükleyin, sonra gömülü Web Browser varsayılanını sürdürmek için tekrar tasarruf edin.',
    reloadToPersistNewDefaultSettings:
      'Ayarlar kaydedildi. Yeni eklenen varsayılan ayarları kalıcı hale getirmek için pencereyi veya eklenti ana bilgisayarını yeniden yükleyin ve tekrar kaydedin.',
  },
  sidebar: {
    title: 'Gömülü Logger Cihazları',
    copyUrl: 'URL',
    copyName: 'Kopya İsim',
    pingInProgress: 'İleride ilerleme',
    pingReachable: 'Ping ulaşılabilir',
    pingUnreachable: 'Güvenilmez',
    openLogs: 'Open Logs',
    openLogsFor: '{name} için açık oturumlar',
    openSshTerminal: 'Open SSH Terminal Terminal Terminal Terminal',
    openSshTerminalFor: 'SSH terminal oturumu için {name}',
    openSftpExplorer: 'Open SFTP Explorer Explorer',
    browseAndTransferFilesFor: '{name} için göz ve transfer dosyaları',
    openExternalWebBrowser: 'Açık Dış Web Browser',
    openExternalWebBrowserFor: 'Bir dış tarayıcıda URL için yapılandırılmış web {name}',
    openEmbeddedWebBrowser: 'Açık Gömülü Web Browser',
    openEmbeddedWebBrowserFor: 'URL için yapılandırılan web {name} için VS Code',
    copyScriptCommandTitle: "/tmp, chmod 777'e kopyalayın ve çalıştırın",
    noDevicesConfigured:
      'Hiçbir cihaz yapılandırılmadı. Update "embeddedLogger.devices" ayarlarında.',
    deviceNameLabel: 'Cihaz adı',
    deviceUrlLabel: 'Device URL',
    copiedToClipboard: '{label} klip odasına kopyaladı.',
  },
  deviceTree: {
    noDevicesConfigured:
      'Hiçbir cihaz yapılandırılmadı. Update "embeddedLogger.devices" ayarlarında.',
    openSettingsToConfigure: 'Gömülü cihazları yapılandırmak için açık ayarlar.',
    openSettings: 'Açık Ayarlar',
    openDeviceLogs: 'Open Device Logs',
    groupTooltip: '{name} grubu',
  },
  logPanel: {
    logsTitle: '{name} Logs Logs',
    minLevel: 'Min Level',
    textFilter: 'Text Filter Filter',
    filterSubstring: 'Filtre substring',
    filteringPresets: 'Filtreleme Presets',
    filterPresets: 'Filtre presets',
    savePreset: 'Kaydet preset',
    deletePreset: 'Delete preset',
    exportLogs: 'İhracat günlükleri',
    editLogFile: 'Edit log file',
    refreshLogFile: 'Yeni sürüm dosyasını',
    startAutoSave: 'Auto-save',
    stopAutoSave: 'Auto-save',
    clearLogs: 'Clear loglar',
    highlight: 'Highlight',
    wordWrap: 'Word Turn',
    autoScroll: 'Auto-scroll',
    autoReconnect: 'Auto-reconnect',
    toggleState: '{label} ({state})',
    toggleOn: 'onda',
    toggleOff: 'kapalı',
    find: 'Find',
    findInLogs: 'Kayıtlarda bulun (Ctrl/Cmd+F)',
    clearSearch: 'Clear arama',
    previousMatch: 'Önceki Maç',
    nextMatch: 'Sonraki maç',
    prev: 'Prev',
    next: 'Sonraki',
    reconnect: 'Yeniden bağlantı',
    disconnect: 'Disconnectconnect',
    highlights: 'Yüksek ışıklar',
    addHighlight: 'add',
    removeAllHighlights: 'her şeyi ortadan kaldır',
    highlightKeywords: 'Highlight anahtar kelimeler',
    lineLimitLive:
      'Configured display line limit ulaştı. Yaşlı çizgiler yeni girişlerle değiştirildi.',
    lineLimitOffline:
      'Configured display line limit ulaştı. Yaşlı ithal hatları bu görüşten gizlenmişti.',
    upToTenHighlights: '10 anahtara vurgulayabilirsiniz.',
    keyToHighlight: 'Anahtar vurgulamak için',
    removeHighlight: 'Kaldırın',
    noPreset: '(no preset)',
    filterPresetNamed: 'Filtre preset: {name}',
    connectedStreaming: 'Bağlanmış. Akış logları...',
    bookmarkLabel: 'Bookmark etiketi',
    enterBookmarkLabel: 'Bookmark etiketi girin',
    addBookmark: 'Add bookmark',
    editBookmarkLabel: 'Edit bookmark label',
    removeBookmark: 'Kaldır',
    removeAllBookmarks: 'Tüm kitap işaretlerini kaldır',
    goToNextBookmark: 'Sonraki Yazıya Git',
    goToPreviousBookmark: 'Önceki yazıya Git',
    clearStatusMessage: 'Clear durum mesajı',
    connectionClosed: 'Bağlantı kapalı.',
    retryingInSeconds: '{message} {seconds} saniye içinde yeniden çalışmak...',
    reconnecting: 'Yeniden bağlantı kurmak...',
    disconnecting: 'Bağlanma...',
    hostKeyFailedDetails:
      'Host key doğrulama başarısız oldu. Beklenmiş {expected} ama {received} aldı. Yeniden bağlantı kurmak için parmak izi güncelleyin.',
    hostKeyFailed:
      'Host key doğrulama başarısız oldu. Yeniden bağlantı kurmadan önce saklanan parmak izi güncelleyin.',
    sessionClosed: 'Oturum kapalı.',
    sshSessionClosedOn: '--- SSH seansı {timestamp} üzerinde kapalı',
    dateAtTime: "{date}'de {time}",
    autoSavingTo: 'Auto-serv to',
    autoSaveEnabled: 'Auto-save etkinleştirildi.',
    autoSaveFailed: 'Auto-save başarısız oldu.',
    waitingForPassword: 'Kullanıcının şifreye girmesini bekleyin..',
  },
  extension: {
    missingHost: 'Device "{name}" ev sahibi eksik.',
    missingUsername: 'Device "{name}" bir kullanıcı eksik.',
    invalidPort: 'Device "{name}" geçersiz bir limana sahiptir.',
    credentialsMigrationWarning:
      'Credentials Secret Storage\'e göç edildi, ancak "password" veya "özelKeyPassphrase" alanları kaldırılamadı. Lütfen onları ayarlarınızda embeddedLogger.devices\'den silin.',
    sftpPresetsMigrationFailed: "SFTP'i embeddedLogger.devices.'e taşımayı başaramadı.",
    noHostFound: 'Seçilen cihaz için ev sahibi bulunamadı.',
    webUrlMustStart: 'Web tarayıcı URLs http:// veya https://. ile başlamalıdır',
    invalidWebUrl: 'Invalid web URL için {name}: {message}',
    deviceNotFound: 'Cihaz bulunamadı. embeddedLogger.devices.',
    workspaceTrustDeviceResources: 'Cihaz kaynakları açmadan önce iş alanı güveni gereklidir.',
    workspaceTrustConnect: 'Workspace trust, cihazlara bağlanmadan önce gereklidir.',
    embeddedBrowserUnavailable: 'VS Code gömülü tarayıcı desteği mevcut değildir.',
    failedToOpenUri: 'Açılmak için başarısız oldu {uri}: {message}',
    sshCommandNoControlCharacters:
      'SSH komutları kontrol karakterleri veya yeni çizgiler içermemelidir.',
    runningCommandOnDevice: '"{command}" {device}',
    commandFinishedOnDevice: 'Komut "{command}" {device} üzerinde bitmiştir.',
    noDevicesConfigured: 'Hiçbir cihaz yapılandırılmadı. embeddedLogger.devices.',
    selectDeviceForSftp: 'SFTP Explorer açmak için bir cihaz seçin',
    selectDeviceForExternalBrowser: 'Dış web tarayıcısında açmak için bir cihaz seçin',
    selectDeviceForEmbeddedBrowser: 'Gömülü web tarayıcılarında açmak için bir cihaz seçin',
    storedPasswordsRemovedFor: 'Mağazalı şifreler ve geçişler {device} için kaldırıldı.',
    noDevicesToClearPasswords: 'Hiçbir cihaz parolaları netleştirmek için yapılandırılmadı.',
    storedPasswordsRemoved:
      'Mağazalı şifreler ve geçişler yapılandırılmış cihazlar için kaldırıldı.',
    openLogFile: 'Open log file',
    failedToReadLogFile: 'Kayıt dosyasını okumak için başarısız oldu: {message}',
    localPanelSuffix: 'Yerel',
    noDeviceInfo: 'Hiçbir cihaz bilgisi sağlamadı.',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: 'Bir cihaz olmadan bir günlük seans oluşturamaz.',
    loadedLines: '{count} hatları.',
    presetSaved: 'Preset "{name}" {target} için kurtarıldı.',
    presetRemoved: 'Preset "{name}" {target} için kaldırıldı.',
    exportLogsSaveLabel: 'İhracat günlükleri',
    exportedLines: '{count} hatları {target}.',
    failedToExportLogs: 'İhracat loglarını ihraç etmek için başarısız oldu: {message}',
    failedToExportLogsFallback: 'Girişleri ihraç etmek için başarısız oldu.',
    editOnlyImported: 'Edit sadece ithal günlük dosyaları için mevcuttur.',
    failedToOpenLogFile: 'Kayıt dosyasını açmaya başarısız oldu: {message}',
    failedToOpenLogFileFallback: 'Kayıt dosyasını açmaya başarısız oldu.',
    refreshOnlyImported: 'Yenileme yalnızca ithal günlük dosyaları için mevcuttur.',
    failedToReadLogFile: 'Kayıt dosyasını okumak için başarısız oldu: {message}',
    failedToReadLogFileFallback: 'Log dosyasını okumak için başarısız oldu.',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: 'Oturum kapalı.',
    disconnected: 'Ayrıştırma.',
    reconnecting: 'Yeniden bağlantı kurmak...',
    failedToReconnect: 'Yeniden bağlantı kurmak için başarısız oldu.',
    autoSaveDialogTitle: 'Giriş dosyasını otomatik olarak SSH çıktı',
    allFiles: 'Tüm Dosyalar',
    autoSaveCancelled: 'Auto-save iptal edildi.',
    autoSaveFailed: 'Auto-save başarısız oldu: {message}',
    autoSaveFailedFallback: 'Auto-save başarısız oldu.',
    hostKeyVerificationFailed:
      'Ev sahibi anahtar doğrulama {target} için başarısız oldu. Beklenmiş {expected} ama {received} aldı. Yeniden bağlantı kurmak için ayarlardaki parmak izi güncelleyin.',
    sshSessionClosedOn: '--- SSH seansı {timestamp} üzerinde kapalı',
  },
};
