import type { en } from './en';

export const zhCn: typeof en = {
  languageId: 'zh-cn',
  htmlLang: 'zh-CN',
  languageNames: {
    vscode: 'VSCode 默认',
    en: '英语',
    es: '西班牙语',
    it: '意大利语',
    'zh-cn': '简体中文',
    'zh-tw': '繁體中文',
    fr: '法语',
    de: '德语',
    ja: '日语',
    ko: '韩语',
    ru: '俄语',
    'pt-br': '葡萄牙语（巴西）',
    tr: '土耳其语',
    pl: '波兰语',
    cs: '捷克语',
    hu: '匈牙利语',
  },
  common: {
    add: '添加',
    cancel: '取消',
    close: '关闭',
    command: '命令',
    copy: '复制',
    default: '默认',
    disabled: '已禁用',
    enabled: '已启用',
    exportSettings: '导出设置',
    importSettings: '导入设置',
    name: '名称',
    none: '无',
    remove: '移除',
    save: '保存',
    select: '选择',
  },
  deviceManager: {
    title: '嵌入式设备 Logger v{version}',
    panelTitle: '嵌入式设备管理器',
    intro: '管理设备和默认配置。',
    removeStoredPasswords: '删除已存储的密码',
    editJson: '用 JSON 编辑',
    viewConfigurationExample: '查看配置示例',
    saveChanges: '保存更改',
    defaults: '默认',
    defaultsDescription: '所有设备的默认值 。 如果需要,每个设备都可以在设备表中更改.',
    enableSshTerminal: '启用 SSH 终端',
    enableSftpExplorer: '启用 SFTP 探索器',
    enableExternalWebBrowser: '启用外部网页浏览器',
    enableEmbeddedWebBrowser: '启用嵌入式网页浏览器',
    enableDevicePing: '启用设备键',
    language: '扩展语言',
    port: '端口',
    logCommand: '日志命令',
    maxLinesPerTab: '每个标签的最大行数',
    pingIntervalSeconds: '平分间隔( 秒)',
    pingIntervalPlaceholder: '空白只用于手动打字',
    sshCommands: 'SSH命令',
    groups: '组',
    groupsDescription: '在嵌入式设备视图中定义组织设备的可选组.',
    addGroup: '添加组',
    devices: '设备',
    devicesDescription: '添加或删除行,然后在行中编辑字段.',
    addDevice: '添加设备',
    moveSelectedDevicesUp: '在列表中上移选中的设备',
    moveSelectedDevicesDown: '在列表中下移选中的设备',
    resetPassword: '重置密码',
    removeStoredPasswordsForSelectedDevices: '删除已存储的选定设备的密码和密码句',
    columnId: '兹兹克',
    columnGroup: '组',
    columnColor: '颜色',
    columnHost: '东道主',
    columnUser: '用户',
    columnHostFingerprint: '主机指纹',
    columnSecondaryHost: '二级东道主',
    columnSecondaryFingerprint: '二级指纹',
    columnSshTerminal: 'SSH终端',
    columnSftp: '兹兹克',
    columnSftpPresetsRemote: 'SFTP预设( 远程)',
    columnSftpPresetsLocal: 'SFTP预设( 本地)',
    columnExternalWebBrowser: '外部网页浏览器',
    columnEmbeddedWebBrowser: '嵌入式网页浏览器',
    columnWebUrl: '网页 URL',
    columnPrivateKeyPath: '私钥路径',
    columnPrivateKeyPassphrase: '私钥密码句',
    columnPasswordWriteOnly: '密码( 只写)',
    columnShowDefaultSshCommands: '显示默认 SSH 命令',
    columnBastionHost: '巴斯通主机',
    columnBastionPort: '巴斯通端口',
    columnBastionUser: '地下室用户',
    columnBastionFingerprint: '血压指纹',
    columnBastionKeyPath: '巴斯通密钥路径',
    columnBastionKeyPassphrase: '巴斯通密钥密码句',
    columnBastionPasswordWriteOnly: '绑定密码( 只写)',
    groupNamePlaceholder: '组名称',
    editScript: '编辑脚本',
    editScriptFor: '编辑 {name} 的脚本',
    sshCommandFallback: 'SSH命令',
    scriptDescription: '写入将复制到 /tmp并被执行的脚本 .',
    sshCommandScriptEditor: 'SSH 命令脚本编辑器',
    commandNamesEmojiHelp: '命令名支持 https://emojidb.org/的emojis',
    openSshPanel: '打开 SSH 小组讨论会',
    rerunOnReconnection: '重联运行',
    copyAndRunScript: '复制并运行脚本',
    addCommand: '添加命令',
    openCommandInSshPanel: '在 SSH 面板中打开此命令',
    openNamedCommandInSshPanel: '在 SSH 面板中打开 {name}',
    rerunCommandAfterReconnect: 'SSH 面板再连接后重运行此命令',
    rerunNamedCommandOnReconnect: 'Re-run {name} on reconnection',
    copyScriptToTmp: 'Copy a script to /tmp and run it after the command',
    copyAndRunScriptFor: '复制和运行 {name} 的脚本',
    removeCommand: '删除命令',
    dragToResize: '拖放以调整大小',
    selectDeviceRow: '选择设备行',
    removedSelectedDevice: '删除了选中的设备 .',
    removedSelectedDevices: '已删除 {count} 选中的设备 .',
    saving: '正在保存...',
    openingSettingsJson: '打开ZQQ0ZZ...',
    removingStoredPasswords: '删除已存储的密码...',
    exportingSettings: '导出设置...',
    importingSettings: '正在导入设置...',
    setSelectedDeviceIdBeforeReset:
      'Set at least one selected device ID before resetting stored password.',
    removingStoredPasswordForDevice: '删除 {id} 已存储密码...',
    removingStoredPasswordsForDevices: 'Removing stored passwords for {count} selected devices...',
    configurationExample: '配置示例',
    configurationExampleDescription: '复制并粘贴这些默认值到您的 settings.json.',
    copiedConfigurationExample: '复制配置实例 .',
    failedToCopyConfigurationExample: '复制配置示例失败 .',
    savedSettings: '已保存设置 .',
    failedToSaveSettings: '保存设置失败 .',
    importedSettingsApply: '导入设置 。 查看并点击保存更改以应用它们 .',
    failedToImportSettings: '导入设置失败 .',
    exportSettingsSaveLabel: '导出设置',
    exportCanceled: '导出已取消 .',
    exportedSettingsTo: 'Exported settings to {path}.',
    failedToExportSettings: 'Failed to export settings: {message}',
    importSettingsOpenLabel: '导入设置',
    importCanceled: '导入已取消 .',
    importedSettingsFrom: '从 {path} 导入设置 。 审查和点击保存更改以应用它们.',
    failedToImportSettingsWithMessage: 'Failed to import settings: {message}',
    reloadToPersistEmbeddedBrowserDefault:
      '已保存设置 。 重新装入窗口或扩展主机, 然后再次保存以坚持嵌入式 Web 浏览器默认值 .',
    reloadToPersistNewDefaultSettings:
      '设置已保存。请重新加载窗口或扩展主机，然后再次保存以保留新添加的默认设置。',
  },
  sidebar: {
    title: '嵌入式 Logger 设备',
    copyUrl: '复制 URL',
    copyName: '复制名称',
    pingInProgress: '进行中的平',
    pingReachable: '平可达',
    pingUnreachable: 'Ping 无法到达',
    openLogs: '打开日志',
    openLogsFor: '{name} 打开日志',
    openSshTerminal: '打开 SSH 终端',
    openSshTerminalFor: '为 {name} 打开 SSH 终端会话',
    openSftpExplorer: '打开 SFTP 浏览器',
    browseAndTransferFilesFor: '{name}的浏览和传输文件',
    openExternalWebBrowser: '打开外部网页浏览器',
    openExternalWebBrowserFor: '在外部浏览器中打开 {name} 配置的网页 URL',
    openEmbeddedWebBrowser: '打开嵌入式网页浏览器',
    openEmbeddedWebBrowserFor: 'Open the configured web URL for {name} in VS Code',
    copyScriptCommandTitle: '复制脚本到 /tmp, chmod 777,并运行它',
    noDevicesConfigured: '没有配置设备 。 在设置中更新"embeddedLogger.devices".',
    deviceNameLabel: '设备名称',
    deviceUrlLabel: '设备 URL',
    copiedToClipboard: '{label}被复制到剪贴板.',
  },
  deviceTree: {
    noDevicesConfigured: '没有配置设备 。 在设置中更新"embeddedLogger.devices".',
    openSettingsToConfigure: '打开配置嵌入式设备的设置 .',
    openSettings: '打开设置',
    openDeviceLogs: '打开设备日志',
    groupTooltip: '{name}组',
  },
  logPanel: {
    logsTitle: '{name} Logs',
    minLevel: '最低级',
    textFilter: '文本过滤器',
    filterSubstring: '过滤子字符串',
    filteringPresets: '过滤预设',
    filterPresets: '过滤预设',
    savePreset: '保存预设',
    deletePreset: '删除预设',
    exportLogs: '导出日志',
    editLogFile: '编辑日志文件',
    refreshLogFile: '刷新日志文件',
    startAutoSave: '开始自动保存',
    stopAutoSave: '停止自动保存',
    clearLogs: '清除日志',
    highlight: '突出显示',
    wordWrap: '文字包装',
    autoScroll: '自动滚动',
    autoReconnect: '自动重接',
    toggleState: '{label} ({state})',
    toggleOn: '打开',
    toggleOff: '关',
    find: '查找',
    findInLogs: '在日志中查找 (Ctrl/Cmd+F)',
    clearSearch: '清除搜索',
    previousMatch: '上一个匹配',
    nextMatch: '下一个匹配',
    prev: '前一頁',
    next: '下一个',
    reconnect: '重新连接',
    disconnect: '断开连接',
    highlights: '要点',
    addHighlight: '添加',
    removeAllHighlights: '删除全部',
    highlightKeywords: '突出显示关键字',
    lineLimitLive: '已达到配置的显示行限制 。 更老的线路被更新的条目所取代.',
    lineLimitOffline: '已达到配置的显示行限制 。 此视图中隐藏了已导入的旧行 .',
    upToTenHighlights: '你可以突出显示最多10个键.',
    keyToHighlight: '要突出显示的密钥',
    removeHighlight: '删除突出显示',
    noPreset: '(无预设)',
    filterPresetNamed: '筛选预设: {name}',
    connectedStreaming: '已连接 。 正在流出日志...',
    bookmarkLabel: '书签标签',
    enterBookmarkLabel: '输入书签标签',
    addBookmark: '添加书签',
    editBookmarkLabel: '编辑书签标签',
    removeBookmark: '删除书签',
    removeAllBookmarks: '删除全部书签',
    goToNextBookmark: '转到下个书签',
    goToPreviousBookmark: '转到上一个书签',
    clearStatusMessage: '清除状态消息',
    connectionClosed: '连接已关闭 .',
    retryingInSeconds: '{message} Retrying in {seconds} seconds...',
    reconnecting: '正在重新连接...',
    disconnecting: '断开连接...',
    hostKeyFailedDetails:
      '主机密钥验证失败 。 预期{expected}但收到{received}. 更新指纹以重新连接 .',
    hostKeyFailed: '主机密钥验证失败 。 在重新连接前更新所存储的指纹 .',
    sessionClosed: '会议闭幕.',
    sshSessionClosedOn: 'SSH会议于{timestamp}闭幕',
    dateAtTime: '{date} 在{time}',
    autoSavingTo: '自动保存到',
    autoSaveEnabled: '自动保存启用 .',
    autoSaveFailed: '自动保存失败 .',
    waitingForPassword: '等待用户输入密码..',
  },
  extension: {
    missingHost: '设备"{name}"缺少一个主机.',
    missingUsername: '设备"{name}"缺少用户名.',
    invalidPort: '设备"{name}"有一个无效的端口.',
    credentialsMigrationWarning:
      'Credentials were migrated to Secret Storage, but the "password" or "privateKeyPassphrase" fields could not be removed. Please delete them from embeddedLogger.devices in your settings.',
    sftpPresetsMigrationFailed:
      '将 SFTP 预设迁移到 embeddedLogger.devices. 已存在的预设仍在扩展存储中失败 .',
    noHostFound: '没有找到选定设备的主机 .',
    webUrlMustStart: '网页浏览器 URL从 http://或 https://. 开始',
    invalidWebUrl: '{name}:{message}',
    deviceNotFound: '未找到设备 。 检查 embeddedLogger.devices.',
    workspaceTrustDeviceResources: '在打开设备资源前需要工作空间信任.',
    workspaceTrustConnect: '连接到设备之前需要工作空间信任 .',
    embeddedBrowserUnavailable: 'VS Code嵌入式浏览器支持不可用.',
    failedToOpenUri: '打开失败 {uri}:{message}',
    sshCommandNoControlCharacters: 'SSH命令不得包含控制字符或新行.',
    runningCommandOnDevice: 'Running "{command}" on {device}',
    commandFinishedOnDevice: 'Command "{command}" finished on {device}.',
    noDevicesConfigured: '未配置设备 。 检查 embeddedLogger.devices.',
    selectDeviceForSftp: '选择打开 SFTP 探索器的设备',
    selectDeviceForExternalBrowser: '选择在外部网页浏览器中打开的设备',
    selectDeviceForEmbeddedBrowser: '选择在嵌入的网络浏览器中打开的设备',
    storedPasswordsRemovedFor: '{device}已取出存储密码和密码句.',
    noDevicesToClearPasswords: '没有配置用于清除密码的设备 .',
    storedPasswordsRemoved: '已删除已配置设备的已存储密码和密码句 .',
    openLogFile: '打开日志文件',
    failedToReadLogFile: '读取日志文件失败: {message}',
    localPanelSuffix: '当地',
    noDeviceInfo: '未提供设备信息 .',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: '没有设备无法创建日志会话 .',
    loadedLines: '装入了{count}线.',
    presetSaved: 'Preset "{name}" saved for {target}.',
    presetRemoved: 'Preset "{name}" removed for {target}.',
    exportLogsSaveLabel: '导出日志',
    exportedLines: '从{target}导出{count}行.',
    failedToExportLogs: 'Failed to export logs: {message}',
    failedToExportLogsFallback: '导出日志失败 .',
    editOnlyImported: '仅可用于导入的日志文件 .',
    failedToOpenLogFile: '打开日志文件失败: {message}',
    failedToOpenLogFileFallback: '打开日志文件失败 .',
    refreshOnlyImported: '刷新仅适用于导入的日志文件 .',
    failedToReadLogFile: '读取日志文件失败: {message}',
    failedToReadLogFileFallback: '读取日志文件失败 .',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: '会议闭幕.',
    disconnected: '已断相通.',
    reconnecting: '正在重新连接...',
    failedToReconnect: '重新连接失败 .',
    autoSaveDialogTitle: '选择自动保存 SSH 输出的日志文件',
    allFiles: '所有文件',
    autoSaveCancelled: '自动保存取消 .',
    autoSaveFailed: '自动保存失败: {message}',
    autoSaveFailedFallback: '自动保存失败 .',
    hostKeyVerificationFailed:
      '{target}的主机密钥校验失败. 预期{expected}但得到{received}. 更新设置中的指纹以重新连接 .',
    sshSessionClosedOn: 'SSH会议于{timestamp}闭幕',
  },
};
