import type { en } from './en';

export const zhTw: typeof en = {
  languageId: 'zh-tw',
  htmlLang: 'zh-TW',
  languageNames: {
    vscode: 'VSCode 預設',
    en: '英文',
    es: '西班牙文',
    it: '義大利文',
    'zh-cn': '简体中文',
    'zh-tw': '繁體中文',
    fr: '法文',
    de: '德文',
    ja: '日文',
    ko: '韓文',
    ru: '俄文',
    'pt-br': '葡萄牙文（巴西）',
    tr: '土耳其文',
    pl: '波蘭文',
    cs: '捷克文',
    hu: '匈牙利文',
  },
  common: {
    add: '新增',
    cancel: '取消',
    close: '關閉',
    command: '命令',
    copy: '複製',
    default: '預設',
    disabled: '已停用',
    enabled: '已啟用',
    exportSettings: '匯出設定',
    importSettings: '匯入設定',
    name: '名稱',
    none: '無',
    remove: '移除',
    save: '儲存',
    select: '選取',
  },
  deviceManager: {
    title: '嵌入式裝置 Logger v{version}',
    panelTitle: '嵌入式裝置管理器',
    intro: '管理裝置和預設組態。',
    removeStoredPasswords: '移除已儲存的密碼',
    editJson: '在 JSON 中編輯',
    viewConfigurationExample: '檢視設定示例',
    saveChanges: '儲存變更',
    defaults: '預設值',
    defaultsDescription: '所有裝置的預設值 。 如果需要, 每個裝置都可以在裝置表格中更改 .',
    enableSshTerminal: '啟用 SSH 终端',
    enableSftpExplorer: '啟用 SFTP 探險器',
    enableExternalWebBrowser: '開啟外部網頁瀏覽器',
    enableEmbeddedWebBrowser: '開啟嵌入的網頁瀏覽器',
    enableDevicePing: '啟用裝置 ping',
    showBastionOptions: '顯示堡壘機選項',
    language: '擴充功能語言',
    port: '端口',
    logCommand: '日志命令',
    maxLinesPerTab: '每分頁最大行數',
    pingIntervalSeconds: '(秒)',
    pingIntervalPlaceholder: '就把空白放入手動打字',
    sshCommands: 'SSH命令',
    groups: '群組',
    groupsDescription: '在嵌入式裝置檢視中設定裝置的可選取群組 .',
    addGroup: '新增群組',
    devices: '裝置',
    devicesDescription: '新增或去除行,再用內線編輯字段 .',
    addDevice: '新增裝置',
    moveSelectedDevicesUp: '在清單中上移所選取的裝置',
    moveSelectedDevicesDown: '在清單中下移所選取的裝置',
    resetPassword: '重置密碼',
    removeStoredPasswordsForSelectedDevices: '为所選取的裝置去除已儲存的口令和密碼',
    columnId: 'ID',
    columnGroup: '群組',
    columnColor: '顏色',
    columnHost: '主机',
    columnUser: '使用者',
    columnHostFingerprint: '主機指紋',
    columnSecondaryHost: '二等主机',
    columnSecondaryFingerprint: '二手指紋',
    columnSshTerminal: 'SSH 终端',
    columnSftp: 'SFTP',
    columnSftpPresetsRemote: 'SFTP 預置 (遠取)',
    columnSftpPresetsLocal: 'SFTP 預置 (地上)',
    columnExternalWebBrowser: '外部網頁瀏覽器',
    columnEmbeddedWebBrowser: '有嵌入的網頁瀏覽器',
    columnWebUrl: '網頁 URL',
    columnPrivateKeyPath: '私密金鑰路徑',
    columnPrivateKeyPassphrase: '私密金鑰密碼',
    columnPasswordWriteOnly: '密碼 (只寫出)',
    columnShowDefaultSshCommands: '顯示預設的 SSH 命令',
    columnBastionHost: 'Bastion 主機',
    columnBastionPort: 'Bastion 端口',
    columnBastionUser: 'Bastion 使用者',
    columnBastionFingerprint: 'Bastion 指紋',
    columnBastionKeyPath: 'Bastion 金鑰路徑',
    columnBastionKeyPassphrase: 'Bastion 金鑰密碼',
    columnBastionPasswordWriteOnly: 'Bastion 密碼 (只寫)',
    groupNamePlaceholder: '群組名稱',
    editScript: '編輯文稿',
    editScriptFor: '編輯 {name} 的文稿',
    sshCommandFallback: 'SSH 命令',
    scriptDescription: '寫出要被复制到 /tmp并被執行的文稿 .',
    sshCommandScriptEditor: 'SSH 命令文稿編輯器',
    commandNamesEmojiHelp: '指揮名為 https://emojidb.org/ 所支援的emojis',
    openSshPanel: '開啟 SSH 面板',
    rerunOnReconnection: '在再連接上重跑',
    copyAndRunScript: '复制并執行文稿',
    addCommand: '新增命令',
    openCommandInSshPanel: '在 SSH 面板中開啟此命令',
    openNamedCommandInSshPanel: '在 SSH 面板中開啟 {name}',
    rerunCommandAfterReconnect: 'SSH面板重新連接後重新執行此命令',
    rerunNamedCommandOnReconnect: '重連接的 {name}',
    copyScriptToTmp: '复制文稿到 /tmp , 在命令之後執行',
    copyAndRunScriptFor: '复制並執行 {name} 的文稿',
    removeCommand: '移除命令',
    dragToResize: '拖曳以改變大小',
    selectDeviceRow: '選擇裝置列',
    removedSelectedDevice: '已移除選取的裝置 .',
    removedSelectedDevices: '已移除 {count} 選取的裝置 .',
    saving: '正在保存...',
    openingSettingsJson: '開啟 settings.json...',
    removingStoredPasswords: '移除已儲存的密碼...',
    exportingSettings: '匯出設定值...',
    importingSettings: '匯入設定值中...',
    setSelectedDeviceIdBeforeReset:
      'Set at least one selected device ID before resetting stored password.',
    removingStoredPasswordForDevice: '移除已儲存的 {id} 的密碼...',
    removingStoredPasswordsForDevices: '移除 {count} 選取裝置的已儲存密碼...',
    configurationExample: '配置示例',
    configurationExampleDescription: '复制並貼入您的 settings.json .',
    copiedConfigurationExample: '已复制配置示例 .',
    failedToCopyConfigurationExample: '复制配置示例失敗 .',
    savedSettings: '有儲存的設定值 .',
    failedToSaveSettings: '儲存設定值失敗 .',
    importedSettingsApply: '已匯入設定值 。 檢視并點擊儲存變更以應用 .',
    failedToImportSettings: '匯入設定值失敗 .',
    exportSettingsSaveLabel: '匯出設定值',
    exportCanceled: '匯出已取消 .',
    exportedSettingsTo: '已匯出設定值到 {path}.',
    failedToExportSettings: '匯出設定失敗 : {message}',
    importSettingsOpenLabel: '匯入設定值',
    importCanceled: '匯入已取消 .',
    importedSettingsFrom: '从 {path} 匯入設定值 。 檢視并點擊已儲存變更以應用 .',
    failedToImportSettingsWithMessage: '匯入設定值失敗 : {message}',
    reloadToPersistEmbeddedBrowserDefault:
      '有儲存的設定值 。 重新載入視窗或延伸主機, 然后再儲存以堅持嵌入的網頁瀏覽器預設 .',
    reloadToPersistNewDefaultSettings:
      '設定已儲存。請重新載入視窗或擴充功能主機，然後再次儲存以保留新加入的預設設定。',
  },
  sidebar: {
    title: '嵌入式',
    copyUrl: '复制 URL',
    copyName: '复制名',
    pingInProgress: '有進取了',
    pingReachable: '平可通取',
    pingUnreachable:
      '有能通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通通',
    openLogs: '開啟日志',
    openLogsFor: '为 {name} 開啟紀錄',
    openSshTerminal: '開啟 SSH 终端',
    openSshTerminalFor: '为 {name} 開啟 SSH 終站会話',
    openSftpExplorer: '開啟 SFTP 探索器',
    browseAndTransferFilesFor: '瀏覽并傳輸 {name} 的檔案',
    openExternalWebBrowser: '開啟外部網頁瀏覽器',
    openExternalWebBrowserFor: 'Open the configured web URL for {name} in an external browser',
    openEmbeddedWebBrowser: '開啟嵌入的網頁瀏覽器',
    openEmbeddedWebBrowserFor: 'Open the configured web URL for {name} in VS Code',
    copyScriptCommandTitle: '將文稿复制到 /tmp, chmod 777并執行',
    noDevicesConfigured: '沒有設定裝置 。 在設定中更新"embeddedLogger.devices" .',
    deviceNameLabel: '裝置名稱',
    deviceUrlLabel: '裝置 URL',
    copiedToClipboard: '{label}已复制到剪貼板 .',
  },
  deviceTree: {
    noDevicesConfigured: '沒有設定裝置 。 在設定中更新"embeddedLogger.devices" .',
    openSettingsToConfigure: '開啟設定嵌入式裝置的設定值 .',
    openSettings: '開啟設定值',
    openDeviceLogs: '開啟裝置紀錄',
    groupTooltip: '{name}群組',
  },
  logPanel: {
    logsTitle: '{name} 日志',
    minLevel: '最小等級',
    textFilter: '文字筛选',
    filterSubstring: '滤取子串',
    filteringPresets: '滤取預置',
    filterPresets: '筛选預置',
    savePreset: '儲存預置',
    deletePreset: '刪除預置',
    exportLogs: '匯出紀錄',
    editLogFile: '編輯紀錄檔',
    refreshLogFile: '刷新紀錄檔',
    startAutoSave: '有自動取出',
    stopAutoSave: '停止自動儲存',
    clearLogs: '清除日志',
    highlight: '突顯',
    wordWrap: '字包',
    autoScroll: '自動卷起',
    autoReconnect: '自動重接',
    toggleState: '{label} ({state})',
    toggleOn: '上',
    toggleOff: '關',
    find: '查找',
    findInLogs: '在日志中查找 (Ctrl/Cmd+F)',
    clearSearch: '清除搜索',
    previousMatch: '上一個相匹配',
    nextMatch: '下一個相匹配',
    prev: '前一頁',
    next: '下一頁',
    reconnect: '重接',
    disconnect: '斷接',
    highlights: '突顯',
    addHighlight: '添加',
    removeAllHighlights: '全部去除',
    highlightKeywords: '突顯关键字',
    lineLimitLive: '有已設定的顯示行限制 。 有更新的入行被取代了 .',
    lineLimitOffline: '有已設定的顯示行限制 。 有更老的匯入行被隱藏出此檢視 .',
    upToTenHighlights: '您可以亮出多至 10 個鍵 .',
    keyToHighlight: '要突顯的金鑰',
    removeHighlight: '移除突顯',
    noPreset: '( 沒有預設 )',
    filterPresetNamed: '滤取預置: {name}',
    connectedStreaming: '有接通了. 正在流出日志...',
    bookmarkLabel: '書签標籤',
    enterBookmarkLabel: '輸入書签標籤',
    addBookmark: '新增書签',
    editBookmarkLabel: '編輯書签標籤',
    removeBookmark: '移除書签',
    removeAllBookmarks: '移除所有書签',
    goToNextBookmark: '到下一個書签',
    goToPreviousBookmark: '跳至上一個書签',
    clearStatusMessage: '清除狀態信件',
    connectionClosed: '已關接 .',
    retryingInSeconds: '{message} Retrying in {seconds} seconds...',
    reconnecting: '正在重接中...',
    disconnecting: '正在斷接...',
    hostKeyFailedDetails:
      'Host key verification failed. Expected {expected} but received {received}. Update the fingerprint to reconnect.',
    hostKeyFailed: '主機金鑰驗證失敗 。 在重新連接前更新已儲存的指紋 .',
    sessionClosed: '第 二 章.',
    sshSessionClosedOn: '--- SSH session closed on {timestamp}',
    dateAtTime: '{date} 在{time}',
    autoSavingTo: '自動儲存到',
    autoSaveEnabled: '自動儲存已啟用 .',
    autoSaveFailed: '自動儲存失敗 .',
    waitingForPassword: '在等待使用者輸入密碼..',
  },
  extension: {
    missingHost: 'Device "{name}" is missing a host.',
    missingUsername: '裝置"{name}"缺少使用者名 .',
    invalidPort: '裝置"{name}"有无效端口.',
    credentialsMigrationWarning:
      'Credentials were migrated to Secret Storage, but the "password" or "privateKeyPassphrase" fields could not be removed. Please delete them from embeddedLogger.devices in your settings.',
    sftpPresetsMigrationFailed: '將 SFTP 預置移入 embeddedLogger.devices. 已存在的預置已存在 .',
    noHostFound: '找不到所選取裝置的主機 .',
    webUrlMustStart: '網頁瀏覽器 URL需要由 http:// 或 https://. 開始',
    invalidWebUrl: '{name}:{message}',
    deviceNotFound: '找不到裝置 。 檢查 embeddedLogger.devices.',
    workspaceTrustDeviceResources: '在開啟裝置資源前需要工作空間信任 .',
    workspaceTrustConnect: '在接通裝置前需要工作空間信任 .',
    embeddedBrowserUnavailable: 'VS Code嵌入式瀏覽器支援已無用.',
    failedToOpenUri: 'Failed to open {uri}: {message}',
    sshCommandNoControlCharacters: 'SSH命令中不能包含控制字符或新行 .',
    runningCommandOnDevice: 'Running "{command}" on {device}',
    commandFinishedOnDevice: 'Command "{command}" finished on {device}.',
    noDevicesConfigured: '沒有設定裝置 。 檢查 embeddedLogger.devices.',
    selectDeviceForSftp: '選擇要開啟 SFTP 探險器的裝置',
    selectDeviceForExternalBrowser: '在外網瀏覽器中選擇要開啟的裝置',
    selectDeviceForEmbeddedBrowser: '在嵌入的網頁瀏覽器中選擇要開啟的裝置',
    storedPasswordsRemovedFor: '{device}已取出已儲存的口令和口令.',
    noDevicesToClearPasswords: '沒有配置以清除密碼的裝置 .',
    storedPasswordsRemoved: '已取出已儲存的密碼和密碼口令以取出已設定的裝置 .',
    openLogFile: '開啟紀錄檔',
    failedToReadLogFile: '讀取紀錄檔失敗: {message}',
    localPanelSuffix: '本地',
    noDeviceInfo: '未提供裝置資訊 .',
  },
  logPanelHost: {
    cannotCreateWithoutDevice: '沒有裝置就無法建立紀錄片段 .',
    loadedLines: '已載入 {count}行.',
    presetSaved: 'Preset "{name}" saved for {target}.',
    presetRemoved: 'Preset "{name}" removed for {target}.',
    exportLogsSaveLabel: '匯出紀錄',
    exportedLines: 'Exported {count} lines from {target}.',
    failedToExportLogs: '匯出紀錄失敗 : {message}',
    failedToExportLogsFallback: '匯出紀錄失敗 .',
    editOnlyImported: '編輯只可被匯入的紀錄檔 .',
    failedToOpenLogFile: '開啟紀錄檔失敗: {message}',
    failedToOpenLogFileFallback: '開啟日志檔失敗 .',
    refreshOnlyImported: '刷新只提供被匯入的紀錄檔 .',
    failedToReadLogFile: '讀取紀錄檔失敗: {message}',
    failedToReadLogFileFallback: '讀取日志檔失敗 .',
    reloadedLinesFrom: 'Reloaded {count} lines from {file}.',
    sessionClosed: '第 二 章.',
    disconnected: '有接通.',
    reconnecting: '正在重接中...',
    failedToReconnect: '重新連接失敗 .',
    autoSaveDialogTitle: 'Select log file to auto-save SSH output',
    allFiles: '所有文件',
    autoSaveCancelled: '自動儲存已取消 .',
    autoSaveFailed: '自動儲存失敗: {message}',
    autoSaveFailedFallback: '自動儲存失敗 .',
    hostKeyVerificationFailed:
      'Host key verification failed for {target}. Expected {expected} but received {received}. Update the fingerprint in settings to reconnect.',
    sshSessionClosedOn: '--- SSH session closed on {timestamp}',
  },
};
